/* ApplicationWindow.c generated by valac 0.50.1.78-abc6b, the Vala compiler
 * generated from ApplicationWindow.vala, do not modify */

/* Replay - An open source YouTube client for GNOME
 * Copyright 2019 - 2020 Nahuel Gomez Castro <nahuel.gomezcastro@outlook.com.ar>
 *
 * Replay is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Replay is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Replay.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <handy.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>

#define REPLAY_TYPE_APPLICATION_WINDOW (replay_application_window_get_type ())
#define REPLAY_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_APPLICATION_WINDOW, ReplayApplicationWindow))
#define REPLAY_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_APPLICATION_WINDOW, ReplayApplicationWindowClass))
#define REPLAY_IS_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_APPLICATION_WINDOW))
#define REPLAY_IS_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_APPLICATION_WINDOW))
#define REPLAY_APPLICATION_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_APPLICATION_WINDOW, ReplayApplicationWindowClass))

typedef struct _ReplayApplicationWindow ReplayApplicationWindow;
typedef struct _ReplayApplicationWindowClass ReplayApplicationWindowClass;
typedef struct _ReplayApplicationWindowPrivate ReplayApplicationWindowPrivate;

#define REPLAY_TYPE_HEADER_BAR (replay_header_bar_get_type ())
#define REPLAY_HEADER_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_HEADER_BAR, ReplayHeaderBar))
#define REPLAY_HEADER_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_HEADER_BAR, ReplayHeaderBarClass))
#define REPLAY_IS_HEADER_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_HEADER_BAR))
#define REPLAY_IS_HEADER_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_HEADER_BAR))
#define REPLAY_HEADER_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_HEADER_BAR, ReplayHeaderBarClass))

typedef struct _ReplayHeaderBar ReplayHeaderBar;
typedef struct _ReplayHeaderBarClass ReplayHeaderBarClass;
typedef enum  {
	REPLAY_ADAPTIVE_MODE_NARROW,
	REPLAY_ADAPTIVE_MODE_NORMAL
} ReplayAdaptiveMode;

#define REPLAY_TYPE_ADAPTIVE_MODE (replay_adaptive_mode_get_type ())
enum  {
	REPLAY_APPLICATION_WINDOW_0_PROPERTY,
	REPLAY_APPLICATION_WINDOW_ADAPTIVE_MODE_PROPERTY,
	REPLAY_APPLICATION_WINDOW_APPLICATION_PROPERTY,
	REPLAY_APPLICATION_WINDOW_PAGES_PROPERTY,
	REPLAY_APPLICATION_WINDOW_NUM_PROPERTIES
};
static GParamSpec* replay_application_window_properties[REPLAY_APPLICATION_WINDOW_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _ReplayApplicationWindow {
	HdyApplicationWindow parent_instance;
	ReplayApplicationWindowPrivate * priv;
};

struct _ReplayApplicationWindowClass {
	HdyApplicationWindowClass parent_class;
};

struct _ReplayApplicationWindowPrivate {
	GtkStack* _content_stack;
	ReplayHeaderBar* _header_bar;
	GtkRevealer* _revealer;
	ReplayAdaptiveMode _adaptive_mode;
	GListModel* _pages;
};

static gint ReplayApplicationWindow_private_offset;
static gpointer replay_application_window_parent_class = NULL;

GType replay_application_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayApplicationWindow, g_object_unref)
GType replay_header_bar_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayHeaderBar, g_object_unref)
GType replay_adaptive_mode_get_type (void) G_GNUC_CONST ;
ReplayApplicationWindow* replay_application_window_new (GtkApplication* application,
                                                        GListModel* pages);
ReplayApplicationWindow* replay_application_window_construct (GType object_type,
                                                              GtkApplication* application,
                                                              GListModel* pages);
static void replay_application_window_real_size_allocate (GtkWidget* base,
                                                   gint width,
                                                   gint height,
                                                   gint baseline);
void replay_application_window_set_adaptive_mode (ReplayApplicationWindow* self,
                                                  ReplayAdaptiveMode value);
void replay_header_bar_set_adaptive_mode (ReplayHeaderBar* self,
                                          ReplayAdaptiveMode value);
ReplayAdaptiveMode replay_application_window_get_adaptive_mode (ReplayApplicationWindow* self);
GtkApplication* replay_application_window_get_application (ReplayApplicationWindow* self);
static void replay_application_window_set_application (ReplayApplicationWindow* self,
                                                GtkApplication* value);
GListModel* replay_application_window_get_pages (ReplayApplicationWindow* self);
static void replay_application_window_set_pages (ReplayApplicationWindow* self,
                                          GListModel* value);
static GObject * replay_application_window_constructor (GType type,
                                                 guint n_construct_properties,
                                                 GObjectConstructParam * construct_properties);
static void replay_application_window_finalize (GObject * obj);
static GType replay_application_window_get_type_once (void);
static void _vala_replay_application_window_get_property (GObject * object,
                                                   guint property_id,
                                                   GValue * value,
                                                   GParamSpec * pspec);
static void _vala_replay_application_window_set_property (GObject * object,
                                                   guint property_id,
                                                   const GValue * value,
                                                   GParamSpec * pspec);

static inline gpointer
replay_application_window_get_instance_private (ReplayApplicationWindow* self)
{
	return G_STRUCT_MEMBER_P (self, ReplayApplicationWindow_private_offset);
}

ReplayApplicationWindow*
replay_application_window_construct (GType object_type,
                                     GtkApplication* application,
                                     GListModel* pages)
{
	ReplayApplicationWindow * self = NULL;
#line 61 "../src/Windows/ApplicationWindow.vala"
	g_return_val_if_fail (application != NULL, NULL);
#line 61 "../src/Windows/ApplicationWindow.vala"
	g_return_val_if_fail (pages != NULL, NULL);
#line 63 "../src/Windows/ApplicationWindow.vala"
	self = (ReplayApplicationWindow*) g_object_new (object_type, "application", application, "pages", pages, NULL);
#line 61 "../src/Windows/ApplicationWindow.vala"
	return self;
#line 145 "ApplicationWindow.c"
}

ReplayApplicationWindow*
replay_application_window_new (GtkApplication* application,
                               GListModel* pages)
{
#line 61 "../src/Windows/ApplicationWindow.vala"
	return replay_application_window_construct (REPLAY_TYPE_APPLICATION_WINDOW, application, pages);
#line 154 "ApplicationWindow.c"
}

static void
replay_application_window_real_size_allocate (GtkWidget* base,
                                              gint width,
                                              gint height,
                                              gint baseline)
{
	ReplayApplicationWindow * self;
#line 70 "../src/Windows/ApplicationWindow.vala"
	self = (ReplayApplicationWindow*) base;
#line 72 "../src/Windows/ApplicationWindow.vala"
	GTK_WIDGET_CLASS (replay_application_window_parent_class)->size_allocate ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, hdy_application_window_get_type (), HdyApplicationWindow), width, height, baseline);
#line 74 "../src/Windows/ApplicationWindow.vala"
	if (width < 576) {
#line 170 "ApplicationWindow.c"
		ReplayHeaderBar* _tmp0_;
#line 76 "../src/Windows/ApplicationWindow.vala"
		replay_application_window_set_adaptive_mode (self, REPLAY_ADAPTIVE_MODE_NARROW);
#line 77 "../src/Windows/ApplicationWindow.vala"
		_tmp0_ = self->priv->_header_bar;
#line 77 "../src/Windows/ApplicationWindow.vala"
		replay_header_bar_set_adaptive_mode (_tmp0_, REPLAY_ADAPTIVE_MODE_NARROW);
#line 178 "ApplicationWindow.c"
	} else {
		ReplayHeaderBar* _tmp1_;
#line 81 "../src/Windows/ApplicationWindow.vala"
		replay_application_window_set_adaptive_mode (self, REPLAY_ADAPTIVE_MODE_NORMAL);
#line 82 "../src/Windows/ApplicationWindow.vala"
		_tmp1_ = self->priv->_header_bar;
#line 82 "../src/Windows/ApplicationWindow.vala"
		replay_header_bar_set_adaptive_mode (_tmp1_, REPLAY_ADAPTIVE_MODE_NORMAL);
#line 187 "ApplicationWindow.c"
	}
}

ReplayAdaptiveMode
replay_application_window_get_adaptive_mode (ReplayApplicationWindow* self)
{
	ReplayAdaptiveMode result;
	ReplayAdaptiveMode _tmp0_;
#line 30 "../src/Windows/ApplicationWindow.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 30 "../src/Windows/ApplicationWindow.vala"
	_tmp0_ = self->priv->_adaptive_mode;
#line 30 "../src/Windows/ApplicationWindow.vala"
	result = _tmp0_;
#line 30 "../src/Windows/ApplicationWindow.vala"
	return result;
#line 204 "ApplicationWindow.c"
}

void
replay_application_window_set_adaptive_mode (ReplayApplicationWindow* self,
                                             ReplayAdaptiveMode value)
{
	ReplayAdaptiveMode _tmp0_;
	ReplayAdaptiveMode _tmp1_;
#line 31 "../src/Windows/ApplicationWindow.vala"
	g_return_if_fail (self != NULL);
#line 33 "../src/Windows/ApplicationWindow.vala"
	_tmp0_ = self->priv->_adaptive_mode;
#line 33 "../src/Windows/ApplicationWindow.vala"
	if (_tmp0_ == value) {
#line 33 "../src/Windows/ApplicationWindow.vala"
		return;
#line 221 "ApplicationWindow.c"
	}
#line 34 "../src/Windows/ApplicationWindow.vala"
	self->priv->_adaptive_mode = value;
#line 36 "../src/Windows/ApplicationWindow.vala"
	_tmp1_ = self->priv->_adaptive_mode;
#line 36 "../src/Windows/ApplicationWindow.vala"
	switch (_tmp1_) {
#line 36 "../src/Windows/ApplicationWindow.vala"
		case REPLAY_ADAPTIVE_MODE_NARROW:
#line 231 "ApplicationWindow.c"
		{
			GtkRevealer* _tmp2_;
#line 39 "../src/Windows/ApplicationWindow.vala"
			_tmp2_ = self->priv->_revealer;
#line 39 "../src/Windows/ApplicationWindow.vala"
			gtk_revealer_set_reveal_child (_tmp2_, FALSE);
#line 40 "../src/Windows/ApplicationWindow.vala"
			break;
#line 240 "ApplicationWindow.c"
		}
#line 36 "../src/Windows/ApplicationWindow.vala"
		case REPLAY_ADAPTIVE_MODE_NORMAL:
#line 244 "ApplicationWindow.c"
		{
			GtkRevealer* _tmp3_;
#line 42 "../src/Windows/ApplicationWindow.vala"
			_tmp3_ = self->priv->_revealer;
#line 42 "../src/Windows/ApplicationWindow.vala"
			gtk_revealer_set_reveal_child (_tmp3_, TRUE);
#line 43 "../src/Windows/ApplicationWindow.vala"
			break;
#line 253 "ApplicationWindow.c"
		}
		default:
#line 36 "../src/Windows/ApplicationWindow.vala"
		break;
#line 258 "ApplicationWindow.c"
	}
#line 31 "../src/Windows/ApplicationWindow.vala"
	g_object_notify_by_pspec ((GObject *) self, replay_application_window_properties[REPLAY_APPLICATION_WINDOW_ADAPTIVE_MODE_PROPERTY]);
#line 262 "ApplicationWindow.c"
}

GtkApplication*
replay_application_window_get_application (ReplayApplicationWindow* self)
{
	GtkApplication* result;
	GtkApplication* _tmp0_;
	GtkApplication* _tmp1_;
#line 50 "../src/Windows/ApplicationWindow.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 50 "../src/Windows/ApplicationWindow.vala"
	_tmp0_ = gtk_window_get_application ((GtkWindow*) G_TYPE_CHECK_INSTANCE_CAST (self, hdy_application_window_get_type (), HdyApplicationWindow));
#line 50 "../src/Windows/ApplicationWindow.vala"
	_tmp1_ = _tmp0_;
#line 50 "../src/Windows/ApplicationWindow.vala"
	result = _tmp1_;
#line 50 "../src/Windows/ApplicationWindow.vala"
	return result;
#line 281 "ApplicationWindow.c"
}

static void
replay_application_window_set_application (ReplayApplicationWindow* self,
                                           GtkApplication* value)
{
	GtkApplication* _tmp0_;
	GtkApplication* _tmp1_;
#line 51 "../src/Windows/ApplicationWindow.vala"
	g_return_if_fail (self != NULL);
#line 53 "../src/Windows/ApplicationWindow.vala"
	_tmp0_ = gtk_window_get_application ((GtkWindow*) G_TYPE_CHECK_INSTANCE_CAST (self, hdy_application_window_get_type (), HdyApplicationWindow));
#line 53 "../src/Windows/ApplicationWindow.vala"
	_tmp1_ = _tmp0_;
#line 53 "../src/Windows/ApplicationWindow.vala"
	if (_tmp1_ == value) {
#line 53 "../src/Windows/ApplicationWindow.vala"
		return;
#line 300 "ApplicationWindow.c"
	}
#line 54 "../src/Windows/ApplicationWindow.vala"
	gtk_window_set_application ((GtkWindow*) G_TYPE_CHECK_INSTANCE_CAST (self, hdy_application_window_get_type (), HdyApplicationWindow), value);
#line 51 "../src/Windows/ApplicationWindow.vala"
	g_object_notify_by_pspec ((GObject *) self, replay_application_window_properties[REPLAY_APPLICATION_WINDOW_APPLICATION_PROPERTY]);
#line 306 "ApplicationWindow.c"
}

GListModel*
replay_application_window_get_pages (ReplayApplicationWindow* self)
{
	GListModel* result;
	GListModel* _tmp0_;
#line 58 "../src/Windows/ApplicationWindow.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 58 "../src/Windows/ApplicationWindow.vala"
	_tmp0_ = self->priv->_pages;
#line 58 "../src/Windows/ApplicationWindow.vala"
	result = _tmp0_;
#line 58 "../src/Windows/ApplicationWindow.vala"
	return result;
#line 322 "ApplicationWindow.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 58 "../src/Windows/ApplicationWindow.vala"
	return self ? g_object_ref (self) : NULL;
#line 330 "ApplicationWindow.c"
}

static void
replay_application_window_set_pages (ReplayApplicationWindow* self,
                                     GListModel* value)
{
#line 58 "../src/Windows/ApplicationWindow.vala"
	g_return_if_fail (self != NULL);
#line 58 "../src/Windows/ApplicationWindow.vala"
	if (replay_application_window_get_pages (self) != value) {
#line 341 "ApplicationWindow.c"
		GListModel* _tmp0_;
#line 58 "../src/Windows/ApplicationWindow.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 58 "../src/Windows/ApplicationWindow.vala"
		_g_object_unref0 (self->priv->_pages);
#line 58 "../src/Windows/ApplicationWindow.vala"
		self->priv->_pages = _tmp0_;
#line 58 "../src/Windows/ApplicationWindow.vala"
		g_object_notify_by_pspec ((GObject *) self, replay_application_window_properties[REPLAY_APPLICATION_WINDOW_PAGES_PROPERTY]);
#line 351 "ApplicationWindow.c"
	}
}

static GObject *
replay_application_window_constructor (GType type,
                                       guint n_construct_properties,
                                       GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	ReplayApplicationWindow * self;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_;
#line 86 "../src/Windows/ApplicationWindow.vala"
	parent_class = G_OBJECT_CLASS (replay_application_window_parent_class);
#line 86 "../src/Windows/ApplicationWindow.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 86 "../src/Windows/ApplicationWindow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, REPLAY_TYPE_APPLICATION_WINDOW, ReplayApplicationWindow);
#line 88 "../src/Windows/ApplicationWindow.vala"
	_tmp1_ = g_get_application_name ();
#line 88 "../src/Windows/ApplicationWindow.vala"
	_tmp0_ = _tmp1_;
#line 88 "../src/Windows/ApplicationWindow.vala"
	if (_tmp0_ == NULL) {
#line 88 "../src/Windows/ApplicationWindow.vala"
		_tmp0_ = "";
#line 379 "ApplicationWindow.c"
	}
#line 88 "../src/Windows/ApplicationWindow.vala"
	gtk_window_set_title ((GtkWindow*) self, (const gchar*) _tmp0_);
#line 90 "../src/Windows/ApplicationWindow.vala"
	gtk_widget_add_css_class ((GtkWidget*) self, "devel");
#line 86 "../src/Windows/ApplicationWindow.vala"
	return obj;
#line 387 "ApplicationWindow.c"
}

static void
replay_application_window_class_init (ReplayApplicationWindowClass * klass,
                                      gpointer klass_data)
{
#line 19 "../src/Windows/ApplicationWindow.vala"
	replay_application_window_parent_class = g_type_class_peek_parent (klass);
#line 19 "../src/Windows/ApplicationWindow.vala"
	g_type_class_adjust_private_offset (klass, &ReplayApplicationWindow_private_offset);
#line 19 "../src/Windows/ApplicationWindow.vala"
	((GtkWidgetClass *) klass)->size_allocate = (void (*) (GtkWidget*, gint, gint, gint)) replay_application_window_real_size_allocate;
#line 19 "../src/Windows/ApplicationWindow.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_replay_application_window_get_property;
#line 19 "../src/Windows/ApplicationWindow.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_replay_application_window_set_property;
#line 19 "../src/Windows/ApplicationWindow.vala"
	G_OBJECT_CLASS (klass)->constructor = replay_application_window_constructor;
#line 19 "../src/Windows/ApplicationWindow.vala"
	G_OBJECT_CLASS (klass)->finalize = replay_application_window_finalize;
#line 19 "../src/Windows/ApplicationWindow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_APPLICATION_WINDOW_ADAPTIVE_MODE_PROPERTY, replay_application_window_properties[REPLAY_APPLICATION_WINDOW_ADAPTIVE_MODE_PROPERTY] = g_param_spec_enum ("adaptive-mode", "adaptive-mode", "adaptive-mode", REPLAY_TYPE_ADAPTIVE_MODE, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 19 "../src/Windows/ApplicationWindow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_APPLICATION_WINDOW_APPLICATION_PROPERTY, replay_application_window_properties[REPLAY_APPLICATION_WINDOW_APPLICATION_PROPERTY] = g_param_spec_object ("application", "application", "application", gtk_application_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 19 "../src/Windows/ApplicationWindow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_APPLICATION_WINDOW_PAGES_PROPERTY, replay_application_window_properties[REPLAY_APPLICATION_WINDOW_PAGES_PROPERTY] = g_param_spec_object ("pages", "pages", "pages", g_list_model_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 19 "../src/Windows/ApplicationWindow.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/io/github/nahuelwexd/Replay/ApplicationWindow.ui");
#line 19 "../src/Windows/ApplicationWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "_content_stack", FALSE, ReplayApplicationWindow_private_offset + G_STRUCT_OFFSET (ReplayApplicationWindowPrivate, _content_stack));
#line 19 "../src/Windows/ApplicationWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "_header_bar", FALSE, ReplayApplicationWindow_private_offset + G_STRUCT_OFFSET (ReplayApplicationWindowPrivate, _header_bar));
#line 19 "../src/Windows/ApplicationWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "_revealer", FALSE, ReplayApplicationWindow_private_offset + G_STRUCT_OFFSET (ReplayApplicationWindowPrivate, _revealer));
#line 422 "ApplicationWindow.c"
}

static void
replay_application_window_instance_init (ReplayApplicationWindow * self,
                                         gpointer klass)
{
#line 19 "../src/Windows/ApplicationWindow.vala"
	self->priv = replay_application_window_get_instance_private (self);
#line 19 "../src/Windows/ApplicationWindow.vala"
	g_type_ensure (REPLAY_TYPE_HEADER_BAR);
#line 19 "../src/Windows/ApplicationWindow.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 435 "ApplicationWindow.c"
}

static void
replay_application_window_finalize (GObject * obj)
{
	ReplayApplicationWindow * self;
#line 19 "../src/Windows/ApplicationWindow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, REPLAY_TYPE_APPLICATION_WINDOW, ReplayApplicationWindow);
#line 21 "../src/Windows/ApplicationWindow.vala"
	_g_object_unref0 (self->priv->_content_stack);
#line 22 "../src/Windows/ApplicationWindow.vala"
	_g_object_unref0 (self->priv->_header_bar);
#line 23 "../src/Windows/ApplicationWindow.vala"
	_g_object_unref0 (self->priv->_revealer);
#line 58 "../src/Windows/ApplicationWindow.vala"
	_g_object_unref0 (self->priv->_pages);
#line 19 "../src/Windows/ApplicationWindow.vala"
	G_OBJECT_CLASS (replay_application_window_parent_class)->finalize (obj);
#line 454 "ApplicationWindow.c"
}

static GType
replay_application_window_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ReplayApplicationWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) replay_application_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReplayApplicationWindow), 0, (GInstanceInitFunc) replay_application_window_instance_init, NULL };
	GType replay_application_window_type_id;
	replay_application_window_type_id = g_type_register_static (hdy_application_window_get_type (), "ReplayApplicationWindow", &g_define_type_info, 0);
	ReplayApplicationWindow_private_offset = g_type_add_instance_private (replay_application_window_type_id, sizeof (ReplayApplicationWindowPrivate));
	return replay_application_window_type_id;
}

GType
replay_application_window_get_type (void)
{
	static volatile gsize replay_application_window_type_id__volatile = 0;
	if (g_once_init_enter (&replay_application_window_type_id__volatile)) {
		GType replay_application_window_type_id;
		replay_application_window_type_id = replay_application_window_get_type_once ();
		g_once_init_leave (&replay_application_window_type_id__volatile, replay_application_window_type_id);
	}
	return replay_application_window_type_id__volatile;
}

static void
_vala_replay_application_window_get_property (GObject * object,
                                              guint property_id,
                                              GValue * value,
                                              GParamSpec * pspec)
{
	ReplayApplicationWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, REPLAY_TYPE_APPLICATION_WINDOW, ReplayApplicationWindow);
#line 19 "../src/Windows/ApplicationWindow.vala"
	switch (property_id) {
#line 19 "../src/Windows/ApplicationWindow.vala"
		case REPLAY_APPLICATION_WINDOW_ADAPTIVE_MODE_PROPERTY:
#line 19 "../src/Windows/ApplicationWindow.vala"
		g_value_set_enum (value, replay_application_window_get_adaptive_mode (self));
#line 19 "../src/Windows/ApplicationWindow.vala"
		break;
#line 19 "../src/Windows/ApplicationWindow.vala"
		case REPLAY_APPLICATION_WINDOW_APPLICATION_PROPERTY:
#line 19 "../src/Windows/ApplicationWindow.vala"
		g_value_set_object (value, replay_application_window_get_application (self));
#line 19 "../src/Windows/ApplicationWindow.vala"
		break;
#line 19 "../src/Windows/ApplicationWindow.vala"
		case REPLAY_APPLICATION_WINDOW_PAGES_PROPERTY:
#line 19 "../src/Windows/ApplicationWindow.vala"
		g_value_set_object (value, replay_application_window_get_pages (self));
#line 19 "../src/Windows/ApplicationWindow.vala"
		break;
#line 507 "ApplicationWindow.c"
		default:
#line 19 "../src/Windows/ApplicationWindow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 19 "../src/Windows/ApplicationWindow.vala"
		break;
#line 513 "ApplicationWindow.c"
	}
}

static void
_vala_replay_application_window_set_property (GObject * object,
                                              guint property_id,
                                              const GValue * value,
                                              GParamSpec * pspec)
{
	ReplayApplicationWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, REPLAY_TYPE_APPLICATION_WINDOW, ReplayApplicationWindow);
#line 19 "../src/Windows/ApplicationWindow.vala"
	switch (property_id) {
#line 19 "../src/Windows/ApplicationWindow.vala"
		case REPLAY_APPLICATION_WINDOW_ADAPTIVE_MODE_PROPERTY:
#line 19 "../src/Windows/ApplicationWindow.vala"
		replay_application_window_set_adaptive_mode (self, g_value_get_enum (value));
#line 19 "../src/Windows/ApplicationWindow.vala"
		break;
#line 19 "../src/Windows/ApplicationWindow.vala"
		case REPLAY_APPLICATION_WINDOW_APPLICATION_PROPERTY:
#line 19 "../src/Windows/ApplicationWindow.vala"
		replay_application_window_set_application (self, g_value_get_object (value));
#line 19 "../src/Windows/ApplicationWindow.vala"
		break;
#line 19 "../src/Windows/ApplicationWindow.vala"
		case REPLAY_APPLICATION_WINDOW_PAGES_PROPERTY:
#line 19 "../src/Windows/ApplicationWindow.vala"
		replay_application_window_set_pages (self, g_value_get_object (value));
#line 19 "../src/Windows/ApplicationWindow.vala"
		break;
#line 545 "ApplicationWindow.c"
		default:
#line 19 "../src/Windows/ApplicationWindow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 19 "../src/Windows/ApplicationWindow.vala"
		break;
#line 551 "ApplicationWindow.c"
	}
}

