/* PreferencesWindow.c generated by valac 0.50.1.78-abc6b, the Vala compiler
 * generated from PreferencesWindow.vala, do not modify */

/* Replay - An open source YouTube client for GNOME
 * Copyright 2019 - 2020 Nahuel Gomez Castro <nahuel.gomezcastro@outlook.com.ar>
 *
 * Replay is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Replay is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Replay.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <handy.h>
#include <glib-object.h>

#define REPLAY_TYPE_PREFERENCES_WINDOW (replay_preferences_window_get_type ())
#define REPLAY_PREFERENCES_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_PREFERENCES_WINDOW, ReplayPreferencesWindow))
#define REPLAY_PREFERENCES_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_PREFERENCES_WINDOW, ReplayPreferencesWindowClass))
#define REPLAY_IS_PREFERENCES_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_PREFERENCES_WINDOW))
#define REPLAY_IS_PREFERENCES_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_PREFERENCES_WINDOW))
#define REPLAY_PREFERENCES_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_PREFERENCES_WINDOW, ReplayPreferencesWindowClass))

typedef struct _ReplayPreferencesWindow ReplayPreferencesWindow;
typedef struct _ReplayPreferencesWindowClass ReplayPreferencesWindowClass;
typedef struct _ReplayPreferencesWindowPrivate ReplayPreferencesWindowPrivate;
enum  {
	REPLAY_PREFERENCES_WINDOW_0_PROPERTY,
	REPLAY_PREFERENCES_WINDOW_NUM_PROPERTIES
};
static GParamSpec* replay_preferences_window_properties[REPLAY_PREFERENCES_WINDOW_NUM_PROPERTIES];

struct _ReplayPreferencesWindow {
	HdyPreferencesWindow parent_instance;
	ReplayPreferencesWindowPrivate * priv;
};

struct _ReplayPreferencesWindowClass {
	HdyPreferencesWindowClass parent_class;
};

static gpointer replay_preferences_window_parent_class = NULL;

GType replay_preferences_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayPreferencesWindow, g_object_unref)
ReplayPreferencesWindow* replay_preferences_window_new (void);
ReplayPreferencesWindow* replay_preferences_window_construct (GType object_type);
static GType replay_preferences_window_get_type_once (void);

ReplayPreferencesWindow*
replay_preferences_window_construct (GType object_type)
{
	ReplayPreferencesWindow * self = NULL;
#line 19 "../src/Windows/PreferencesWindow.vala"
	self = (ReplayPreferencesWindow*) g_object_new (object_type, NULL);
#line 19 "../src/Windows/PreferencesWindow.vala"
	return self;
#line 66 "PreferencesWindow.c"
}

ReplayPreferencesWindow*
replay_preferences_window_new (void)
{
#line 19 "../src/Windows/PreferencesWindow.vala"
	return replay_preferences_window_construct (REPLAY_TYPE_PREFERENCES_WINDOW);
#line 74 "PreferencesWindow.c"
}

static void
replay_preferences_window_class_init (ReplayPreferencesWindowClass * klass,
                                      gpointer klass_data)
{
#line 19 "../src/Windows/PreferencesWindow.vala"
	replay_preferences_window_parent_class = g_type_class_peek_parent (klass);
#line 19 "../src/Windows/PreferencesWindow.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/io/github/nahuelwexd/Replay/PreferencesWindow.ui");
#line 85 "PreferencesWindow.c"
}

static void
replay_preferences_window_instance_init (ReplayPreferencesWindow * self,
                                         gpointer klass)
{
#line 19 "../src/Windows/PreferencesWindow.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 94 "PreferencesWindow.c"
}

static GType
replay_preferences_window_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ReplayPreferencesWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) replay_preferences_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReplayPreferencesWindow), 0, (GInstanceInitFunc) replay_preferences_window_instance_init, NULL };
	GType replay_preferences_window_type_id;
	replay_preferences_window_type_id = g_type_register_static (hdy_preferences_window_get_type (), "ReplayPreferencesWindow", &g_define_type_info, 0);
	return replay_preferences_window_type_id;
}

GType
replay_preferences_window_get_type (void)
{
	static volatile gsize replay_preferences_window_type_id__volatile = 0;
	if (g_once_init_enter (&replay_preferences_window_type_id__volatile)) {
		GType replay_preferences_window_type_id;
		replay_preferences_window_type_id = replay_preferences_window_get_type_once ();
		g_once_init_leave (&replay_preferences_window_type_id__volatile, replay_preferences_window_type_id);
	}
	return replay_preferences_window_type_id__volatile;
}

