/* Application.c generated by valac 0.50.1.78-abc6b, the Vala compiler
 * generated from Application.vala, do not modify */

/* Replay - An open source YouTube client for GNOME
 * Copyright 2019 - 2020 Nahuel Gomez Castro <nahuel.gomezcastro@outlook.com.ar>
 *
 * Replay is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Replay is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Replay.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <gio/gio.h>
#include "config.h"
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <locale.h>
#include <glib/gi18n-lib.h>
#include <gdk/gdk.h>
#include <handy.h>
#include <vadi.h>

#define REPLAY_TYPE_APPLICATION (replay_application_get_type ())
#define REPLAY_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_APPLICATION, ReplayApplication))
#define REPLAY_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_APPLICATION, ReplayApplicationClass))
#define REPLAY_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_APPLICATION))
#define REPLAY_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_APPLICATION))
#define REPLAY_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_APPLICATION, ReplayApplicationClass))

typedef struct _ReplayApplication ReplayApplication;
typedef struct _ReplayApplicationClass ReplayApplicationClass;
typedef struct _ReplayApplicationPrivate ReplayApplicationPrivate;
enum  {
	REPLAY_APPLICATION_0_PROPERTY,
	REPLAY_APPLICATION_NUM_PROPERTIES
};
static GParamSpec* replay_application_properties[REPLAY_APPLICATION_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define REPLAY_TYPE_APPLICATION_WINDOW (replay_application_window_get_type ())
#define REPLAY_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_APPLICATION_WINDOW, ReplayApplicationWindow))
#define REPLAY_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_APPLICATION_WINDOW, ReplayApplicationWindowClass))
#define REPLAY_IS_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_APPLICATION_WINDOW))
#define REPLAY_IS_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_APPLICATION_WINDOW))
#define REPLAY_APPLICATION_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_APPLICATION_WINDOW, ReplayApplicationWindowClass))

typedef struct _ReplayApplicationWindow ReplayApplicationWindow;
typedef struct _ReplayApplicationWindowClass ReplayApplicationWindowClass;

#define REPLAY_TYPE_STACK_SIDEBAR (replay_stack_sidebar_get_type ())
#define REPLAY_STACK_SIDEBAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_STACK_SIDEBAR, ReplayStackSidebar))
#define REPLAY_STACK_SIDEBAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_STACK_SIDEBAR, ReplayStackSidebarClass))
#define REPLAY_IS_STACK_SIDEBAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_STACK_SIDEBAR))
#define REPLAY_IS_STACK_SIDEBAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_STACK_SIDEBAR))
#define REPLAY_STACK_SIDEBAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_STACK_SIDEBAR, ReplayStackSidebarClass))

typedef struct _ReplayStackSidebar ReplayStackSidebar;
typedef struct _ReplayStackSidebarClass ReplayStackSidebarClass;

#define REPLAY_TYPE_PREFERENCES_WINDOW (replay_preferences_window_get_type ())
#define REPLAY_PREFERENCES_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_PREFERENCES_WINDOW, ReplayPreferencesWindow))
#define REPLAY_PREFERENCES_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_PREFERENCES_WINDOW, ReplayPreferencesWindowClass))
#define REPLAY_IS_PREFERENCES_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_PREFERENCES_WINDOW))
#define REPLAY_IS_PREFERENCES_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_PREFERENCES_WINDOW))
#define REPLAY_PREFERENCES_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_PREFERENCES_WINDOW, ReplayPreferencesWindowClass))

typedef struct _ReplayPreferencesWindow ReplayPreferencesWindow;
typedef struct _ReplayPreferencesWindowClass ReplayPreferencesWindowClass;
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _ReplayApplication {
	GtkApplication parent_instance;
	ReplayApplicationPrivate * priv;
};

struct _ReplayApplicationClass {
	GtkApplicationClass parent_class;
};

static gpointer replay_application_parent_class = NULL;

GType replay_application_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayApplication, g_object_unref)
ReplayApplication* replay_application_new (void);
ReplayApplication* replay_application_construct (GType object_type);
gint replay_application_main (gchar** args,
                              gint args_length1);
static void replay_application_real_activate (GApplication* base);
static void replay_application_real_startup (GApplication* base);
static void replay_application_ensure_type_registration (ReplayApplication* self);
static void replay_application_register_actions (ReplayApplication* self);
VdiObjectFactory* replay_utils_get_factory (ReplayApplication* app);
GType replay_application_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayApplicationWindow, g_object_unref)
GType replay_stack_sidebar_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayStackSidebar, g_object_unref)
static void __lambda4_ (ReplayApplication* self,
                 GVariant* parameter);
static void replay_application_show_preferences_window (ReplayApplication* self);
static void ___lambda4__g_simple_action_activate (GSimpleAction* _sender,
                                           GVariant* parameter,
                                           gpointer self);
static void __lambda5_ (ReplayApplication* self,
                 GVariant* parameter);
static void replay_application_show_about_dialog (ReplayApplication* self);
static void ___lambda5__g_simple_action_activate (GSimpleAction* _sender,
                                           GVariant* parameter,
                                           gpointer self);
static void __lambda6_ (ReplayApplication* self,
                 GVariant* parameter);
static void ___lambda6__g_simple_action_activate (GSimpleAction* _sender,
                                           GVariant* parameter,
                                           gpointer self);
GType replay_preferences_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayPreferencesWindow, g_object_unref)
ReplayPreferencesWindow* replay_preferences_window_new (void);
ReplayPreferencesWindow* replay_preferences_window_construct (GType object_type);
static GType replay_application_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);

ReplayApplication*
replay_application_construct (GType object_type)
{
	ReplayApplication * self = NULL;
#line 22 "../src/Application.vala"
	self = (ReplayApplication*) g_object_new (object_type, "resource-base-path", RESOURCE_PATH, "application-id", APPLICATION_ID, "flags", G_APPLICATION_FLAGS_NONE, NULL);
#line 20 "../src/Application.vala"
	return self;
#line 150 "Application.c"
}

ReplayApplication*
replay_application_new (void)
{
#line 20 "../src/Application.vala"
	return replay_application_construct (REPLAY_TYPE_APPLICATION);
#line 158 "Application.c"
}

gint
replay_application_main (gchar** args,
                         gint args_length1)
{
	ReplayApplication* _tmp0_;
	ReplayApplication* _tmp1_;
	gint _tmp2_;
	gint result = 0;
#line 39 "../src/Application.vala"
	setlocale (LC_ALL, "");
#line 40 "../src/Application.vala"
	bindtextdomain (GETTEXT_PACKAGE, LOCALEDIR);
#line 41 "../src/Application.vala"
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
#line 42 "../src/Application.vala"
	textdomain (GETTEXT_PACKAGE);
#line 44 "../src/Application.vala"
	_tmp0_ = replay_application_new ();
#line 44 "../src/Application.vala"
	_tmp1_ = _tmp0_;
#line 44 "../src/Application.vala"
	_tmp2_ = g_application_run ((GApplication*) _tmp1_, (gint) args_length1, args);
#line 44 "../src/Application.vala"
	_g_object_unref0 (_tmp1_);
#line 44 "../src/Application.vala"
	result = _tmp2_;
#line 44 "../src/Application.vala"
	return result;
#line 189 "Application.c"
}

int
main (int argc,
      char ** argv)
{
#line 36 "../src/Application.vala"
	return replay_application_main (argv, argc);
#line 198 "Application.c"
}

static void
replay_application_real_activate (GApplication* base)
{
	ReplayApplication * self;
	GtkWindow* _tmp0_;
	GtkWindow* _tmp1_;
	GtkWindow* _tmp2_;
#line 48 "../src/Application.vala"
	self = (ReplayApplication*) base;
#line 48 "../src/Application.vala"
	_tmp0_ = gtk_application_get_active_window ((GtkApplication*) self);
#line 48 "../src/Application.vala"
	_vala_return_if_fail (_tmp0_ != NULL, "this.get_active_window () != null");
#line 51 "../src/Application.vala"
	_tmp1_ = gtk_application_get_active_window ((GtkApplication*) self);
#line 51 "../src/Application.vala"
	_tmp2_ = _tmp1_;
#line 51 "../src/Application.vala"
	gtk_window_present_with_time (_tmp2_, (guint32) GDK_CURRENT_TIME);
#line 220 "Application.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 62 "../src/Application.vala"
	return self ? g_object_ref (self) : NULL;
#line 228 "Application.c"
}

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result = NULL;
#line 1570 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1571 "glib-2.0.vapi"
	result = self;
#line 1571 "glib-2.0.vapi"
	return result;
#line 241 "Application.c"
}

static void
replay_application_real_startup (GApplication* base)
{
	ReplayApplication * self;
	GtkSettings* gtk_settings = NULL;
	GtkSettings* _tmp0_;
	GtkSettings* _tmp1_;
	GtkSettings* _tmp2_;
	GtkCssProvider* css_provider = NULL;
	GtkCssProvider* _tmp4_;
	GtkCssProvider* _tmp5_;
	const gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	GdkDisplay* display = NULL;
	GdkDisplay* _tmp9_;
	GdkDisplay* _tmp10_;
	GdkDisplay* _tmp11_;
	VdiObjectFactory* factory = NULL;
	VdiObjectFactory* _tmp14_;
	GObject* _tmp15_;
	GObject* _tmp16_;
#line 54 "../src/Application.vala"
	self = (ReplayApplication*) base;
#line 56 "../src/Application.vala"
	G_APPLICATION_CLASS (replay_application_parent_class)->startup ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication));
#line 59 "../src/Application.vala"
	g_set_application_name (_ ("Replay"));
#line 62 "../src/Application.vala"
	_tmp0_ = gtk_settings_get_default ();
#line 62 "../src/Application.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 62 "../src/Application.vala"
	gtk_settings = _tmp1_;
#line 63 "../src/Application.vala"
	_tmp2_ = gtk_settings;
#line 63 "../src/Application.vala"
	if (_tmp2_ != NULL) {
#line 282 "Application.c"
		GtkSettings* _tmp3_;
#line 64 "../src/Application.vala"
		_tmp3_ = gtk_settings;
#line 64 "../src/Application.vala"
		g_object_set (G_TYPE_CHECK_INSTANCE_CAST (_tmp3_, gtk_settings_get_type (), GtkSettings), "gtk-application-prefer-dark-theme", TRUE, NULL);
#line 288 "Application.c"
	}
#line 66 "../src/Application.vala"
	_tmp4_ = gtk_css_provider_new ();
#line 66 "../src/Application.vala"
	css_provider = _tmp4_;
#line 67 "../src/Application.vala"
	_tmp5_ = css_provider;
#line 67 "../src/Application.vala"
	_tmp6_ = string_to_string (RESOURCE_PATH);
#line 67 "../src/Application.vala"
	_tmp7_ = g_strconcat (_tmp6_, "/styles.css", NULL);
#line 67 "../src/Application.vala"
	_tmp8_ = _tmp7_;
#line 67 "../src/Application.vala"
	gtk_css_provider_load_from_resource (_tmp5_, _tmp8_);
#line 67 "../src/Application.vala"
	_g_free0 (_tmp8_);
#line 69 "../src/Application.vala"
	_tmp9_ = gdk_display_get_default ();
#line 69 "../src/Application.vala"
	_tmp10_ = _g_object_ref0 (_tmp9_);
#line 69 "../src/Application.vala"
	display = _tmp10_;
#line 70 "../src/Application.vala"
	_tmp11_ = display;
#line 70 "../src/Application.vala"
	if (_tmp11_ != NULL) {
#line 316 "Application.c"
		GdkDisplay* _tmp12_;
		GtkCssProvider* _tmp13_;
#line 72 "../src/Application.vala"
		_tmp12_ = display;
#line 72 "../src/Application.vala"
		_tmp13_ = css_provider;
#line 72 "../src/Application.vala"
		gtk_style_context_add_provider_for_display (G_TYPE_CHECK_INSTANCE_CAST (_tmp12_, gdk_display_get_type (), GdkDisplay), (GtkStyleProvider*) _tmp13_, (guint) GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
#line 325 "Application.c"
	}
#line 76 "../src/Application.vala"
	hdy_init ();
#line 78 "../src/Application.vala"
	replay_application_ensure_type_registration (self);
#line 79 "../src/Application.vala"
	replay_application_register_actions (self);
#line 81 "../src/Application.vala"
	_tmp14_ = replay_utils_get_factory (self);
#line 81 "../src/Application.vala"
	factory = _tmp14_;
#line 82 "../src/Application.vala"
	_tmp15_ = vdi_object_factory_withdraw (factory, REPLAY_TYPE_APPLICATION_WINDOW);
#line 82 "../src/Application.vala"
	_tmp16_ = _tmp15_;
#line 82 "../src/Application.vala"
	_g_object_unref0 (_tmp16_);
#line 54 "../src/Application.vala"
	_g_object_unref0 (factory);
#line 54 "../src/Application.vala"
	_g_object_unref0 (display);
#line 54 "../src/Application.vala"
	_g_object_unref0 (css_provider);
#line 54 "../src/Application.vala"
	_g_object_unref0 (gtk_settings);
#line 351 "Application.c"
}

static void
replay_application_ensure_type_registration (ReplayApplication* self)
{
#line 86 "../src/Application.vala"
	g_return_if_fail (self != NULL);
#line 88 "../src/Application.vala"
	g_type_ensure (REPLAY_TYPE_STACK_SIDEBAR);
#line 361 "Application.c"
}

static void
__lambda4_ (ReplayApplication* self,
            GVariant* parameter)
{
#line 94 "../src/Application.vala"
	replay_application_show_preferences_window (self);
#line 370 "Application.c"
}

static void
___lambda4__g_simple_action_activate (GSimpleAction* _sender,
                                      GVariant* parameter,
                                      gpointer self)
{
#line 94 "../src/Application.vala"
	__lambda4_ ((ReplayApplication*) self, parameter);
#line 380 "Application.c"
}

static void
__lambda5_ (ReplayApplication* self,
            GVariant* parameter)
{
#line 98 "../src/Application.vala"
	replay_application_show_about_dialog (self);
#line 389 "Application.c"
}

static void
___lambda5__g_simple_action_activate (GSimpleAction* _sender,
                                      GVariant* parameter,
                                      gpointer self)
{
#line 98 "../src/Application.vala"
	__lambda5_ ((ReplayApplication*) self, parameter);
#line 399 "Application.c"
}

static void
__lambda6_ (ReplayApplication* self,
            GVariant* parameter)
{
#line 102 "../src/Application.vala"
	g_application_quit ((GApplication*) self);
#line 408 "Application.c"
}

static void
___lambda6__g_simple_action_activate (GSimpleAction* _sender,
                                      GVariant* parameter,
                                      gpointer self)
{
#line 102 "../src/Application.vala"
	__lambda6_ ((ReplayApplication*) self, parameter);
#line 418 "Application.c"
}

static void
replay_application_register_actions (ReplayApplication* self)
{
	GSimpleAction* preferences_action = NULL;
	GSimpleAction* _tmp0_;
	GSimpleAction* about_action = NULL;
	GSimpleAction* _tmp1_;
	GSimpleAction* quit_action = NULL;
	GSimpleAction* _tmp2_;
	gchar* _tmp3_;
	gchar** _tmp4_;
	gchar** _tmp5_;
	gint _tmp5__length1;
#line 91 "../src/Application.vala"
	g_return_if_fail (self != NULL);
#line 93 "../src/Application.vala"
	_tmp0_ = g_simple_action_new ("preferences", NULL);
#line 93 "../src/Application.vala"
	preferences_action = _tmp0_;
#line 94 "../src/Application.vala"
	g_signal_connect_object (preferences_action, "activate", (GCallback) ___lambda4__g_simple_action_activate, self, 0);
#line 95 "../src/Application.vala"
	g_action_map_add_action ((GActionMap*) self, (GAction*) preferences_action);
#line 97 "../src/Application.vala"
	_tmp1_ = g_simple_action_new ("about", NULL);
#line 97 "../src/Application.vala"
	about_action = _tmp1_;
#line 98 "../src/Application.vala"
	g_signal_connect_object (about_action, "activate", (GCallback) ___lambda5__g_simple_action_activate, self, 0);
#line 99 "../src/Application.vala"
	g_action_map_add_action ((GActionMap*) self, (GAction*) about_action);
#line 101 "../src/Application.vala"
	_tmp2_ = g_simple_action_new ("quit", NULL);
#line 101 "../src/Application.vala"
	quit_action = _tmp2_;
#line 102 "../src/Application.vala"
	g_signal_connect_object (quit_action, "activate", (GCallback) ___lambda6__g_simple_action_activate, self, 0);
#line 103 "../src/Application.vala"
	_tmp3_ = g_strdup ("<Ctrl>Q");
#line 103 "../src/Application.vala"
	_tmp4_ = g_new0 (gchar*, 1 + 1);
#line 103 "../src/Application.vala"
	_tmp4_[0] = _tmp3_;
#line 103 "../src/Application.vala"
	_tmp5_ = _tmp4_;
#line 103 "../src/Application.vala"
	_tmp5__length1 = 1;
#line 103 "../src/Application.vala"
	gtk_application_set_accels_for_action ((GtkApplication*) self, "app.quit", _tmp5_);
#line 103 "../src/Application.vala"
	_tmp5_ = (_vala_array_free (_tmp5_, _tmp5__length1, (GDestroyNotify) g_free), NULL);
#line 104 "../src/Application.vala"
	g_action_map_add_action ((GActionMap*) self, (GAction*) quit_action);
#line 91 "../src/Application.vala"
	_g_object_unref0 (quit_action);
#line 91 "../src/Application.vala"
	_g_object_unref0 (about_action);
#line 91 "../src/Application.vala"
	_g_object_unref0 (preferences_action);
#line 480 "Application.c"
}

static void
replay_application_show_about_dialog (ReplayApplication* self)
{
	GtkWindow* _tmp0_;
	GtkAboutDialog* about_dialog = NULL;
	GtkWindow* _tmp1_;
	GtkWindow* _tmp2_;
	GtkWindow* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar** _tmp12_;
	GtkAboutDialog* _tmp13_ = NULL;
#line 107 "../src/Application.vala"
	g_return_if_fail (self != NULL);
#line 107 "../src/Application.vala"
	_tmp0_ = gtk_application_get_active_window ((GtkApplication*) self);
#line 107 "../src/Application.vala"
	_vala_return_if_fail (_tmp0_ != NULL, "this.get_active_window () != null");
#line 110 "../src/Application.vala"
	_tmp1_ = gtk_application_get_active_window ((GtkApplication*) self);
#line 110 "../src/Application.vala"
	_tmp2_ = _tmp1_;
#line 110 "../src/Application.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 110 "../src/Application.vala"
	_tmp4_ = g_strdup (_ ("About Replay"));
#line 110 "../src/Application.vala"
	_tmp5_ = g_strdup (APPLICATION_ID);
#line 110 "../src/Application.vala"
	_tmp6_ = g_strdup (VERSION);
#line 110 "../src/Application.vala"
	_tmp7_ = g_strdup (_ ("A new way to watch YouTube videos"));
#line 110 "../src/Application.vala"
	_tmp8_ = g_strdup (PROJECT_WEBSITE);
#line 110 "../src/Application.vala"
	_tmp9_ = g_strdup (_ ("Project repository"));
#line 110 "../src/Application.vala"
	_tmp10_ = g_strdup ("© 2019 - 2020 Nahuel Gomez Castro");
#line 110 "../src/Application.vala"
	_tmp11_ = g_strdup ("Nahuel Gomez Castro <nahuel.gomezcastro@outlook.com.ar>");
#line 110 "../src/Application.vala"
	_tmp12_ = g_new0 (gchar*, 1 + 1);
#line 110 "../src/Application.vala"
	_tmp12_[0] = _tmp11_;
#line 110 "../src/Application.vala"
	_tmp13_ = (GtkAboutDialog*) gtk_about_dialog_new ();
#line 110 "../src/Application.vala"
	gtk_window_set_transient_for ((GtkWindow*) _tmp13_, _tmp3_);
#line 110 "../src/Application.vala"
	_g_object_unref0 (_tmp3_);
#line 110 "../src/Application.vala"
	gtk_window_set_modal ((GtkWindow*) _tmp13_, TRUE);
#line 110 "../src/Application.vala"
	gtk_window_set_destroy_with_parent ((GtkWindow*) _tmp13_, TRUE);
#line 110 "../src/Application.vala"
	gtk_window_set_title ((GtkWindow*) _tmp13_, _tmp4_);
#line 110 "../src/Application.vala"
	_g_free0 (_tmp4_);
#line 110 "../src/Application.vala"
	gtk_about_dialog_set_logo_icon_name (_tmp13_, _tmp5_);
#line 110 "../src/Application.vala"
	_g_free0 (_tmp5_);
#line 110 "../src/Application.vala"
	gtk_about_dialog_set_version (_tmp13_, _tmp6_);
#line 110 "../src/Application.vala"
	_g_free0 (_tmp6_);
#line 110 "../src/Application.vala"
	gtk_about_dialog_set_comments (_tmp13_, _tmp7_);
#line 110 "../src/Application.vala"
	_g_free0 (_tmp7_);
#line 110 "../src/Application.vala"
	gtk_about_dialog_set_website (_tmp13_, _tmp8_);
#line 110 "../src/Application.vala"
	_g_free0 (_tmp8_);
#line 110 "../src/Application.vala"
	gtk_about_dialog_set_website_label (_tmp13_, _tmp9_);
#line 110 "../src/Application.vala"
	_g_free0 (_tmp9_);
#line 110 "../src/Application.vala"
	gtk_about_dialog_set_copyright (_tmp13_, _tmp10_);
#line 110 "../src/Application.vala"
	_g_free0 (_tmp10_);
#line 110 "../src/Application.vala"
	gtk_about_dialog_set_license_type (_tmp13_, GTK_LICENSE_GPL_3_0);
#line 110 "../src/Application.vala"
	gtk_about_dialog_set_authors (_tmp13_, _tmp12_);
#line 110 "../src/Application.vala"
	_tmp12_ = (_vala_array_free (_tmp12_, 1, (GDestroyNotify) g_free), NULL);
#line 110 "../src/Application.vala"
	g_object_ref_sink (_tmp13_);
#line 110 "../src/Application.vala"
	about_dialog = _tmp13_;
#line 126 "../src/Application.vala"
	gtk_window_present_with_time ((GtkWindow*) about_dialog, (guint32) GDK_CURRENT_TIME);
#line 107 "../src/Application.vala"
	_g_object_unref0 (about_dialog);
#line 585 "Application.c"
}

static void
replay_application_show_preferences_window (ReplayApplication* self)
{
	GtkWindow* _tmp0_;
	ReplayPreferencesWindow* preferences_window = NULL;
	GtkWindow* _tmp1_;
	GtkWindow* _tmp2_;
	GtkWindow* _tmp3_;
	ReplayPreferencesWindow* _tmp4_ = NULL;
#line 129 "../src/Application.vala"
	g_return_if_fail (self != NULL);
#line 129 "../src/Application.vala"
	_tmp0_ = gtk_application_get_active_window ((GtkApplication*) self);
#line 129 "../src/Application.vala"
	_vala_return_if_fail (_tmp0_ != NULL, "this.get_active_window () != null");
#line 132 "../src/Application.vala"
	_tmp1_ = gtk_application_get_active_window ((GtkApplication*) self);
#line 132 "../src/Application.vala"
	_tmp2_ = _tmp1_;
#line 132 "../src/Application.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 132 "../src/Application.vala"
	_tmp4_ = replay_preferences_window_new ();
#line 132 "../src/Application.vala"
	gtk_window_set_transient_for ((GtkWindow*) _tmp4_, _tmp3_);
#line 132 "../src/Application.vala"
	_g_object_unref0 (_tmp3_);
#line 132 "../src/Application.vala"
	gtk_window_set_modal ((GtkWindow*) _tmp4_, TRUE);
#line 132 "../src/Application.vala"
	gtk_window_set_destroy_with_parent ((GtkWindow*) _tmp4_, TRUE);
#line 132 "../src/Application.vala"
	g_object_ref_sink (_tmp4_);
#line 132 "../src/Application.vala"
	preferences_window = _tmp4_;
#line 139 "../src/Application.vala"
	gtk_window_present_with_time ((GtkWindow*) preferences_window, (guint32) GDK_CURRENT_TIME);
#line 129 "../src/Application.vala"
	_g_object_unref0 (preferences_window);
#line 627 "Application.c"
}

static void
replay_application_class_init (ReplayApplicationClass * klass,
                               gpointer klass_data)
{
#line 18 "../src/Application.vala"
	replay_application_parent_class = g_type_class_peek_parent (klass);
#line 18 "../src/Application.vala"
	((GApplicationClass *) klass)->activate = (void (*) (GApplication*)) replay_application_real_activate;
#line 18 "../src/Application.vala"
	((GApplicationClass *) klass)->startup = (void (*) (GApplication*)) replay_application_real_startup;
#line 640 "Application.c"
}

static void
replay_application_instance_init (ReplayApplication * self,
                                  gpointer klass)
{
}

static GType
replay_application_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ReplayApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) replay_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReplayApplication), 0, (GInstanceInitFunc) replay_application_instance_init, NULL };
	GType replay_application_type_id;
	replay_application_type_id = g_type_register_static (gtk_application_get_type (), "ReplayApplication", &g_define_type_info, 0);
	return replay_application_type_id;
}

GType
replay_application_get_type (void)
{
	static volatile gsize replay_application_type_id__volatile = 0;
	if (g_once_init_enter (&replay_application_type_id__volatile)) {
		GType replay_application_type_id;
		replay_application_type_id = replay_application_get_type_once ();
		g_once_init_leave (&replay_application_type_id__volatile, replay_application_type_id);
	}
	return replay_application_type_id__volatile;
}

static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gint i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

