/* Dao.c generated by valac 0.50.1.78-abc6b, the Vala compiler
 * generated from Dao.vala, do not modify */

/* Replay - An open source YouTube client for GNOME
 * Copyright 2019 - 2020 Nahuel Gomez Castro <nahuel.gomezcastro@outlook.com.ar>
 *
 * Replay is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Replay is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Replay.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <glib-object.h>

#define REPLAY_TYPE_DAO (replay_dao_get_type ())
#define REPLAY_DAO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_DAO, ReplayDao))
#define REPLAY_DAO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_DAO, ReplayDaoClass))
#define REPLAY_IS_DAO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_DAO))
#define REPLAY_IS_DAO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_DAO))
#define REPLAY_DAO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_DAO, ReplayDaoClass))

typedef struct _ReplayDao ReplayDao;
typedef struct _ReplayDaoClass ReplayDaoClass;
typedef struct _ReplayDaoPrivate ReplayDaoPrivate;
enum  {
	REPLAY_DAO_0_PROPERTY,
	REPLAY_DAO_NUM_PROPERTIES
};
static GParamSpec* replay_dao_properties[REPLAY_DAO_NUM_PROPERTIES];

struct _ReplayDao {
	GObject parent_instance;
	ReplayDaoPrivate * priv;
};

struct _ReplayDaoClass {
	GObjectClass parent_class;
};

static gpointer replay_dao_parent_class = NULL;

GType replay_dao_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayDao, g_object_unref)
ReplayDao* replay_dao_new (void);
ReplayDao* replay_dao_construct (GType object_type);
static GType replay_dao_get_type_once (void);

ReplayDao*
replay_dao_construct (GType object_type)
{
	ReplayDao * self = NULL;
#line 18 "../src/Database/Dao.vala"
	self = (ReplayDao*) g_object_new (object_type, NULL);
#line 18 "../src/Database/Dao.vala"
	return self;
#line 65 "Dao.c"
}

ReplayDao*
replay_dao_new (void)
{
#line 18 "../src/Database/Dao.vala"
	return replay_dao_construct (REPLAY_TYPE_DAO);
#line 73 "Dao.c"
}

static void
replay_dao_class_init (ReplayDaoClass * klass,
                       gpointer klass_data)
{
#line 18 "../src/Database/Dao.vala"
	replay_dao_parent_class = g_type_class_peek_parent (klass);
#line 82 "Dao.c"
}

static void
replay_dao_instance_init (ReplayDao * self,
                          gpointer klass)
{
}

static GType
replay_dao_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ReplayDaoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) replay_dao_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReplayDao), 0, (GInstanceInitFunc) replay_dao_instance_init, NULL };
	GType replay_dao_type_id;
	replay_dao_type_id = g_type_register_static (G_TYPE_OBJECT, "ReplayDao", &g_define_type_info, 0);
	return replay_dao_type_id;
}

GType
replay_dao_get_type (void)
{
	static volatile gsize replay_dao_type_id__volatile = 0;
	if (g_once_init_enter (&replay_dao_type_id__volatile)) {
		GType replay_dao_type_id;
		replay_dao_type_id = replay_dao_get_type_once ();
		g_once_init_leave (&replay_dao_type_id__volatile, replay_dao_type_id);
	}
	return replay_dao_type_id__volatile;
}

