/* HomeViewModel.c generated by valac 0.50.1.76-412f3, the Vala compiler
 * generated from HomeViewModel.vala, do not modify */

/* Replay - An open source YouTube client for GNOME
 * Copyright 2019 - 2020 Nahuel Gomez Castro <nahuel.gomezcastro@outlook.com.ar>
 *
 * Replay is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Replay is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Replay.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <glib-object.h>

#define REPLAY_TYPE_HOME_VIEW_MODEL (replay_home_view_model_get_type ())
#define REPLAY_HOME_VIEW_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_HOME_VIEW_MODEL, ReplayHomeViewModel))
#define REPLAY_HOME_VIEW_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_HOME_VIEW_MODEL, ReplayHomeViewModelClass))
#define REPLAY_IS_HOME_VIEW_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_HOME_VIEW_MODEL))
#define REPLAY_IS_HOME_VIEW_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_HOME_VIEW_MODEL))
#define REPLAY_HOME_VIEW_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_HOME_VIEW_MODEL, ReplayHomeViewModelClass))

typedef struct _ReplayHomeViewModel ReplayHomeViewModel;
typedef struct _ReplayHomeViewModelClass ReplayHomeViewModelClass;
typedef struct _ReplayHomeViewModelPrivate ReplayHomeViewModelPrivate;
enum  {
	REPLAY_HOME_VIEW_MODEL_0_PROPERTY,
	REPLAY_HOME_VIEW_MODEL_NUM_PROPERTIES
};
static GParamSpec* replay_home_view_model_properties[REPLAY_HOME_VIEW_MODEL_NUM_PROPERTIES];

struct _ReplayHomeViewModel {
	GObject parent_instance;
	ReplayHomeViewModelPrivate * priv;
};

struct _ReplayHomeViewModelClass {
	GObjectClass parent_class;
};

static gpointer replay_home_view_model_parent_class = NULL;

GType replay_home_view_model_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayHomeViewModel, g_object_unref)
ReplayHomeViewModel* replay_home_view_model_new (void);
ReplayHomeViewModel* replay_home_view_model_construct (GType object_type);
static GType replay_home_view_model_get_type_once (void);

ReplayHomeViewModel*
replay_home_view_model_construct (GType object_type)
{
	ReplayHomeViewModel * self = NULL;
#line 18 "../src/ViewModels/HomeViewModel.vala"
	self = (ReplayHomeViewModel*) g_object_new (object_type, NULL);
#line 18 "../src/ViewModels/HomeViewModel.vala"
	return self;
#line 65 "HomeViewModel.c"
}

ReplayHomeViewModel*
replay_home_view_model_new (void)
{
#line 18 "../src/ViewModels/HomeViewModel.vala"
	return replay_home_view_model_construct (REPLAY_TYPE_HOME_VIEW_MODEL);
#line 73 "HomeViewModel.c"
}

static void
replay_home_view_model_class_init (ReplayHomeViewModelClass * klass,
                                   gpointer klass_data)
{
#line 18 "../src/ViewModels/HomeViewModel.vala"
	replay_home_view_model_parent_class = g_type_class_peek_parent (klass);
#line 82 "HomeViewModel.c"
}

static void
replay_home_view_model_instance_init (ReplayHomeViewModel * self,
                                      gpointer klass)
{
}

static GType
replay_home_view_model_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ReplayHomeViewModelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) replay_home_view_model_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReplayHomeViewModel), 0, (GInstanceInitFunc) replay_home_view_model_instance_init, NULL };
	GType replay_home_view_model_type_id;
	replay_home_view_model_type_id = g_type_register_static (G_TYPE_OBJECT, "ReplayHomeViewModel", &g_define_type_info, 0);
	return replay_home_view_model_type_id;
}

GType
replay_home_view_model_get_type (void)
{
	static volatile gsize replay_home_view_model_type_id__volatile = 0;
	if (g_once_init_enter (&replay_home_view_model_type_id__volatile)) {
		GType replay_home_view_model_type_id;
		replay_home_view_model_type_id = replay_home_view_model_get_type_once ();
		g_once_init_leave (&replay_home_view_model_type_id__volatile, replay_home_view_model_type_id);
	}
	return replay_home_view_model_type_id__volatile;
}

