/* TrendingViewModel.c generated by valac 0.50.1.78-abc6b, the Vala compiler
 * generated from TrendingViewModel.vala, do not modify */

/* Replay - An open source YouTube client for GNOME
 * Copyright 2019 - 2020 Nahuel Gomez Castro <nahuel.gomezcastro@outlook.com.ar>
 *
 * Replay is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Replay is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Replay.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <glib-object.h>
#include <gee.h>
#include <glib.h>

#define REPLAY_TYPE_TRENDING_VIEW_MODEL (replay_trending_view_model_get_type ())
#define REPLAY_TRENDING_VIEW_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_TRENDING_VIEW_MODEL, ReplayTrendingViewModel))
#define REPLAY_TRENDING_VIEW_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_TRENDING_VIEW_MODEL, ReplayTrendingViewModelClass))
#define REPLAY_IS_TRENDING_VIEW_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_TRENDING_VIEW_MODEL))
#define REPLAY_IS_TRENDING_VIEW_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_TRENDING_VIEW_MODEL))
#define REPLAY_TRENDING_VIEW_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_TRENDING_VIEW_MODEL, ReplayTrendingViewModelClass))

typedef struct _ReplayTrendingViewModel ReplayTrendingViewModel;
typedef struct _ReplayTrendingViewModelClass ReplayTrendingViewModelClass;
typedef struct _ReplayTrendingViewModelPrivate ReplayTrendingViewModelPrivate;

#define REPLAY_TYPE_VIDEO (replay_video_get_type ())
#define REPLAY_VIDEO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_VIDEO, ReplayVideo))
#define REPLAY_VIDEO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_VIDEO, ReplayVideoClass))
#define REPLAY_IS_VIDEO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_VIDEO))
#define REPLAY_IS_VIDEO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_VIDEO))
#define REPLAY_VIDEO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_VIDEO, ReplayVideoClass))

typedef struct _ReplayVideo ReplayVideo;
typedef struct _ReplayVideoClass ReplayVideoClass;
enum  {
	REPLAY_TRENDING_VIEW_MODEL_0_PROPERTY,
	REPLAY_TRENDING_VIEW_MODEL_TRENDING_LIST_PROPERTY,
	REPLAY_TRENDING_VIEW_MODEL_NUM_PROPERTIES
};
static GParamSpec* replay_trending_view_model_properties[REPLAY_TRENDING_VIEW_MODEL_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define REPLAY_TYPE_OBSERVABLE_LIST (replay_observable_list_get_type ())
#define REPLAY_OBSERVABLE_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_OBSERVABLE_LIST, ReplayObservableList))
#define REPLAY_OBSERVABLE_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_OBSERVABLE_LIST, ReplayObservableListClass))
#define REPLAY_IS_OBSERVABLE_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_OBSERVABLE_LIST))
#define REPLAY_IS_OBSERVABLE_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_OBSERVABLE_LIST))
#define REPLAY_OBSERVABLE_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_OBSERVABLE_LIST, ReplayObservableListClass))

typedef struct _ReplayObservableList ReplayObservableList;
typedef struct _ReplayObservableListClass ReplayObservableListClass;

struct _ReplayTrendingViewModel {
	GObject parent_instance;
	ReplayTrendingViewModelPrivate * priv;
};

struct _ReplayTrendingViewModelClass {
	GObjectClass parent_class;
};

struct _ReplayTrendingViewModelPrivate {
	GeeList* _trending_list;
};

static gint ReplayTrendingViewModel_private_offset;
static gpointer replay_trending_view_model_parent_class = NULL;

GType replay_trending_view_model_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayTrendingViewModel, g_object_unref)
GType replay_video_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayVideo, g_object_unref)
ReplayTrendingViewModel* replay_trending_view_model_new (void);
ReplayTrendingViewModel* replay_trending_view_model_construct (GType object_type);
GeeList* replay_trending_view_model_get_trending_list (ReplayTrendingViewModel* self);
static GObject * replay_trending_view_model_constructor (GType type,
                                                  guint n_construct_properties,
                                                  GObjectConstructParam * construct_properties);
ReplayObservableList* replay_observable_list_new (GType t_type,
                                                  GBoxedCopyFunc t_dup_func,
                                                  GDestroyNotify t_destroy_func);
ReplayObservableList* replay_observable_list_construct (GType object_type,
                                                        GType t_type,
                                                        GBoxedCopyFunc t_dup_func,
                                                        GDestroyNotify t_destroy_func);
GType replay_observable_list_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayObservableList, g_object_unref)
static void replay_trending_view_model_finalize (GObject * obj);
static GType replay_trending_view_model_get_type_once (void);
static void _vala_replay_trending_view_model_get_property (GObject * object,
                                                    guint property_id,
                                                    GValue * value,
                                                    GParamSpec * pspec);

static inline gpointer
replay_trending_view_model_get_instance_private (ReplayTrendingViewModel* self)
{
	return G_STRUCT_MEMBER_P (self, ReplayTrendingViewModel_private_offset);
}

ReplayTrendingViewModel*
replay_trending_view_model_construct (GType object_type)
{
	ReplayTrendingViewModel * self = NULL;
#line 18 "../src/ViewModels/TrendingViewModel.vala"
	self = (ReplayTrendingViewModel*) g_object_new (object_type, NULL);
#line 18 "../src/ViewModels/TrendingViewModel.vala"
	return self;
#line 120 "TrendingViewModel.c"
}

ReplayTrendingViewModel*
replay_trending_view_model_new (void)
{
#line 18 "../src/ViewModels/TrendingViewModel.vala"
	return replay_trending_view_model_construct (REPLAY_TYPE_TRENDING_VIEW_MODEL);
#line 128 "TrendingViewModel.c"
}

GeeList*
replay_trending_view_model_get_trending_list (ReplayTrendingViewModel* self)
{
	GeeList* result;
	GeeList* _tmp0_;
#line 20 "../src/ViewModels/TrendingViewModel.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 20 "../src/ViewModels/TrendingViewModel.vala"
	_tmp0_ = self->priv->_trending_list;
#line 20 "../src/ViewModels/TrendingViewModel.vala"
	result = _tmp0_;
#line 20 "../src/ViewModels/TrendingViewModel.vala"
	return result;
#line 144 "TrendingViewModel.c"
}

static GObject *
replay_trending_view_model_constructor (GType type,
                                        guint n_construct_properties,
                                        GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	ReplayTrendingViewModel * self;
	ReplayObservableList* _tmp0_;
#line 23 "../src/ViewModels/TrendingViewModel.vala"
	parent_class = G_OBJECT_CLASS (replay_trending_view_model_parent_class);
#line 23 "../src/ViewModels/TrendingViewModel.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 23 "../src/ViewModels/TrendingViewModel.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, REPLAY_TYPE_TRENDING_VIEW_MODEL, ReplayTrendingViewModel);
#line 25 "../src/ViewModels/TrendingViewModel.vala"
	_tmp0_ = replay_observable_list_new (REPLAY_TYPE_VIDEO, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref);
#line 25 "../src/ViewModels/TrendingViewModel.vala"
	_g_object_unref0 (self->priv->_trending_list);
#line 25 "../src/ViewModels/TrendingViewModel.vala"
	self->priv->_trending_list = (GeeList*) _tmp0_;
#line 23 "../src/ViewModels/TrendingViewModel.vala"
	return obj;
#line 170 "TrendingViewModel.c"
}

static void
replay_trending_view_model_class_init (ReplayTrendingViewModelClass * klass,
                                       gpointer klass_data)
{
#line 18 "../src/ViewModels/TrendingViewModel.vala"
	replay_trending_view_model_parent_class = g_type_class_peek_parent (klass);
#line 18 "../src/ViewModels/TrendingViewModel.vala"
	g_type_class_adjust_private_offset (klass, &ReplayTrendingViewModel_private_offset);
#line 18 "../src/ViewModels/TrendingViewModel.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_replay_trending_view_model_get_property;
#line 18 "../src/ViewModels/TrendingViewModel.vala"
	G_OBJECT_CLASS (klass)->constructor = replay_trending_view_model_constructor;
#line 18 "../src/ViewModels/TrendingViewModel.vala"
	G_OBJECT_CLASS (klass)->finalize = replay_trending_view_model_finalize;
#line 18 "../src/ViewModels/TrendingViewModel.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_TRENDING_VIEW_MODEL_TRENDING_LIST_PROPERTY, replay_trending_view_model_properties[REPLAY_TRENDING_VIEW_MODEL_TRENDING_LIST_PROPERTY] = g_param_spec_object ("trending-list", "trending-list", "trending-list", GEE_TYPE_LIST, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
#line 189 "TrendingViewModel.c"
}

static void
replay_trending_view_model_instance_init (ReplayTrendingViewModel * self,
                                          gpointer klass)
{
#line 18 "../src/ViewModels/TrendingViewModel.vala"
	self->priv = replay_trending_view_model_get_instance_private (self);
#line 198 "TrendingViewModel.c"
}

static void
replay_trending_view_model_finalize (GObject * obj)
{
	ReplayTrendingViewModel * self;
#line 18 "../src/ViewModels/TrendingViewModel.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, REPLAY_TYPE_TRENDING_VIEW_MODEL, ReplayTrendingViewModel);
#line 20 "../src/ViewModels/TrendingViewModel.vala"
	_g_object_unref0 (self->priv->_trending_list);
#line 18 "../src/ViewModels/TrendingViewModel.vala"
	G_OBJECT_CLASS (replay_trending_view_model_parent_class)->finalize (obj);
#line 211 "TrendingViewModel.c"
}

static GType
replay_trending_view_model_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ReplayTrendingViewModelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) replay_trending_view_model_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReplayTrendingViewModel), 0, (GInstanceInitFunc) replay_trending_view_model_instance_init, NULL };
	GType replay_trending_view_model_type_id;
	replay_trending_view_model_type_id = g_type_register_static (G_TYPE_OBJECT, "ReplayTrendingViewModel", &g_define_type_info, 0);
	ReplayTrendingViewModel_private_offset = g_type_add_instance_private (replay_trending_view_model_type_id, sizeof (ReplayTrendingViewModelPrivate));
	return replay_trending_view_model_type_id;
}

GType
replay_trending_view_model_get_type (void)
{
	static volatile gsize replay_trending_view_model_type_id__volatile = 0;
	if (g_once_init_enter (&replay_trending_view_model_type_id__volatile)) {
		GType replay_trending_view_model_type_id;
		replay_trending_view_model_type_id = replay_trending_view_model_get_type_once ();
		g_once_init_leave (&replay_trending_view_model_type_id__volatile, replay_trending_view_model_type_id);
	}
	return replay_trending_view_model_type_id__volatile;
}

static void
_vala_replay_trending_view_model_get_property (GObject * object,
                                               guint property_id,
                                               GValue * value,
                                               GParamSpec * pspec)
{
	ReplayTrendingViewModel * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, REPLAY_TYPE_TRENDING_VIEW_MODEL, ReplayTrendingViewModel);
#line 18 "../src/ViewModels/TrendingViewModel.vala"
	switch (property_id) {
#line 18 "../src/ViewModels/TrendingViewModel.vala"
		case REPLAY_TRENDING_VIEW_MODEL_TRENDING_LIST_PROPERTY:
#line 18 "../src/ViewModels/TrendingViewModel.vala"
		g_value_set_object (value, replay_trending_view_model_get_trending_list (self));
#line 18 "../src/ViewModels/TrendingViewModel.vala"
		break;
#line 252 "TrendingViewModel.c"
		default:
#line 18 "../src/ViewModels/TrendingViewModel.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 18 "../src/ViewModels/TrendingViewModel.vala"
		break;
#line 258 "TrendingViewModel.c"
	}
}

