/* HomePage.c generated by valac 0.50.1.76-412f3, the Vala compiler
 * generated from HomePage.vala, do not modify */

/* Replay - An open source YouTube client for GNOME
 * Copyright 2019 - 2020 Nahuel Gomez Castro <nahuel.gomezcastro@outlook.com.ar>
 *
 * Replay is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Replay is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Replay.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <gtk/gtk.h>
#include <glib-object.h>

#define REPLAY_TYPE_PAGE (replay_page_get_type ())
#define REPLAY_PAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_PAGE, ReplayPage))
#define REPLAY_PAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_PAGE, ReplayPageClass))
#define REPLAY_IS_PAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_PAGE))
#define REPLAY_IS_PAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_PAGE))
#define REPLAY_PAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_PAGE, ReplayPageClass))

typedef struct _ReplayPage ReplayPage;
typedef struct _ReplayPageClass ReplayPageClass;
typedef struct _ReplayPagePrivate ReplayPagePrivate;

#define REPLAY_TYPE_HOME_PAGE (replay_home_page_get_type ())
#define REPLAY_HOME_PAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_HOME_PAGE, ReplayHomePage))
#define REPLAY_HOME_PAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_HOME_PAGE, ReplayHomePageClass))
#define REPLAY_IS_HOME_PAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_HOME_PAGE))
#define REPLAY_IS_HOME_PAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_HOME_PAGE))
#define REPLAY_HOME_PAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_HOME_PAGE, ReplayHomePageClass))

typedef struct _ReplayHomePage ReplayHomePage;
typedef struct _ReplayHomePageClass ReplayHomePageClass;
typedef struct _ReplayHomePagePrivate ReplayHomePagePrivate;
enum  {
	REPLAY_HOME_PAGE_0_PROPERTY,
	REPLAY_HOME_PAGE_NUM_PROPERTIES
};
static GParamSpec* replay_home_page_properties[REPLAY_HOME_PAGE_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _ReplayPage {
	GtkWidget parent_instance;
	ReplayPagePrivate * priv;
};

struct _ReplayPageClass {
	GtkWidgetClass parent_class;
};

struct _ReplayHomePage {
	ReplayPage parent_instance;
	ReplayHomePagePrivate * priv;
};

struct _ReplayHomePageClass {
	ReplayPageClass parent_class;
};

struct _ReplayHomePagePrivate {
	GtkBox* _content_box;
};

static gint ReplayHomePage_private_offset;
static gpointer replay_home_page_parent_class = NULL;

GType replay_page_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayPage, g_object_unref)
GType replay_home_page_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayHomePage, g_object_unref)
ReplayHomePage* replay_home_page_new (void);
ReplayHomePage* replay_home_page_construct (GType object_type);
ReplayPage* replay_page_new (void);
ReplayPage* replay_page_construct (GType object_type);
static void replay_home_page_finalize (GObject * obj);
static GType replay_home_page_get_type_once (void);

static inline gpointer
replay_home_page_get_instance_private (ReplayHomePage* self)
{
	return G_STRUCT_MEMBER_P (self, ReplayHomePage_private_offset);
}

ReplayHomePage*
replay_home_page_construct (GType object_type)
{
	ReplayHomePage * self = NULL;
#line 19 "../src/Pages/HomePage.vala"
	self = (ReplayHomePage*) replay_page_construct (object_type);
#line 19 "../src/Pages/HomePage.vala"
	return self;
#line 103 "HomePage.c"
}

ReplayHomePage*
replay_home_page_new (void)
{
#line 19 "../src/Pages/HomePage.vala"
	return replay_home_page_construct (REPLAY_TYPE_HOME_PAGE);
#line 111 "HomePage.c"
}

static void
replay_home_page_class_init (ReplayHomePageClass * klass,
                             gpointer klass_data)
{
#line 19 "../src/Pages/HomePage.vala"
	replay_home_page_parent_class = g_type_class_peek_parent (klass);
#line 19 "../src/Pages/HomePage.vala"
	g_type_class_adjust_private_offset (klass, &ReplayHomePage_private_offset);
#line 19 "../src/Pages/HomePage.vala"
	G_OBJECT_CLASS (klass)->finalize = replay_home_page_finalize;
#line 19 "../src/Pages/HomePage.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/io/github/nahuelwexd/Replay/HomePage.ui");
#line 19 "../src/Pages/HomePage.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "_content_box", FALSE, ReplayHomePage_private_offset + G_STRUCT_OFFSET (ReplayHomePagePrivate, _content_box));
#line 128 "HomePage.c"
}

static void
replay_home_page_instance_init (ReplayHomePage * self,
                                gpointer klass)
{
#line 19 "../src/Pages/HomePage.vala"
	self->priv = replay_home_page_get_instance_private (self);
#line 19 "../src/Pages/HomePage.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 139 "HomePage.c"
}

static void
replay_home_page_finalize (GObject * obj)
{
	ReplayHomePage * self;
#line 19 "../src/Pages/HomePage.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, REPLAY_TYPE_HOME_PAGE, ReplayHomePage);
#line 21 "../src/Pages/HomePage.vala"
	_g_object_unref0 (self->priv->_content_box);
#line 19 "../src/Pages/HomePage.vala"
	G_OBJECT_CLASS (replay_home_page_parent_class)->finalize (obj);
#line 152 "HomePage.c"
}

static GType
replay_home_page_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ReplayHomePageClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) replay_home_page_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReplayHomePage), 0, (GInstanceInitFunc) replay_home_page_instance_init, NULL };
	GType replay_home_page_type_id;
	replay_home_page_type_id = g_type_register_static (REPLAY_TYPE_PAGE, "ReplayHomePage", &g_define_type_info, 0);
	ReplayHomePage_private_offset = g_type_add_instance_private (replay_home_page_type_id, sizeof (ReplayHomePagePrivate));
	return replay_home_page_type_id;
}

GType
replay_home_page_get_type (void)
{
	static volatile gsize replay_home_page_type_id__volatile = 0;
	if (g_once_init_enter (&replay_home_page_type_id__volatile)) {
		GType replay_home_page_type_id;
		replay_home_page_type_id = replay_home_page_get_type_once ();
		g_once_init_leave (&replay_home_page_type_id__volatile, replay_home_page_type_id);
	}
	return replay_home_page_type_id__volatile;
}

