/* SearchPage.c generated by valac 0.50.1.78-abc6b, the Vala compiler
 * generated from SearchPage.vala, do not modify */

/* Replay - An open source YouTube client for GNOME
 * Copyright 2019 - 2020 Nahuel Gomez Castro <nahuel.gomezcastro@outlook.com.ar>
 *
 * Replay is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Replay is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Replay.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <gtk/gtk.h>
#include <glib-object.h>

#define REPLAY_TYPE_PAGE (replay_page_get_type ())
#define REPLAY_PAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_PAGE, ReplayPage))
#define REPLAY_PAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_PAGE, ReplayPageClass))
#define REPLAY_IS_PAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_PAGE))
#define REPLAY_IS_PAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_PAGE))
#define REPLAY_PAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_PAGE, ReplayPageClass))

typedef struct _ReplayPage ReplayPage;
typedef struct _ReplayPageClass ReplayPageClass;
typedef struct _ReplayPagePrivate ReplayPagePrivate;

#define REPLAY_TYPE_SEARCH_PAGE (replay_search_page_get_type ())
#define REPLAY_SEARCH_PAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_SEARCH_PAGE, ReplaySearchPage))
#define REPLAY_SEARCH_PAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_SEARCH_PAGE, ReplaySearchPageClass))
#define REPLAY_IS_SEARCH_PAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_SEARCH_PAGE))
#define REPLAY_IS_SEARCH_PAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_SEARCH_PAGE))
#define REPLAY_SEARCH_PAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_SEARCH_PAGE, ReplaySearchPageClass))

typedef struct _ReplaySearchPage ReplaySearchPage;
typedef struct _ReplaySearchPageClass ReplaySearchPageClass;
typedef struct _ReplaySearchPagePrivate ReplaySearchPagePrivate;
enum  {
	REPLAY_SEARCH_PAGE_0_PROPERTY,
	REPLAY_SEARCH_PAGE_NUM_PROPERTIES
};
static GParamSpec* replay_search_page_properties[REPLAY_SEARCH_PAGE_NUM_PROPERTIES];

struct _ReplayPage {
	GtkWidget parent_instance;
	ReplayPagePrivate * priv;
};

struct _ReplayPageClass {
	GtkWidgetClass parent_class;
};

struct _ReplaySearchPage {
	ReplayPage parent_instance;
	ReplaySearchPagePrivate * priv;
};

struct _ReplaySearchPageClass {
	ReplayPageClass parent_class;
};

static gpointer replay_search_page_parent_class = NULL;

GType replay_page_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayPage, g_object_unref)
GType replay_search_page_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplaySearchPage, g_object_unref)
ReplaySearchPage* replay_search_page_new (void);
ReplaySearchPage* replay_search_page_construct (GType object_type);
ReplayPage* replay_page_new (void);
ReplayPage* replay_page_construct (GType object_type);
static GType replay_search_page_get_type_once (void);

ReplaySearchPage*
replay_search_page_construct (GType object_type)
{
	ReplaySearchPage * self = NULL;
#line 19 "../src/Pages/SearchPage.vala"
	self = (ReplaySearchPage*) replay_page_construct (object_type);
#line 19 "../src/Pages/SearchPage.vala"
	return self;
#line 90 "SearchPage.c"
}

ReplaySearchPage*
replay_search_page_new (void)
{
#line 19 "../src/Pages/SearchPage.vala"
	return replay_search_page_construct (REPLAY_TYPE_SEARCH_PAGE);
#line 98 "SearchPage.c"
}

static void
replay_search_page_class_init (ReplaySearchPageClass * klass,
                               gpointer klass_data)
{
#line 19 "../src/Pages/SearchPage.vala"
	replay_search_page_parent_class = g_type_class_peek_parent (klass);
#line 19 "../src/Pages/SearchPage.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/io/github/nahuelwexd/Replay/SearchPage.ui");
#line 109 "SearchPage.c"
}

static void
replay_search_page_instance_init (ReplaySearchPage * self,
                                  gpointer klass)
{
#line 19 "../src/Pages/SearchPage.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 118 "SearchPage.c"
}

static GType
replay_search_page_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ReplaySearchPageClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) replay_search_page_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReplaySearchPage), 0, (GInstanceInitFunc) replay_search_page_instance_init, NULL };
	GType replay_search_page_type_id;
	replay_search_page_type_id = g_type_register_static (REPLAY_TYPE_PAGE, "ReplaySearchPage", &g_define_type_info, 0);
	return replay_search_page_type_id;
}

GType
replay_search_page_get_type (void)
{
	static volatile gsize replay_search_page_type_id__volatile = 0;
	if (g_once_init_enter (&replay_search_page_type_id__volatile)) {
		GType replay_search_page_type_id;
		replay_search_page_type_id = replay_search_page_get_type_once ();
		g_once_init_leave (&replay_search_page_type_id__volatile, replay_search_page_type_id);
	}
	return replay_search_page_type_id__volatile;
}

