/* Channel.c generated by valac 0.50.1.78-abc6b, the Vala compiler
 * generated from Channel.vala, do not modify */

/* Replay - An open source YouTube client for GNOME
 * Copyright 2019 - 2020 Nahuel Gomez Castro <nahuel.gomezcastro@outlook.com.ar>
 *
 * Replay is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Replay is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Replay.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gee.h>

#define REPLAY_TYPE_CHANNEL (replay_channel_get_type ())
#define REPLAY_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_CHANNEL, ReplayChannel))
#define REPLAY_CHANNEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_CHANNEL, ReplayChannelClass))
#define REPLAY_IS_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_CHANNEL))
#define REPLAY_IS_CHANNEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_CHANNEL))
#define REPLAY_CHANNEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_CHANNEL, ReplayChannelClass))

typedef struct _ReplayChannel ReplayChannel;
typedef struct _ReplayChannelClass ReplayChannelClass;
typedef struct _ReplayChannelPrivate ReplayChannelPrivate;

#define REPLAY_TYPE_VIDEO (replay_video_get_type ())
#define REPLAY_VIDEO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_VIDEO, ReplayVideo))
#define REPLAY_VIDEO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_VIDEO, ReplayVideoClass))
#define REPLAY_IS_VIDEO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_VIDEO))
#define REPLAY_IS_VIDEO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_VIDEO))
#define REPLAY_VIDEO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_VIDEO, ReplayVideoClass))

typedef struct _ReplayVideo ReplayVideo;
typedef struct _ReplayVideoClass ReplayVideoClass;
enum  {
	REPLAY_CHANNEL_0_PROPERTY,
	REPLAY_CHANNEL_ID_PROPERTY,
	REPLAY_CHANNEL_TITLE_PROPERTY,
	REPLAY_CHANNEL_VIDEOS_PROPERTY,
	REPLAY_CHANNEL_NUM_PROPERTIES
};
static GParamSpec* replay_channel_properties[REPLAY_CHANNEL_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _ReplayChannel {
	GObject parent_instance;
	ReplayChannelPrivate * priv;
};

struct _ReplayChannelClass {
	GObjectClass parent_class;
};

struct _ReplayChannelPrivate {
	gchar* _id;
	gchar* _title;
	GeeList* _videos;
};

static gint ReplayChannel_private_offset;
static gpointer replay_channel_parent_class = NULL;

GType replay_channel_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayChannel, g_object_unref)
GType replay_video_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayVideo, g_object_unref)
ReplayChannel* replay_channel_new (void);
ReplayChannel* replay_channel_construct (GType object_type);
const gchar* replay_channel_get_id (ReplayChannel* self);
void replay_channel_set_id (ReplayChannel* self,
                            const gchar* value);
const gchar* replay_channel_get_title (ReplayChannel* self);
void replay_channel_set_title (ReplayChannel* self,
                               const gchar* value);
GeeList* replay_channel_get_videos (ReplayChannel* self);
void replay_channel_set_videos (ReplayChannel* self,
                                GeeList* value);
static void replay_channel_finalize (GObject * obj);
static GType replay_channel_get_type_once (void);
static void _vala_replay_channel_get_property (GObject * object,
                                        guint property_id,
                                        GValue * value,
                                        GParamSpec * pspec);
static void _vala_replay_channel_set_property (GObject * object,
                                        guint property_id,
                                        const GValue * value,
                                        GParamSpec * pspec);

static inline gpointer
replay_channel_get_instance_private (ReplayChannel* self)
{
	return G_STRUCT_MEMBER_P (self, ReplayChannel_private_offset);
}

ReplayChannel*
replay_channel_construct (GType object_type)
{
	ReplayChannel * self = NULL;
#line 18 "../src/Database/Models/Channel.vala"
	self = (ReplayChannel*) g_object_new (object_type, NULL);
#line 18 "../src/Database/Models/Channel.vala"
	return self;
#line 117 "Channel.c"
}

ReplayChannel*
replay_channel_new (void)
{
#line 18 "../src/Database/Models/Channel.vala"
	return replay_channel_construct (REPLAY_TYPE_CHANNEL);
#line 125 "Channel.c"
}

const gchar*
replay_channel_get_id (ReplayChannel* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 20 "../src/Database/Models/Channel.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 20 "../src/Database/Models/Channel.vala"
	_tmp0_ = self->priv->_id;
#line 20 "../src/Database/Models/Channel.vala"
	result = _tmp0_;
#line 20 "../src/Database/Models/Channel.vala"
	return result;
#line 141 "Channel.c"
}

void
replay_channel_set_id (ReplayChannel* self,
                       const gchar* value)
{
#line 20 "../src/Database/Models/Channel.vala"
	g_return_if_fail (self != NULL);
#line 20 "../src/Database/Models/Channel.vala"
	if (replay_channel_get_id (self) != value) {
#line 152 "Channel.c"
		gchar* _tmp0_;
#line 20 "../src/Database/Models/Channel.vala"
		_tmp0_ = g_strdup (value);
#line 20 "../src/Database/Models/Channel.vala"
		_g_free0 (self->priv->_id);
#line 20 "../src/Database/Models/Channel.vala"
		self->priv->_id = _tmp0_;
#line 20 "../src/Database/Models/Channel.vala"
		g_object_notify_by_pspec ((GObject *) self, replay_channel_properties[REPLAY_CHANNEL_ID_PROPERTY]);
#line 162 "Channel.c"
	}
}

const gchar*
replay_channel_get_title (ReplayChannel* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 21 "../src/Database/Models/Channel.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 21 "../src/Database/Models/Channel.vala"
	_tmp0_ = self->priv->_title;
#line 21 "../src/Database/Models/Channel.vala"
	result = _tmp0_;
#line 21 "../src/Database/Models/Channel.vala"
	return result;
#line 179 "Channel.c"
}

void
replay_channel_set_title (ReplayChannel* self,
                          const gchar* value)
{
#line 21 "../src/Database/Models/Channel.vala"
	g_return_if_fail (self != NULL);
#line 21 "../src/Database/Models/Channel.vala"
	if (replay_channel_get_title (self) != value) {
#line 190 "Channel.c"
		gchar* _tmp0_;
#line 21 "../src/Database/Models/Channel.vala"
		_tmp0_ = g_strdup (value);
#line 21 "../src/Database/Models/Channel.vala"
		_g_free0 (self->priv->_title);
#line 21 "../src/Database/Models/Channel.vala"
		self->priv->_title = _tmp0_;
#line 21 "../src/Database/Models/Channel.vala"
		g_object_notify_by_pspec ((GObject *) self, replay_channel_properties[REPLAY_CHANNEL_TITLE_PROPERTY]);
#line 200 "Channel.c"
	}
}

GeeList*
replay_channel_get_videos (ReplayChannel* self)
{
	GeeList* result;
	GeeList* _tmp0_;
#line 22 "../src/Database/Models/Channel.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 22 "../src/Database/Models/Channel.vala"
	_tmp0_ = self->priv->_videos;
#line 22 "../src/Database/Models/Channel.vala"
	result = _tmp0_;
#line 22 "../src/Database/Models/Channel.vala"
	return result;
#line 217 "Channel.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 22 "../src/Database/Models/Channel.vala"
	return self ? g_object_ref (self) : NULL;
#line 225 "Channel.c"
}

void
replay_channel_set_videos (ReplayChannel* self,
                           GeeList* value)
{
#line 22 "../src/Database/Models/Channel.vala"
	g_return_if_fail (self != NULL);
#line 22 "../src/Database/Models/Channel.vala"
	if (replay_channel_get_videos (self) != value) {
#line 236 "Channel.c"
		GeeList* _tmp0_;
#line 22 "../src/Database/Models/Channel.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 22 "../src/Database/Models/Channel.vala"
		_g_object_unref0 (self->priv->_videos);
#line 22 "../src/Database/Models/Channel.vala"
		self->priv->_videos = _tmp0_;
#line 22 "../src/Database/Models/Channel.vala"
		g_object_notify_by_pspec ((GObject *) self, replay_channel_properties[REPLAY_CHANNEL_VIDEOS_PROPERTY]);
#line 246 "Channel.c"
	}
}

static void
replay_channel_class_init (ReplayChannelClass * klass,
                           gpointer klass_data)
{
#line 18 "../src/Database/Models/Channel.vala"
	replay_channel_parent_class = g_type_class_peek_parent (klass);
#line 18 "../src/Database/Models/Channel.vala"
	g_type_class_adjust_private_offset (klass, &ReplayChannel_private_offset);
#line 18 "../src/Database/Models/Channel.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_replay_channel_get_property;
#line 18 "../src/Database/Models/Channel.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_replay_channel_set_property;
#line 18 "../src/Database/Models/Channel.vala"
	G_OBJECT_CLASS (klass)->finalize = replay_channel_finalize;
#line 18 "../src/Database/Models/Channel.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_CHANNEL_ID_PROPERTY, replay_channel_properties[REPLAY_CHANNEL_ID_PROPERTY] = g_param_spec_string ("id", "id", "id", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 18 "../src/Database/Models/Channel.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_CHANNEL_TITLE_PROPERTY, replay_channel_properties[REPLAY_CHANNEL_TITLE_PROPERTY] = g_param_spec_string ("title", "title", "title", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 18 "../src/Database/Models/Channel.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_CHANNEL_VIDEOS_PROPERTY, replay_channel_properties[REPLAY_CHANNEL_VIDEOS_PROPERTY] = g_param_spec_object ("videos", "videos", "videos", GEE_TYPE_LIST, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 270 "Channel.c"
}

static void
replay_channel_instance_init (ReplayChannel * self,
                              gpointer klass)
{
#line 18 "../src/Database/Models/Channel.vala"
	self->priv = replay_channel_get_instance_private (self);
#line 279 "Channel.c"
}

static void
replay_channel_finalize (GObject * obj)
{
	ReplayChannel * self;
#line 18 "../src/Database/Models/Channel.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, REPLAY_TYPE_CHANNEL, ReplayChannel);
#line 20 "../src/Database/Models/Channel.vala"
	_g_free0 (self->priv->_id);
#line 21 "../src/Database/Models/Channel.vala"
	_g_free0 (self->priv->_title);
#line 22 "../src/Database/Models/Channel.vala"
	_g_object_unref0 (self->priv->_videos);
#line 18 "../src/Database/Models/Channel.vala"
	G_OBJECT_CLASS (replay_channel_parent_class)->finalize (obj);
#line 296 "Channel.c"
}

static GType
replay_channel_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ReplayChannelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) replay_channel_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReplayChannel), 0, (GInstanceInitFunc) replay_channel_instance_init, NULL };
	GType replay_channel_type_id;
	replay_channel_type_id = g_type_register_static (G_TYPE_OBJECT, "ReplayChannel", &g_define_type_info, 0);
	ReplayChannel_private_offset = g_type_add_instance_private (replay_channel_type_id, sizeof (ReplayChannelPrivate));
	return replay_channel_type_id;
}

GType
replay_channel_get_type (void)
{
	static volatile gsize replay_channel_type_id__volatile = 0;
	if (g_once_init_enter (&replay_channel_type_id__volatile)) {
		GType replay_channel_type_id;
		replay_channel_type_id = replay_channel_get_type_once ();
		g_once_init_leave (&replay_channel_type_id__volatile, replay_channel_type_id);
	}
	return replay_channel_type_id__volatile;
}

static void
_vala_replay_channel_get_property (GObject * object,
                                   guint property_id,
                                   GValue * value,
                                   GParamSpec * pspec)
{
	ReplayChannel * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, REPLAY_TYPE_CHANNEL, ReplayChannel);
#line 18 "../src/Database/Models/Channel.vala"
	switch (property_id) {
#line 18 "../src/Database/Models/Channel.vala"
		case REPLAY_CHANNEL_ID_PROPERTY:
#line 18 "../src/Database/Models/Channel.vala"
		g_value_set_string (value, replay_channel_get_id (self));
#line 18 "../src/Database/Models/Channel.vala"
		break;
#line 18 "../src/Database/Models/Channel.vala"
		case REPLAY_CHANNEL_TITLE_PROPERTY:
#line 18 "../src/Database/Models/Channel.vala"
		g_value_set_string (value, replay_channel_get_title (self));
#line 18 "../src/Database/Models/Channel.vala"
		break;
#line 18 "../src/Database/Models/Channel.vala"
		case REPLAY_CHANNEL_VIDEOS_PROPERTY:
#line 18 "../src/Database/Models/Channel.vala"
		g_value_set_object (value, replay_channel_get_videos (self));
#line 18 "../src/Database/Models/Channel.vala"
		break;
#line 349 "Channel.c"
		default:
#line 18 "../src/Database/Models/Channel.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 18 "../src/Database/Models/Channel.vala"
		break;
#line 355 "Channel.c"
	}
}

static void
_vala_replay_channel_set_property (GObject * object,
                                   guint property_id,
                                   const GValue * value,
                                   GParamSpec * pspec)
{
	ReplayChannel * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, REPLAY_TYPE_CHANNEL, ReplayChannel);
#line 18 "../src/Database/Models/Channel.vala"
	switch (property_id) {
#line 18 "../src/Database/Models/Channel.vala"
		case REPLAY_CHANNEL_ID_PROPERTY:
#line 18 "../src/Database/Models/Channel.vala"
		replay_channel_set_id (self, g_value_get_string (value));
#line 18 "../src/Database/Models/Channel.vala"
		break;
#line 18 "../src/Database/Models/Channel.vala"
		case REPLAY_CHANNEL_TITLE_PROPERTY:
#line 18 "../src/Database/Models/Channel.vala"
		replay_channel_set_title (self, g_value_get_string (value));
#line 18 "../src/Database/Models/Channel.vala"
		break;
#line 18 "../src/Database/Models/Channel.vala"
		case REPLAY_CHANNEL_VIDEOS_PROPERTY:
#line 18 "../src/Database/Models/Channel.vala"
		replay_channel_set_videos (self, g_value_get_object (value));
#line 18 "../src/Database/Models/Channel.vala"
		break;
#line 387 "Channel.c"
		default:
#line 18 "../src/Database/Models/Channel.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 18 "../src/Database/Models/Channel.vala"
		break;
#line 393 "Channel.c"
	}
}

