/* Playlist.c generated by valac 0.50.1.78-abc6b, the Vala compiler
 * generated from Playlist.vala, do not modify */

/* Replay - An open source YouTube client for GNOME
 * Copyright 2019 - 2020 Nahuel Gomez Castro <nahuel.gomezcastro@outlook.com.ar>
 *
 * Replay is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Replay is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Replay.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gee.h>

#define REPLAY_TYPE_PLAYLIST (replay_playlist_get_type ())
#define REPLAY_PLAYLIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_PLAYLIST, ReplayPlaylist))
#define REPLAY_PLAYLIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_PLAYLIST, ReplayPlaylistClass))
#define REPLAY_IS_PLAYLIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_PLAYLIST))
#define REPLAY_IS_PLAYLIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_PLAYLIST))
#define REPLAY_PLAYLIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_PLAYLIST, ReplayPlaylistClass))

typedef struct _ReplayPlaylist ReplayPlaylist;
typedef struct _ReplayPlaylistClass ReplayPlaylistClass;
typedef struct _ReplayPlaylistPrivate ReplayPlaylistPrivate;

#define REPLAY_TYPE_VIDEO (replay_video_get_type ())
#define REPLAY_VIDEO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_VIDEO, ReplayVideo))
#define REPLAY_VIDEO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_VIDEO, ReplayVideoClass))
#define REPLAY_IS_VIDEO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_VIDEO))
#define REPLAY_IS_VIDEO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_VIDEO))
#define REPLAY_VIDEO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_VIDEO, ReplayVideoClass))

typedef struct _ReplayVideo ReplayVideo;
typedef struct _ReplayVideoClass ReplayVideoClass;
enum  {
	REPLAY_PLAYLIST_0_PROPERTY,
	REPLAY_PLAYLIST_ID_PROPERTY,
	REPLAY_PLAYLIST_TITLE_PROPERTY,
	REPLAY_PLAYLIST_VIDEOS_PROPERTY,
	REPLAY_PLAYLIST_NUM_PROPERTIES
};
static GParamSpec* replay_playlist_properties[REPLAY_PLAYLIST_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _ReplayPlaylist {
	GObject parent_instance;
	ReplayPlaylistPrivate * priv;
};

struct _ReplayPlaylistClass {
	GObjectClass parent_class;
};

struct _ReplayPlaylistPrivate {
	gchar* _id;
	gchar* _title;
	GeeList* _videos;
};

static gint ReplayPlaylist_private_offset;
static gpointer replay_playlist_parent_class = NULL;

GType replay_playlist_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayPlaylist, g_object_unref)
GType replay_video_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayVideo, g_object_unref)
ReplayPlaylist* replay_playlist_new (void);
ReplayPlaylist* replay_playlist_construct (GType object_type);
const gchar* replay_playlist_get_id (ReplayPlaylist* self);
void replay_playlist_set_id (ReplayPlaylist* self,
                             const gchar* value);
const gchar* replay_playlist_get_title (ReplayPlaylist* self);
void replay_playlist_set_title (ReplayPlaylist* self,
                                const gchar* value);
GeeList* replay_playlist_get_videos (ReplayPlaylist* self);
void replay_playlist_set_videos (ReplayPlaylist* self,
                                 GeeList* value);
static void replay_playlist_finalize (GObject * obj);
static GType replay_playlist_get_type_once (void);
static void _vala_replay_playlist_get_property (GObject * object,
                                         guint property_id,
                                         GValue * value,
                                         GParamSpec * pspec);
static void _vala_replay_playlist_set_property (GObject * object,
                                         guint property_id,
                                         const GValue * value,
                                         GParamSpec * pspec);

static inline gpointer
replay_playlist_get_instance_private (ReplayPlaylist* self)
{
	return G_STRUCT_MEMBER_P (self, ReplayPlaylist_private_offset);
}

ReplayPlaylist*
replay_playlist_construct (GType object_type)
{
	ReplayPlaylist * self = NULL;
#line 18 "../src/Database/Models/Playlist.vala"
	self = (ReplayPlaylist*) g_object_new (object_type, NULL);
#line 18 "../src/Database/Models/Playlist.vala"
	return self;
#line 117 "Playlist.c"
}

ReplayPlaylist*
replay_playlist_new (void)
{
#line 18 "../src/Database/Models/Playlist.vala"
	return replay_playlist_construct (REPLAY_TYPE_PLAYLIST);
#line 125 "Playlist.c"
}

const gchar*
replay_playlist_get_id (ReplayPlaylist* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 20 "../src/Database/Models/Playlist.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 20 "../src/Database/Models/Playlist.vala"
	_tmp0_ = self->priv->_id;
#line 20 "../src/Database/Models/Playlist.vala"
	result = _tmp0_;
#line 20 "../src/Database/Models/Playlist.vala"
	return result;
#line 141 "Playlist.c"
}

void
replay_playlist_set_id (ReplayPlaylist* self,
                        const gchar* value)
{
#line 20 "../src/Database/Models/Playlist.vala"
	g_return_if_fail (self != NULL);
#line 20 "../src/Database/Models/Playlist.vala"
	if (replay_playlist_get_id (self) != value) {
#line 152 "Playlist.c"
		gchar* _tmp0_;
#line 20 "../src/Database/Models/Playlist.vala"
		_tmp0_ = g_strdup (value);
#line 20 "../src/Database/Models/Playlist.vala"
		_g_free0 (self->priv->_id);
#line 20 "../src/Database/Models/Playlist.vala"
		self->priv->_id = _tmp0_;
#line 20 "../src/Database/Models/Playlist.vala"
		g_object_notify_by_pspec ((GObject *) self, replay_playlist_properties[REPLAY_PLAYLIST_ID_PROPERTY]);
#line 162 "Playlist.c"
	}
}

const gchar*
replay_playlist_get_title (ReplayPlaylist* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 21 "../src/Database/Models/Playlist.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 21 "../src/Database/Models/Playlist.vala"
	_tmp0_ = self->priv->_title;
#line 21 "../src/Database/Models/Playlist.vala"
	result = _tmp0_;
#line 21 "../src/Database/Models/Playlist.vala"
	return result;
#line 179 "Playlist.c"
}

void
replay_playlist_set_title (ReplayPlaylist* self,
                           const gchar* value)
{
#line 21 "../src/Database/Models/Playlist.vala"
	g_return_if_fail (self != NULL);
#line 21 "../src/Database/Models/Playlist.vala"
	if (replay_playlist_get_title (self) != value) {
#line 190 "Playlist.c"
		gchar* _tmp0_;
#line 21 "../src/Database/Models/Playlist.vala"
		_tmp0_ = g_strdup (value);
#line 21 "../src/Database/Models/Playlist.vala"
		_g_free0 (self->priv->_title);
#line 21 "../src/Database/Models/Playlist.vala"
		self->priv->_title = _tmp0_;
#line 21 "../src/Database/Models/Playlist.vala"
		g_object_notify_by_pspec ((GObject *) self, replay_playlist_properties[REPLAY_PLAYLIST_TITLE_PROPERTY]);
#line 200 "Playlist.c"
	}
}

GeeList*
replay_playlist_get_videos (ReplayPlaylist* self)
{
	GeeList* result;
	GeeList* _tmp0_;
#line 22 "../src/Database/Models/Playlist.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 22 "../src/Database/Models/Playlist.vala"
	_tmp0_ = self->priv->_videos;
#line 22 "../src/Database/Models/Playlist.vala"
	result = _tmp0_;
#line 22 "../src/Database/Models/Playlist.vala"
	return result;
#line 217 "Playlist.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 22 "../src/Database/Models/Playlist.vala"
	return self ? g_object_ref (self) : NULL;
#line 225 "Playlist.c"
}

void
replay_playlist_set_videos (ReplayPlaylist* self,
                            GeeList* value)
{
#line 22 "../src/Database/Models/Playlist.vala"
	g_return_if_fail (self != NULL);
#line 22 "../src/Database/Models/Playlist.vala"
	if (replay_playlist_get_videos (self) != value) {
#line 236 "Playlist.c"
		GeeList* _tmp0_;
#line 22 "../src/Database/Models/Playlist.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 22 "../src/Database/Models/Playlist.vala"
		_g_object_unref0 (self->priv->_videos);
#line 22 "../src/Database/Models/Playlist.vala"
		self->priv->_videos = _tmp0_;
#line 22 "../src/Database/Models/Playlist.vala"
		g_object_notify_by_pspec ((GObject *) self, replay_playlist_properties[REPLAY_PLAYLIST_VIDEOS_PROPERTY]);
#line 246 "Playlist.c"
	}
}

static void
replay_playlist_class_init (ReplayPlaylistClass * klass,
                            gpointer klass_data)
{
#line 18 "../src/Database/Models/Playlist.vala"
	replay_playlist_parent_class = g_type_class_peek_parent (klass);
#line 18 "../src/Database/Models/Playlist.vala"
	g_type_class_adjust_private_offset (klass, &ReplayPlaylist_private_offset);
#line 18 "../src/Database/Models/Playlist.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_replay_playlist_get_property;
#line 18 "../src/Database/Models/Playlist.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_replay_playlist_set_property;
#line 18 "../src/Database/Models/Playlist.vala"
	G_OBJECT_CLASS (klass)->finalize = replay_playlist_finalize;
#line 18 "../src/Database/Models/Playlist.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_PLAYLIST_ID_PROPERTY, replay_playlist_properties[REPLAY_PLAYLIST_ID_PROPERTY] = g_param_spec_string ("id", "id", "id", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 18 "../src/Database/Models/Playlist.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_PLAYLIST_TITLE_PROPERTY, replay_playlist_properties[REPLAY_PLAYLIST_TITLE_PROPERTY] = g_param_spec_string ("title", "title", "title", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 18 "../src/Database/Models/Playlist.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_PLAYLIST_VIDEOS_PROPERTY, replay_playlist_properties[REPLAY_PLAYLIST_VIDEOS_PROPERTY] = g_param_spec_object ("videos", "videos", "videos", GEE_TYPE_LIST, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 270 "Playlist.c"
}

static void
replay_playlist_instance_init (ReplayPlaylist * self,
                               gpointer klass)
{
#line 18 "../src/Database/Models/Playlist.vala"
	self->priv = replay_playlist_get_instance_private (self);
#line 279 "Playlist.c"
}

static void
replay_playlist_finalize (GObject * obj)
{
	ReplayPlaylist * self;
#line 18 "../src/Database/Models/Playlist.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, REPLAY_TYPE_PLAYLIST, ReplayPlaylist);
#line 20 "../src/Database/Models/Playlist.vala"
	_g_free0 (self->priv->_id);
#line 21 "../src/Database/Models/Playlist.vala"
	_g_free0 (self->priv->_title);
#line 22 "../src/Database/Models/Playlist.vala"
	_g_object_unref0 (self->priv->_videos);
#line 18 "../src/Database/Models/Playlist.vala"
	G_OBJECT_CLASS (replay_playlist_parent_class)->finalize (obj);
#line 296 "Playlist.c"
}

static GType
replay_playlist_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ReplayPlaylistClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) replay_playlist_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReplayPlaylist), 0, (GInstanceInitFunc) replay_playlist_instance_init, NULL };
	GType replay_playlist_type_id;
	replay_playlist_type_id = g_type_register_static (G_TYPE_OBJECT, "ReplayPlaylist", &g_define_type_info, 0);
	ReplayPlaylist_private_offset = g_type_add_instance_private (replay_playlist_type_id, sizeof (ReplayPlaylistPrivate));
	return replay_playlist_type_id;
}

GType
replay_playlist_get_type (void)
{
	static volatile gsize replay_playlist_type_id__volatile = 0;
	if (g_once_init_enter (&replay_playlist_type_id__volatile)) {
		GType replay_playlist_type_id;
		replay_playlist_type_id = replay_playlist_get_type_once ();
		g_once_init_leave (&replay_playlist_type_id__volatile, replay_playlist_type_id);
	}
	return replay_playlist_type_id__volatile;
}

static void
_vala_replay_playlist_get_property (GObject * object,
                                    guint property_id,
                                    GValue * value,
                                    GParamSpec * pspec)
{
	ReplayPlaylist * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, REPLAY_TYPE_PLAYLIST, ReplayPlaylist);
#line 18 "../src/Database/Models/Playlist.vala"
	switch (property_id) {
#line 18 "../src/Database/Models/Playlist.vala"
		case REPLAY_PLAYLIST_ID_PROPERTY:
#line 18 "../src/Database/Models/Playlist.vala"
		g_value_set_string (value, replay_playlist_get_id (self));
#line 18 "../src/Database/Models/Playlist.vala"
		break;
#line 18 "../src/Database/Models/Playlist.vala"
		case REPLAY_PLAYLIST_TITLE_PROPERTY:
#line 18 "../src/Database/Models/Playlist.vala"
		g_value_set_string (value, replay_playlist_get_title (self));
#line 18 "../src/Database/Models/Playlist.vala"
		break;
#line 18 "../src/Database/Models/Playlist.vala"
		case REPLAY_PLAYLIST_VIDEOS_PROPERTY:
#line 18 "../src/Database/Models/Playlist.vala"
		g_value_set_object (value, replay_playlist_get_videos (self));
#line 18 "../src/Database/Models/Playlist.vala"
		break;
#line 349 "Playlist.c"
		default:
#line 18 "../src/Database/Models/Playlist.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 18 "../src/Database/Models/Playlist.vala"
		break;
#line 355 "Playlist.c"
	}
}

static void
_vala_replay_playlist_set_property (GObject * object,
                                    guint property_id,
                                    const GValue * value,
                                    GParamSpec * pspec)
{
	ReplayPlaylist * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, REPLAY_TYPE_PLAYLIST, ReplayPlaylist);
#line 18 "../src/Database/Models/Playlist.vala"
	switch (property_id) {
#line 18 "../src/Database/Models/Playlist.vala"
		case REPLAY_PLAYLIST_ID_PROPERTY:
#line 18 "../src/Database/Models/Playlist.vala"
		replay_playlist_set_id (self, g_value_get_string (value));
#line 18 "../src/Database/Models/Playlist.vala"
		break;
#line 18 "../src/Database/Models/Playlist.vala"
		case REPLAY_PLAYLIST_TITLE_PROPERTY:
#line 18 "../src/Database/Models/Playlist.vala"
		replay_playlist_set_title (self, g_value_get_string (value));
#line 18 "../src/Database/Models/Playlist.vala"
		break;
#line 18 "../src/Database/Models/Playlist.vala"
		case REPLAY_PLAYLIST_VIDEOS_PROPERTY:
#line 18 "../src/Database/Models/Playlist.vala"
		replay_playlist_set_videos (self, g_value_get_object (value));
#line 18 "../src/Database/Models/Playlist.vala"
		break;
#line 387 "Playlist.c"
		default:
#line 18 "../src/Database/Models/Playlist.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 18 "../src/Database/Models/Playlist.vala"
		break;
#line 393 "Playlist.c"
	}
}

