/* Video.c generated by valac 0.50.1.78-abc6b, the Vala compiler
 * generated from Video.vala, do not modify */

/* Replay - An open source YouTube client for GNOME
 * Copyright 2019 - 2020 Nahuel Gomez Castro <nahuel.gomezcastro@outlook.com.ar>
 *
 * Replay is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Replay is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Replay.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>

#define REPLAY_TYPE_VIDEO (replay_video_get_type ())
#define REPLAY_VIDEO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_VIDEO, ReplayVideo))
#define REPLAY_VIDEO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_VIDEO, ReplayVideoClass))
#define REPLAY_IS_VIDEO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_VIDEO))
#define REPLAY_IS_VIDEO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_VIDEO))
#define REPLAY_VIDEO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_VIDEO, ReplayVideoClass))

typedef struct _ReplayVideo ReplayVideo;
typedef struct _ReplayVideoClass ReplayVideoClass;
typedef struct _ReplayVideoPrivate ReplayVideoPrivate;

#define REPLAY_TYPE_CHANNEL (replay_channel_get_type ())
#define REPLAY_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_CHANNEL, ReplayChannel))
#define REPLAY_CHANNEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_CHANNEL, ReplayChannelClass))
#define REPLAY_IS_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_CHANNEL))
#define REPLAY_IS_CHANNEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_CHANNEL))
#define REPLAY_CHANNEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_CHANNEL, ReplayChannelClass))

typedef struct _ReplayChannel ReplayChannel;
typedef struct _ReplayChannelClass ReplayChannelClass;
enum  {
	REPLAY_VIDEO_0_PROPERTY,
	REPLAY_VIDEO_ID_PROPERTY,
	REPLAY_VIDEO_TITLE_PROPERTY,
	REPLAY_VIDEO_DESCRIPTION_PROPERTY,
	REPLAY_VIDEO_CHANNEL_PROPERTY,
	REPLAY_VIDEO_NUM_PROPERTIES
};
static GParamSpec* replay_video_properties[REPLAY_VIDEO_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _ReplayVideo {
	GObject parent_instance;
	ReplayVideoPrivate * priv;
};

struct _ReplayVideoClass {
	GObjectClass parent_class;
};

struct _ReplayVideoPrivate {
	gchar* _id;
	gchar* _title;
	gchar* _description;
	ReplayChannel* _channel;
};

static gint ReplayVideo_private_offset;
static gpointer replay_video_parent_class = NULL;

GType replay_video_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayVideo, g_object_unref)
GType replay_channel_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayChannel, g_object_unref)
ReplayVideo* replay_video_new (void);
ReplayVideo* replay_video_construct (GType object_type);
const gchar* replay_video_get_id (ReplayVideo* self);
void replay_video_set_id (ReplayVideo* self,
                          const gchar* value);
const gchar* replay_video_get_title (ReplayVideo* self);
void replay_video_set_title (ReplayVideo* self,
                             const gchar* value);
const gchar* replay_video_get_description (ReplayVideo* self);
void replay_video_set_description (ReplayVideo* self,
                                   const gchar* value);
ReplayChannel* replay_video_get_channel (ReplayVideo* self);
void replay_video_set_channel (ReplayVideo* self,
                               ReplayChannel* value);
static void replay_video_finalize (GObject * obj);
static GType replay_video_get_type_once (void);
static void _vala_replay_video_get_property (GObject * object,
                                      guint property_id,
                                      GValue * value,
                                      GParamSpec * pspec);
static void _vala_replay_video_set_property (GObject * object,
                                      guint property_id,
                                      const GValue * value,
                                      GParamSpec * pspec);

static inline gpointer
replay_video_get_instance_private (ReplayVideo* self)
{
	return G_STRUCT_MEMBER_P (self, ReplayVideo_private_offset);
}

ReplayVideo*
replay_video_construct (GType object_type)
{
	ReplayVideo * self = NULL;
#line 18 "../src/Database/Models/Video.vala"
	self = (ReplayVideo*) g_object_new (object_type, NULL);
#line 18 "../src/Database/Models/Video.vala"
	return self;
#line 121 "Video.c"
}

ReplayVideo*
replay_video_new (void)
{
#line 18 "../src/Database/Models/Video.vala"
	return replay_video_construct (REPLAY_TYPE_VIDEO);
#line 129 "Video.c"
}

const gchar*
replay_video_get_id (ReplayVideo* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 20 "../src/Database/Models/Video.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 20 "../src/Database/Models/Video.vala"
	_tmp0_ = self->priv->_id;
#line 20 "../src/Database/Models/Video.vala"
	result = _tmp0_;
#line 20 "../src/Database/Models/Video.vala"
	return result;
#line 145 "Video.c"
}

void
replay_video_set_id (ReplayVideo* self,
                     const gchar* value)
{
#line 20 "../src/Database/Models/Video.vala"
	g_return_if_fail (self != NULL);
#line 20 "../src/Database/Models/Video.vala"
	if (replay_video_get_id (self) != value) {
#line 156 "Video.c"
		gchar* _tmp0_;
#line 20 "../src/Database/Models/Video.vala"
		_tmp0_ = g_strdup (value);
#line 20 "../src/Database/Models/Video.vala"
		_g_free0 (self->priv->_id);
#line 20 "../src/Database/Models/Video.vala"
		self->priv->_id = _tmp0_;
#line 20 "../src/Database/Models/Video.vala"
		g_object_notify_by_pspec ((GObject *) self, replay_video_properties[REPLAY_VIDEO_ID_PROPERTY]);
#line 166 "Video.c"
	}
}

const gchar*
replay_video_get_title (ReplayVideo* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 21 "../src/Database/Models/Video.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 21 "../src/Database/Models/Video.vala"
	_tmp0_ = self->priv->_title;
#line 21 "../src/Database/Models/Video.vala"
	result = _tmp0_;
#line 21 "../src/Database/Models/Video.vala"
	return result;
#line 183 "Video.c"
}

void
replay_video_set_title (ReplayVideo* self,
                        const gchar* value)
{
#line 21 "../src/Database/Models/Video.vala"
	g_return_if_fail (self != NULL);
#line 21 "../src/Database/Models/Video.vala"
	if (replay_video_get_title (self) != value) {
#line 194 "Video.c"
		gchar* _tmp0_;
#line 21 "../src/Database/Models/Video.vala"
		_tmp0_ = g_strdup (value);
#line 21 "../src/Database/Models/Video.vala"
		_g_free0 (self->priv->_title);
#line 21 "../src/Database/Models/Video.vala"
		self->priv->_title = _tmp0_;
#line 21 "../src/Database/Models/Video.vala"
		g_object_notify_by_pspec ((GObject *) self, replay_video_properties[REPLAY_VIDEO_TITLE_PROPERTY]);
#line 204 "Video.c"
	}
}

const gchar*
replay_video_get_description (ReplayVideo* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 22 "../src/Database/Models/Video.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 22 "../src/Database/Models/Video.vala"
	_tmp0_ = self->priv->_description;
#line 22 "../src/Database/Models/Video.vala"
	result = _tmp0_;
#line 22 "../src/Database/Models/Video.vala"
	return result;
#line 221 "Video.c"
}

void
replay_video_set_description (ReplayVideo* self,
                              const gchar* value)
{
#line 22 "../src/Database/Models/Video.vala"
	g_return_if_fail (self != NULL);
#line 22 "../src/Database/Models/Video.vala"
	if (replay_video_get_description (self) != value) {
#line 232 "Video.c"
		gchar* _tmp0_;
#line 22 "../src/Database/Models/Video.vala"
		_tmp0_ = g_strdup (value);
#line 22 "../src/Database/Models/Video.vala"
		_g_free0 (self->priv->_description);
#line 22 "../src/Database/Models/Video.vala"
		self->priv->_description = _tmp0_;
#line 22 "../src/Database/Models/Video.vala"
		g_object_notify_by_pspec ((GObject *) self, replay_video_properties[REPLAY_VIDEO_DESCRIPTION_PROPERTY]);
#line 242 "Video.c"
	}
}

ReplayChannel*
replay_video_get_channel (ReplayVideo* self)
{
	ReplayChannel* result;
	ReplayChannel* _tmp0_;
#line 23 "../src/Database/Models/Video.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 23 "../src/Database/Models/Video.vala"
	_tmp0_ = self->priv->_channel;
#line 23 "../src/Database/Models/Video.vala"
	result = _tmp0_;
#line 23 "../src/Database/Models/Video.vala"
	return result;
#line 259 "Video.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 23 "../src/Database/Models/Video.vala"
	return self ? g_object_ref (self) : NULL;
#line 267 "Video.c"
}

void
replay_video_set_channel (ReplayVideo* self,
                          ReplayChannel* value)
{
#line 23 "../src/Database/Models/Video.vala"
	g_return_if_fail (self != NULL);
#line 23 "../src/Database/Models/Video.vala"
	if (replay_video_get_channel (self) != value) {
#line 278 "Video.c"
		ReplayChannel* _tmp0_;
#line 23 "../src/Database/Models/Video.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 23 "../src/Database/Models/Video.vala"
		_g_object_unref0 (self->priv->_channel);
#line 23 "../src/Database/Models/Video.vala"
		self->priv->_channel = _tmp0_;
#line 23 "../src/Database/Models/Video.vala"
		g_object_notify_by_pspec ((GObject *) self, replay_video_properties[REPLAY_VIDEO_CHANNEL_PROPERTY]);
#line 288 "Video.c"
	}
}

static void
replay_video_class_init (ReplayVideoClass * klass,
                         gpointer klass_data)
{
#line 18 "../src/Database/Models/Video.vala"
	replay_video_parent_class = g_type_class_peek_parent (klass);
#line 18 "../src/Database/Models/Video.vala"
	g_type_class_adjust_private_offset (klass, &ReplayVideo_private_offset);
#line 18 "../src/Database/Models/Video.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_replay_video_get_property;
#line 18 "../src/Database/Models/Video.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_replay_video_set_property;
#line 18 "../src/Database/Models/Video.vala"
	G_OBJECT_CLASS (klass)->finalize = replay_video_finalize;
#line 18 "../src/Database/Models/Video.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_VIDEO_ID_PROPERTY, replay_video_properties[REPLAY_VIDEO_ID_PROPERTY] = g_param_spec_string ("id", "id", "id", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 18 "../src/Database/Models/Video.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_VIDEO_TITLE_PROPERTY, replay_video_properties[REPLAY_VIDEO_TITLE_PROPERTY] = g_param_spec_string ("title", "title", "title", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 18 "../src/Database/Models/Video.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_VIDEO_DESCRIPTION_PROPERTY, replay_video_properties[REPLAY_VIDEO_DESCRIPTION_PROPERTY] = g_param_spec_string ("description", "description", "description", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 18 "../src/Database/Models/Video.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_VIDEO_CHANNEL_PROPERTY, replay_video_properties[REPLAY_VIDEO_CHANNEL_PROPERTY] = g_param_spec_object ("channel", "channel", "channel", REPLAY_TYPE_CHANNEL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 314 "Video.c"
}

static void
replay_video_instance_init (ReplayVideo * self,
                            gpointer klass)
{
#line 18 "../src/Database/Models/Video.vala"
	self->priv = replay_video_get_instance_private (self);
#line 323 "Video.c"
}

static void
replay_video_finalize (GObject * obj)
{
	ReplayVideo * self;
#line 18 "../src/Database/Models/Video.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, REPLAY_TYPE_VIDEO, ReplayVideo);
#line 20 "../src/Database/Models/Video.vala"
	_g_free0 (self->priv->_id);
#line 21 "../src/Database/Models/Video.vala"
	_g_free0 (self->priv->_title);
#line 22 "../src/Database/Models/Video.vala"
	_g_free0 (self->priv->_description);
#line 23 "../src/Database/Models/Video.vala"
	_g_object_unref0 (self->priv->_channel);
#line 18 "../src/Database/Models/Video.vala"
	G_OBJECT_CLASS (replay_video_parent_class)->finalize (obj);
#line 342 "Video.c"
}

static GType
replay_video_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ReplayVideoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) replay_video_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReplayVideo), 0, (GInstanceInitFunc) replay_video_instance_init, NULL };
	GType replay_video_type_id;
	replay_video_type_id = g_type_register_static (G_TYPE_OBJECT, "ReplayVideo", &g_define_type_info, 0);
	ReplayVideo_private_offset = g_type_add_instance_private (replay_video_type_id, sizeof (ReplayVideoPrivate));
	return replay_video_type_id;
}

GType
replay_video_get_type (void)
{
	static volatile gsize replay_video_type_id__volatile = 0;
	if (g_once_init_enter (&replay_video_type_id__volatile)) {
		GType replay_video_type_id;
		replay_video_type_id = replay_video_get_type_once ();
		g_once_init_leave (&replay_video_type_id__volatile, replay_video_type_id);
	}
	return replay_video_type_id__volatile;
}

static void
_vala_replay_video_get_property (GObject * object,
                                 guint property_id,
                                 GValue * value,
                                 GParamSpec * pspec)
{
	ReplayVideo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, REPLAY_TYPE_VIDEO, ReplayVideo);
#line 18 "../src/Database/Models/Video.vala"
	switch (property_id) {
#line 18 "../src/Database/Models/Video.vala"
		case REPLAY_VIDEO_ID_PROPERTY:
#line 18 "../src/Database/Models/Video.vala"
		g_value_set_string (value, replay_video_get_id (self));
#line 18 "../src/Database/Models/Video.vala"
		break;
#line 18 "../src/Database/Models/Video.vala"
		case REPLAY_VIDEO_TITLE_PROPERTY:
#line 18 "../src/Database/Models/Video.vala"
		g_value_set_string (value, replay_video_get_title (self));
#line 18 "../src/Database/Models/Video.vala"
		break;
#line 18 "../src/Database/Models/Video.vala"
		case REPLAY_VIDEO_DESCRIPTION_PROPERTY:
#line 18 "../src/Database/Models/Video.vala"
		g_value_set_string (value, replay_video_get_description (self));
#line 18 "../src/Database/Models/Video.vala"
		break;
#line 18 "../src/Database/Models/Video.vala"
		case REPLAY_VIDEO_CHANNEL_PROPERTY:
#line 18 "../src/Database/Models/Video.vala"
		g_value_set_object (value, replay_video_get_channel (self));
#line 18 "../src/Database/Models/Video.vala"
		break;
#line 401 "Video.c"
		default:
#line 18 "../src/Database/Models/Video.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 18 "../src/Database/Models/Video.vala"
		break;
#line 407 "Video.c"
	}
}

static void
_vala_replay_video_set_property (GObject * object,
                                 guint property_id,
                                 const GValue * value,
                                 GParamSpec * pspec)
{
	ReplayVideo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, REPLAY_TYPE_VIDEO, ReplayVideo);
#line 18 "../src/Database/Models/Video.vala"
	switch (property_id) {
#line 18 "../src/Database/Models/Video.vala"
		case REPLAY_VIDEO_ID_PROPERTY:
#line 18 "../src/Database/Models/Video.vala"
		replay_video_set_id (self, g_value_get_string (value));
#line 18 "../src/Database/Models/Video.vala"
		break;
#line 18 "../src/Database/Models/Video.vala"
		case REPLAY_VIDEO_TITLE_PROPERTY:
#line 18 "../src/Database/Models/Video.vala"
		replay_video_set_title (self, g_value_get_string (value));
#line 18 "../src/Database/Models/Video.vala"
		break;
#line 18 "../src/Database/Models/Video.vala"
		case REPLAY_VIDEO_DESCRIPTION_PROPERTY:
#line 18 "../src/Database/Models/Video.vala"
		replay_video_set_description (self, g_value_get_string (value));
#line 18 "../src/Database/Models/Video.vala"
		break;
#line 18 "../src/Database/Models/Video.vala"
		case REPLAY_VIDEO_CHANNEL_PROPERTY:
#line 18 "../src/Database/Models/Video.vala"
		replay_video_set_channel (self, g_value_get_object (value));
#line 18 "../src/Database/Models/Video.vala"
		break;
#line 445 "Video.c"
		default:
#line 18 "../src/Database/Models/Video.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 18 "../src/Database/Models/Video.vala"
		break;
#line 451 "Video.c"
	}
}

