/* ObjectFactory.c generated by valac 0.50.1.78-abc6b, the Vala compiler
 * generated from ObjectFactory.vala, do not modify */

/* Replay - An open source YouTube client for GNOME
 * Copyright 2019 - 2020 Nahuel Gomez Castro <nahuel.gomezcastro@outlook.com.ar>
 *
 * Replay is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Replay is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Replay.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <vadi.h>
#include <glib.h>
#include <gio/gio.h>
#include <gee.h>
#include <handy.h>

#define REPLAY_TYPE_APPLICATION (replay_application_get_type ())
#define REPLAY_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_APPLICATION, ReplayApplication))
#define REPLAY_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_APPLICATION, ReplayApplicationClass))
#define REPLAY_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_APPLICATION))
#define REPLAY_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_APPLICATION))
#define REPLAY_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_APPLICATION, ReplayApplicationClass))

typedef struct _ReplayApplication ReplayApplication;
typedef struct _ReplayApplicationClass ReplayApplicationClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block1Data Block1Data;

#define REPLAY_TYPE_OBSERVABLE_LIST (replay_observable_list_get_type ())
#define REPLAY_OBSERVABLE_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_OBSERVABLE_LIST, ReplayObservableList))
#define REPLAY_OBSERVABLE_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_OBSERVABLE_LIST, ReplayObservableListClass))
#define REPLAY_IS_OBSERVABLE_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_OBSERVABLE_LIST))
#define REPLAY_IS_OBSERVABLE_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_OBSERVABLE_LIST))
#define REPLAY_OBSERVABLE_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_OBSERVABLE_LIST, ReplayObservableListClass))

typedef struct _ReplayObservableList ReplayObservableList;
typedef struct _ReplayObservableListClass ReplayObservableListClass;

#define REPLAY_TYPE_PAGE (replay_page_get_type ())
#define REPLAY_PAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_PAGE, ReplayPage))
#define REPLAY_PAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_PAGE, ReplayPageClass))
#define REPLAY_IS_PAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_PAGE))
#define REPLAY_IS_PAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_PAGE))
#define REPLAY_PAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_PAGE, ReplayPageClass))

typedef struct _ReplayPage ReplayPage;
typedef struct _ReplayPageClass ReplayPageClass;

#define REPLAY_TYPE_TRENDING_PAGE (replay_trending_page_get_type ())
#define REPLAY_TRENDING_PAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_TRENDING_PAGE, ReplayTrendingPage))
#define REPLAY_TRENDING_PAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_TRENDING_PAGE, ReplayTrendingPageClass))
#define REPLAY_IS_TRENDING_PAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_TRENDING_PAGE))
#define REPLAY_IS_TRENDING_PAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_TRENDING_PAGE))
#define REPLAY_TRENDING_PAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_TRENDING_PAGE, ReplayTrendingPageClass))

typedef struct _ReplayTrendingPage ReplayTrendingPage;
typedef struct _ReplayTrendingPageClass ReplayTrendingPageClass;

#define REPLAY_TYPE_APPLICATION_WINDOW (replay_application_window_get_type ())
#define REPLAY_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_APPLICATION_WINDOW, ReplayApplicationWindow))
#define REPLAY_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_APPLICATION_WINDOW, ReplayApplicationWindowClass))
#define REPLAY_IS_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_APPLICATION_WINDOW))
#define REPLAY_IS_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_APPLICATION_WINDOW))
#define REPLAY_APPLICATION_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_APPLICATION_WINDOW, ReplayApplicationWindowClass))

typedef struct _ReplayApplicationWindow ReplayApplicationWindow;
typedef struct _ReplayApplicationWindowClass ReplayApplicationWindowClass;

struct _Block1Data {
	int _ref_count_;
	ReplayApplication* app;
};

GType replay_application_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayApplication, g_object_unref)
VdiObjectFactory* replay_utils_get_factory (ReplayApplication* app);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static GObject* __lambda7_ (Block1Data* _data1_,
                     VdiObjectFactory* factory);
static GObject* ___lambda7__vdi_recipe_func (VdiObjectFactory* object_factory,
                                      gpointer self);
static GObject* __lambda8_ (VdiObjectFactory* factory);
GType replay_observable_list_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayObservableList, g_object_unref)
GType replay_page_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayPage, g_object_unref)
ReplayObservableList* replay_observable_list_new (GType t_type,
                                                  GBoxedCopyFunc t_dup_func,
                                                  GDestroyNotify t_destroy_func);
ReplayObservableList* replay_observable_list_construct (GType object_type,
                                                        GType t_type,
                                                        GBoxedCopyFunc t_dup_func,
                                                        GDestroyNotify t_destroy_func);
ReplayTrendingPage* replay_trending_page_new (void);
ReplayTrendingPage* replay_trending_page_construct (GType object_type);
GType replay_trending_page_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayTrendingPage, g_object_unref)
static GObject* ___lambda8__vdi_recipe_func (VdiObjectFactory* object_factory,
                                      gpointer self);
GType replay_application_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayApplicationWindow, g_object_unref)

static gpointer
_g_object_ref0 (gpointer self)
{
#line 20 "../src/Utils/ObjectFactory.vala"
	return self ? g_object_ref (self) : NULL;
#line 122 "ObjectFactory.c"
}

static Block1Data*
block1_data_ref (Block1Data* _data1_)
{
#line 20 "../src/Utils/ObjectFactory.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 20 "../src/Utils/ObjectFactory.vala"
	return _data1_;
#line 132 "ObjectFactory.c"
}

static void
block1_data_unref (void * _userdata_)
{
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 20 "../src/Utils/ObjectFactory.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 20 "../src/Utils/ObjectFactory.vala"
		_g_object_unref0 (_data1_->app);
#line 20 "../src/Utils/ObjectFactory.vala"
		g_slice_free (Block1Data, _data1_);
#line 146 "ObjectFactory.c"
	}
}

static GObject*
__lambda7_ (Block1Data* _data1_,
            VdiObjectFactory* factory)
{
	GObject* _tmp0_;
	GObject* result = NULL;
#line 24 "../src/Utils/ObjectFactory.vala"
	g_return_val_if_fail (factory != NULL, NULL);
#line 24 "../src/Utils/ObjectFactory.vala"
	_tmp0_ = _g_object_ref0 ((GObject*) _data1_->app);
#line 24 "../src/Utils/ObjectFactory.vala"
	result = _tmp0_;
#line 24 "../src/Utils/ObjectFactory.vala"
	return result;
#line 164 "ObjectFactory.c"
}

static GObject*
___lambda7__vdi_recipe_func (VdiObjectFactory* object_factory,
                             gpointer self)
{
	GObject* result;
	result = __lambda7_ (self, object_factory);
#line 24 "../src/Utils/ObjectFactory.vala"
	return result;
#line 175 "ObjectFactory.c"
}

static GObject*
__lambda8_ (VdiObjectFactory* factory)
{
	ReplayObservableList* pages = NULL;
	ReplayObservableList* _tmp0_;
	ReplayTrendingPage* _tmp1_;
	ReplayTrendingPage* _tmp2_;
	GObject* result = NULL;
#line 26 "../src/Utils/ObjectFactory.vala"
	g_return_val_if_fail (factory != NULL, NULL);
#line 27 "../src/Utils/ObjectFactory.vala"
	_tmp0_ = replay_observable_list_new (REPLAY_TYPE_PAGE, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref);
#line 27 "../src/Utils/ObjectFactory.vala"
	pages = _tmp0_;
#line 28 "../src/Utils/ObjectFactory.vala"
	_tmp1_ = replay_trending_page_new ();
#line 28 "../src/Utils/ObjectFactory.vala"
	g_object_ref_sink (_tmp1_);
#line 28 "../src/Utils/ObjectFactory.vala"
	_tmp2_ = _tmp1_;
#line 28 "../src/Utils/ObjectFactory.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) pages, (ReplayPage*) _tmp2_);
#line 28 "../src/Utils/ObjectFactory.vala"
	_g_object_unref0 (_tmp2_);
#line 29 "../src/Utils/ObjectFactory.vala"
	result = (GObject*) pages;
#line 29 "../src/Utils/ObjectFactory.vala"
	return result;
#line 206 "ObjectFactory.c"
}

static GObject*
___lambda8__vdi_recipe_func (VdiObjectFactory* object_factory,
                             gpointer self)
{
	GObject* result;
	result = __lambda8_ (object_factory);
#line 26 "../src/Utils/ObjectFactory.vala"
	return result;
#line 217 "ObjectFactory.c"
}

VdiObjectFactory*
replay_utils_get_factory (ReplayApplication* app)
{
	Block1Data* _data1_;
	ReplayApplication* _tmp0_;
	VdiObjectFactory* factory = NULL;
	VdiObjectFactory* _tmp1_;
	VdiObjectFactory* result = NULL;
#line 20 "../src/Utils/ObjectFactory.vala"
	g_return_val_if_fail (app != NULL, NULL);
#line 20 "../src/Utils/ObjectFactory.vala"
	_data1_ = g_slice_new0 (Block1Data);
#line 20 "../src/Utils/ObjectFactory.vala"
	_data1_->_ref_count_ = 1;
#line 20 "../src/Utils/ObjectFactory.vala"
	_tmp0_ = _g_object_ref0 (app);
#line 20 "../src/Utils/ObjectFactory.vala"
	_g_object_unref0 (_data1_->app);
#line 20 "../src/Utils/ObjectFactory.vala"
	_data1_->app = _tmp0_;
#line 22 "../src/Utils/ObjectFactory.vala"
	_tmp1_ = vdi_object_factory_new ();
#line 22 "../src/Utils/ObjectFactory.vala"
	factory = _tmp1_;
#line 24 "../src/Utils/ObjectFactory.vala"
	vdi_object_factory_order_with_recipe (factory, gtk_application_get_type (), ___lambda7__vdi_recipe_func, block1_data_ref (_data1_), block1_data_unref);
#line 26 "../src/Utils/ObjectFactory.vala"
	vdi_object_factory_order_with_recipe (factory, g_list_model_get_type (), ___lambda8__vdi_recipe_func, NULL, NULL);
#line 32 "../src/Utils/ObjectFactory.vala"
	vdi_object_factory_order (factory, REPLAY_TYPE_APPLICATION_WINDOW);
#line 34 "../src/Utils/ObjectFactory.vala"
	result = factory;
#line 34 "../src/Utils/ObjectFactory.vala"
	block1_data_unref (_data1_);
#line 34 "../src/Utils/ObjectFactory.vala"
	_data1_ = NULL;
#line 34 "../src/Utils/ObjectFactory.vala"
	return result;
#line 258 "ObjectFactory.c"
}

