/* ObservableList.c generated by valac 0.50.1.78-abc6b, the Vala compiler
 * generated from ObservableList.vala, do not modify */

/* Replay - An open source YouTube client for GNOME
 * Copyright 2019 - 2020 Nahuel Gomez Castro <nahuel.gomezcastro@outlook.com.ar>
 *
 * Replay is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Replay is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Replay.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <gee.h>
#include <gio/gio.h>
#include <glib-object.h>
#include <glib.h>

#define REPLAY_TYPE_OBSERVABLE_LIST (replay_observable_list_get_type ())
#define REPLAY_OBSERVABLE_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_OBSERVABLE_LIST, ReplayObservableList))
#define REPLAY_OBSERVABLE_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_OBSERVABLE_LIST, ReplayObservableListClass))
#define REPLAY_IS_OBSERVABLE_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_OBSERVABLE_LIST))
#define REPLAY_IS_OBSERVABLE_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_OBSERVABLE_LIST))
#define REPLAY_OBSERVABLE_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_OBSERVABLE_LIST, ReplayObservableListClass))

typedef struct _ReplayObservableList ReplayObservableList;
typedef struct _ReplayObservableListClass ReplayObservableListClass;
typedef struct _ReplayObservableListPrivate ReplayObservableListPrivate;
enum  {
	REPLAY_OBSERVABLE_LIST_0_PROPERTY,
	REPLAY_OBSERVABLE_LIST_T_TYPE,
	REPLAY_OBSERVABLE_LIST_T_DUP_FUNC,
	REPLAY_OBSERVABLE_LIST_T_DESTROY_FUNC,
	REPLAY_OBSERVABLE_LIST_READ_ONLY_PROPERTY,
	REPLAY_OBSERVABLE_LIST_SIZE_PROPERTY,
	REPLAY_OBSERVABLE_LIST_NUM_PROPERTIES
};
static GParamSpec* replay_observable_list_properties[REPLAY_OBSERVABLE_LIST_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _ReplayObservableList {
	GeeAbstractList parent_instance;
	ReplayObservableListPrivate * priv;
};

struct _ReplayObservableListClass {
	GeeAbstractListClass parent_class;
};

struct _ReplayObservableListPrivate {
	GType t_type;
	GBoxedCopyFunc t_dup_func;
	GDestroyNotify t_destroy_func;
	GeeList* _data;
};

static gint ReplayObservableList_private_offset;
static gpointer replay_observable_list_parent_class = NULL;
static GListModelInterface * replay_observable_list_g_list_model_parent_iface = NULL;

GType replay_observable_list_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayObservableList, g_object_unref)
ReplayObservableList* replay_observable_list_new_from_list (GType t_type,
                                                            GBoxedCopyFunc t_dup_func,
                                                            GDestroyNotify t_destroy_func,
                                                            GeeList* data);
ReplayObservableList* replay_observable_list_construct_from_list (GType object_type,
                                                                  GType t_type,
                                                                  GBoxedCopyFunc t_dup_func,
                                                                  GDestroyNotify t_destroy_func,
                                                                  GeeList* data);
gboolean replay_observable_list_add_all (ReplayObservableList* self,
                                         GeeCollection* collection);
static gboolean replay_observable_list_real_add (GeeAbstractCollection* base,
                                          gconstpointer item);
static void replay_observable_list_real_clear (GeeAbstractCollection* base);
static gboolean replay_observable_list_real_contains (GeeAbstractCollection* base,
                                               gconstpointer item);
static gpointer replay_observable_list_real_get (GeeAbstractList* base,
                                          gint index);
static GObject* replay_observable_list_real_get_item (GListModel* base,
                                               guint position);
static GType replay_observable_list_real_get_item_type (GListModel* base);
static guint replay_observable_list_real_get_n_items (GListModel* base);
static gint replay_observable_list_real_index_of (GeeAbstractList* base,
                                           gconstpointer item);
static void replay_observable_list_real_insert (GeeAbstractList* base,
                                         gint index,
                                         gconstpointer item);
static GeeIterator* replay_observable_list_real_iterator (GeeAbstractCollection* base);
static GeeListIterator* replay_observable_list_real_list_iterator (GeeAbstractList* base);
static gboolean replay_observable_list_real_remove (GeeAbstractCollection* base,
                                             gconstpointer item);
static gpointer replay_observable_list_real_remove_at (GeeAbstractList* base,
                                                gint index);
static void replay_observable_list_real_set (GeeAbstractList* base,
                                      gint index,
                                      gconstpointer item);
static GeeList* replay_observable_list_real_slice (GeeAbstractList* base,
                                            gint start,
                                            gint stop);
ReplayObservableList* replay_observable_list_new (GType t_type,
                                                  GBoxedCopyFunc t_dup_func,
                                                  GDestroyNotify t_destroy_func);
ReplayObservableList* replay_observable_list_construct (GType object_type,
                                                        GType t_type,
                                                        GBoxedCopyFunc t_dup_func,
                                                        GDestroyNotify t_destroy_func);
static GObject * replay_observable_list_constructor (GType type,
                                              guint n_construct_properties,
                                              GObjectConstructParam * construct_properties);
static void replay_observable_list_finalize (GObject * obj);
static GType replay_observable_list_get_type_once (void);
static void _vala_replay_observable_list_get_property (GObject * object,
                                                guint property_id,
                                                GValue * value,
                                                GParamSpec * pspec);
static void _vala_replay_observable_list_set_property (GObject * object,
                                                guint property_id,
                                                const GValue * value,
                                                GParamSpec * pspec);

static inline gpointer
replay_observable_list_get_instance_private (ReplayObservableList* self)
{
	return G_STRUCT_MEMBER_P (self, ReplayObservableList_private_offset);
}

ReplayObservableList*
replay_observable_list_construct_from_list (GType object_type,
                                            GType t_type,
                                            GBoxedCopyFunc t_dup_func,
                                            GDestroyNotify t_destroy_func,
                                            GeeList* data)
{
	ReplayObservableList * self = NULL;
#line 34 "../src/Utils/ObservableList.vala"
	g_return_val_if_fail (data != NULL, NULL);
#line 34 "../src/Utils/ObservableList.vala"
	self = (ReplayObservableList*) gee_abstract_list_construct (object_type, t_type, (GBoxedCopyFunc) t_dup_func, (GDestroyNotify) t_destroy_func);
#line 34 "../src/Utils/ObservableList.vala"
	self->priv->t_type = t_type;
#line 34 "../src/Utils/ObservableList.vala"
	self->priv->t_dup_func = t_dup_func;
#line 34 "../src/Utils/ObservableList.vala"
	self->priv->t_destroy_func = t_destroy_func;
#line 36 "../src/Utils/ObservableList.vala"
	replay_observable_list_add_all (self, (GeeCollection*) data);
#line 34 "../src/Utils/ObservableList.vala"
	return self;
#line 163 "ObservableList.c"
}

ReplayObservableList*
replay_observable_list_new_from_list (GType t_type,
                                      GBoxedCopyFunc t_dup_func,
                                      GDestroyNotify t_destroy_func,
                                      GeeList* data)
{
#line 34 "../src/Utils/ObservableList.vala"
	return replay_observable_list_construct_from_list (REPLAY_TYPE_OBSERVABLE_LIST, t_type, t_dup_func, t_destroy_func, data);
#line 174 "ObservableList.c"
}

static gboolean
replay_observable_list_real_add (GeeAbstractCollection* base,
                                 gconstpointer item)
{
	ReplayObservableList * self;
	gboolean added = FALSE;
	GeeList* _tmp0_;
	gboolean result = FALSE;
#line 40 "../src/Utils/ObservableList.vala"
	self = (ReplayObservableList*) base;
#line 42 "../src/Utils/ObservableList.vala"
	_tmp0_ = self->priv->_data;
#line 42 "../src/Utils/ObservableList.vala"
	added = gee_collection_add ((GeeCollection*) _tmp0_, item);
#line 44 "../src/Utils/ObservableList.vala"
	if (added) {
#line 45 "../src/Utils/ObservableList.vala"
		g_list_model_items_changed ((GListModel*) self, (guint) gee_abstract_list_index_of ((GeeAbstractList*) self, item), (guint) 0, (guint) 1);
#line 195 "ObservableList.c"
	}
#line 47 "../src/Utils/ObservableList.vala"
	result = added;
#line 47 "../src/Utils/ObservableList.vala"
	return result;
#line 201 "ObservableList.c"
}

gboolean
replay_observable_list_add_all (ReplayObservableList* self,
                                GeeCollection* collection)
{
	gboolean result = FALSE;
#line 50 "../src/Utils/ObservableList.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 50 "../src/Utils/ObservableList.vala"
	g_return_val_if_fail (collection != NULL, FALSE);
#line 213 "ObservableList.c"
	{
		GeeIterator* _item_it = NULL;
		GeeIterator* _tmp0_;
#line 52 "../src/Utils/ObservableList.vala"
		_tmp0_ = gee_iterable_iterator ((GeeIterable*) collection);
#line 52 "../src/Utils/ObservableList.vala"
		_item_it = _tmp0_;
#line 52 "../src/Utils/ObservableList.vala"
		while (TRUE) {
#line 223 "ObservableList.c"
			GeeIterator* _tmp1_;
			gpointer item = NULL;
			GeeIterator* _tmp2_;
			gpointer _tmp3_;
			gconstpointer _tmp4_;
#line 52 "../src/Utils/ObservableList.vala"
			_tmp1_ = _item_it;
#line 52 "../src/Utils/ObservableList.vala"
			if (!gee_iterator_next (_tmp1_)) {
#line 52 "../src/Utils/ObservableList.vala"
				break;
#line 235 "ObservableList.c"
			}
#line 52 "../src/Utils/ObservableList.vala"
			_tmp2_ = _item_it;
#line 52 "../src/Utils/ObservableList.vala"
			_tmp3_ = gee_iterator_get (_tmp2_);
#line 52 "../src/Utils/ObservableList.vala"
			item = _tmp3_;
#line 53 "../src/Utils/ObservableList.vala"
			_tmp4_ = item;
#line 53 "../src/Utils/ObservableList.vala"
			if (!gee_abstract_collection_add ((GeeAbstractCollection*) self, _tmp4_)) {
#line 53 "../src/Utils/ObservableList.vala"
				result = FALSE;
#line 53 "../src/Utils/ObservableList.vala"
				((item == NULL) || (self->priv->t_destroy_func == NULL)) ? NULL : (item = (self->priv->t_destroy_func (item), NULL));
#line 53 "../src/Utils/ObservableList.vala"
				_g_object_unref0 (_item_it);
#line 53 "../src/Utils/ObservableList.vala"
				return result;
#line 255 "ObservableList.c"
			}
#line 52 "../src/Utils/ObservableList.vala"
			((item == NULL) || (self->priv->t_destroy_func == NULL)) ? NULL : (item = (self->priv->t_destroy_func (item), NULL));
#line 259 "ObservableList.c"
		}
#line 52 "../src/Utils/ObservableList.vala"
		_g_object_unref0 (_item_it);
#line 263 "ObservableList.c"
	}
#line 55 "../src/Utils/ObservableList.vala"
	result = TRUE;
#line 55 "../src/Utils/ObservableList.vala"
	return result;
#line 269 "ObservableList.c"
}

static void
replay_observable_list_real_clear (GeeAbstractCollection* base)
{
	ReplayObservableList * self;
	gint size = 0;
	GeeList* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	GeeList* _tmp3_;
#line 58 "../src/Utils/ObservableList.vala"
	self = (ReplayObservableList*) base;
#line 60 "../src/Utils/ObservableList.vala"
	_tmp0_ = self->priv->_data;
#line 60 "../src/Utils/ObservableList.vala"
	_tmp1_ = gee_collection_get_size ((GeeCollection*) _tmp0_);
#line 60 "../src/Utils/ObservableList.vala"
	_tmp2_ = _tmp1_;
#line 60 "../src/Utils/ObservableList.vala"
	size = _tmp2_;
#line 61 "../src/Utils/ObservableList.vala"
	_tmp3_ = self->priv->_data;
#line 61 "../src/Utils/ObservableList.vala"
	gee_collection_clear ((GeeCollection*) _tmp3_);
#line 62 "../src/Utils/ObservableList.vala"
	g_list_model_items_changed ((GListModel*) self, (guint) 0, (guint) size, (guint) 0);
#line 297 "ObservableList.c"
}

static gboolean
replay_observable_list_real_contains (GeeAbstractCollection* base,
                                      gconstpointer item)
{
	ReplayObservableList * self;
	GeeList* _tmp0_;
	gboolean result = FALSE;
#line 65 "../src/Utils/ObservableList.vala"
	self = (ReplayObservableList*) base;
#line 67 "../src/Utils/ObservableList.vala"
	_tmp0_ = self->priv->_data;
#line 67 "../src/Utils/ObservableList.vala"
	result = gee_collection_contains ((GeeCollection*) _tmp0_, item);
#line 67 "../src/Utils/ObservableList.vala"
	return result;
#line 315 "ObservableList.c"
}

static gpointer
replay_observable_list_real_get (GeeAbstractList* base,
                                 gint index)
{
	ReplayObservableList * self;
	GeeList* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	GeeList* _tmp3_;
	gpointer _tmp4_;
	gpointer result = NULL;
#line 70 "../src/Utils/ObservableList.vala"
	self = (ReplayObservableList*) base;
#line 70 "../src/Utils/ObservableList.vala"
	_vala_return_val_if_fail (index >= 0, "index >= 0", NULL);
#line 70 "../src/Utils/ObservableList.vala"
	_tmp0_ = self->priv->_data;
#line 70 "../src/Utils/ObservableList.vala"
	_tmp1_ = gee_collection_get_size ((GeeCollection*) _tmp0_);
#line 70 "../src/Utils/ObservableList.vala"
	_tmp2_ = _tmp1_;
#line 70 "../src/Utils/ObservableList.vala"
	_vala_return_val_if_fail (index < _tmp2_, "index < this._data.size", NULL);
#line 74 "../src/Utils/ObservableList.vala"
	_tmp3_ = self->priv->_data;
#line 74 "../src/Utils/ObservableList.vala"
	_tmp4_ = gee_list_get (_tmp3_, index);
#line 74 "../src/Utils/ObservableList.vala"
	result = _tmp4_;
#line 74 "../src/Utils/ObservableList.vala"
	return result;
#line 349 "ObservableList.c"
}

static GObject*
replay_observable_list_real_get_item (GListModel* base,
                                      guint position)
{
	ReplayObservableList * self;
	GeeList* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	GeeList* _tmp3_;
	gpointer _tmp4_;
	GObject* _tmp5_;
	GObject* result = NULL;
#line 77 "../src/Utils/ObservableList.vala"
	self = (ReplayObservableList*) base;
#line 77 "../src/Utils/ObservableList.vala"
	_vala_return_val_if_fail (position >= ((guint) 0), "position >= 0", NULL);
#line 77 "../src/Utils/ObservableList.vala"
	_tmp0_ = self->priv->_data;
#line 77 "../src/Utils/ObservableList.vala"
	_tmp1_ = gee_collection_get_size ((GeeCollection*) _tmp0_);
#line 77 "../src/Utils/ObservableList.vala"
	_tmp2_ = _tmp1_;
#line 77 "../src/Utils/ObservableList.vala"
	_vala_return_val_if_fail (position < ((guint) _tmp2_), "position < this._data.size", NULL);
#line 81 "../src/Utils/ObservableList.vala"
	_tmp3_ = self->priv->_data;
#line 81 "../src/Utils/ObservableList.vala"
	_tmp4_ = gee_list_get (_tmp3_, (gint) position);
#line 81 "../src/Utils/ObservableList.vala"
	_tmp5_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp4_, G_TYPE_OBJECT) ? ((GObject*) _tmp4_) : NULL;
#line 81 "../src/Utils/ObservableList.vala"
	if (_tmp5_ == NULL) {
#line 81 "../src/Utils/ObservableList.vala"
		((_tmp4_ == NULL) || (self->priv->t_destroy_func == NULL)) ? NULL : (_tmp4_ = (self->priv->t_destroy_func (_tmp4_), NULL));
#line 386 "ObservableList.c"
	}
#line 81 "../src/Utils/ObservableList.vala"
	result = _tmp5_;
#line 81 "../src/Utils/ObservableList.vala"
	return result;
#line 392 "ObservableList.c"
}

static GType
replay_observable_list_real_get_item_type (GListModel* base)
{
	ReplayObservableList * self;
	GType result = 0UL;
#line 84 "../src/Utils/ObservableList.vala"
	self = (ReplayObservableList*) base;
#line 86 "../src/Utils/ObservableList.vala"
	result = self->priv->t_type;
#line 86 "../src/Utils/ObservableList.vala"
	return result;
#line 406 "ObservableList.c"
}

static guint
replay_observable_list_real_get_n_items (GListModel* base)
{
	ReplayObservableList * self;
	GeeList* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	guint result = 0U;
#line 89 "../src/Utils/ObservableList.vala"
	self = (ReplayObservableList*) base;
#line 91 "../src/Utils/ObservableList.vala"
	_tmp0_ = self->priv->_data;
#line 91 "../src/Utils/ObservableList.vala"
	_tmp1_ = gee_collection_get_size ((GeeCollection*) _tmp0_);
#line 91 "../src/Utils/ObservableList.vala"
	_tmp2_ = _tmp1_;
#line 91 "../src/Utils/ObservableList.vala"
	result = (guint) _tmp2_;
#line 91 "../src/Utils/ObservableList.vala"
	return result;
#line 429 "ObservableList.c"
}

static gint
replay_observable_list_real_index_of (GeeAbstractList* base,
                                      gconstpointer item)
{
	ReplayObservableList * self;
	GeeList* _tmp0_;
	gint result = 0;
#line 94 "../src/Utils/ObservableList.vala"
	self = (ReplayObservableList*) base;
#line 96 "../src/Utils/ObservableList.vala"
	_tmp0_ = self->priv->_data;
#line 96 "../src/Utils/ObservableList.vala"
	result = gee_list_index_of (_tmp0_, item);
#line 96 "../src/Utils/ObservableList.vala"
	return result;
#line 447 "ObservableList.c"
}

static void
replay_observable_list_real_insert (GeeAbstractList* base,
                                    gint index,
                                    gconstpointer item)
{
	ReplayObservableList * self;
	GeeList* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	GeeList* _tmp3_;
#line 99 "../src/Utils/ObservableList.vala"
	self = (ReplayObservableList*) base;
#line 99 "../src/Utils/ObservableList.vala"
	_vala_return_if_fail (index >= 0, "index >= 0");
#line 99 "../src/Utils/ObservableList.vala"
	_tmp0_ = self->priv->_data;
#line 99 "../src/Utils/ObservableList.vala"
	_tmp1_ = gee_collection_get_size ((GeeCollection*) _tmp0_);
#line 99 "../src/Utils/ObservableList.vala"
	_tmp2_ = _tmp1_;
#line 99 "../src/Utils/ObservableList.vala"
	_vala_return_if_fail (index < _tmp2_, "index < this._data.size");
#line 103 "../src/Utils/ObservableList.vala"
	_tmp3_ = self->priv->_data;
#line 103 "../src/Utils/ObservableList.vala"
	gee_list_insert (_tmp3_, index, item);
#line 104 "../src/Utils/ObservableList.vala"
	g_list_model_items_changed ((GListModel*) self, (guint) index, (guint) 0, (guint) 1);
#line 478 "ObservableList.c"
}

static GeeIterator*
replay_observable_list_real_iterator (GeeAbstractCollection* base)
{
	ReplayObservableList * self;
	GeeList* _tmp0_;
	GeeIterator* _tmp1_;
	GeeIterator* result = NULL;
#line 107 "../src/Utils/ObservableList.vala"
	self = (ReplayObservableList*) base;
#line 109 "../src/Utils/ObservableList.vala"
	_tmp0_ = self->priv->_data;
#line 109 "../src/Utils/ObservableList.vala"
	_tmp1_ = gee_iterable_iterator ((GeeIterable*) _tmp0_);
#line 109 "../src/Utils/ObservableList.vala"
	result = _tmp1_;
#line 109 "../src/Utils/ObservableList.vala"
	return result;
#line 498 "ObservableList.c"
}

static GeeListIterator*
replay_observable_list_real_list_iterator (GeeAbstractList* base)
{
	ReplayObservableList * self;
	GeeList* _tmp0_;
	GeeListIterator* _tmp1_;
	GeeListIterator* result = NULL;
#line 112 "../src/Utils/ObservableList.vala"
	self = (ReplayObservableList*) base;
#line 114 "../src/Utils/ObservableList.vala"
	_tmp0_ = self->priv->_data;
#line 114 "../src/Utils/ObservableList.vala"
	_tmp1_ = gee_list_list_iterator (_tmp0_);
#line 114 "../src/Utils/ObservableList.vala"
	result = _tmp1_;
#line 114 "../src/Utils/ObservableList.vala"
	return result;
#line 518 "ObservableList.c"
}

static gboolean
replay_observable_list_real_remove (GeeAbstractCollection* base,
                                    gconstpointer item)
{
	ReplayObservableList * self;
	gboolean removed = FALSE;
	GeeList* _tmp0_;
	gboolean result = FALSE;
#line 117 "../src/Utils/ObservableList.vala"
	self = (ReplayObservableList*) base;
#line 119 "../src/Utils/ObservableList.vala"
	_tmp0_ = self->priv->_data;
#line 119 "../src/Utils/ObservableList.vala"
	removed = gee_collection_remove ((GeeCollection*) _tmp0_, item);
#line 121 "../src/Utils/ObservableList.vala"
	if (removed) {
#line 537 "ObservableList.c"
		GeeList* _tmp1_;
#line 122 "../src/Utils/ObservableList.vala"
		_tmp1_ = self->priv->_data;
#line 122 "../src/Utils/ObservableList.vala"
		g_list_model_items_changed ((GListModel*) self, (guint) gee_list_index_of (_tmp1_, item), (guint) 1, (guint) 0);
#line 543 "ObservableList.c"
	}
#line 124 "../src/Utils/ObservableList.vala"
	result = removed;
#line 124 "../src/Utils/ObservableList.vala"
	return result;
#line 549 "ObservableList.c"
}

static gpointer
replay_observable_list_real_remove_at (GeeAbstractList* base,
                                       gint index)
{
	ReplayObservableList * self;
	GeeList* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	gpointer item_removed = NULL;
	GeeList* _tmp3_;
	gpointer _tmp4_;
	gpointer result = NULL;
#line 127 "../src/Utils/ObservableList.vala"
	self = (ReplayObservableList*) base;
#line 127 "../src/Utils/ObservableList.vala"
	_vala_return_val_if_fail (index >= 0, "index >= 0", NULL);
#line 127 "../src/Utils/ObservableList.vala"
	_tmp0_ = self->priv->_data;
#line 127 "../src/Utils/ObservableList.vala"
	_tmp1_ = gee_collection_get_size ((GeeCollection*) _tmp0_);
#line 127 "../src/Utils/ObservableList.vala"
	_tmp2_ = _tmp1_;
#line 127 "../src/Utils/ObservableList.vala"
	_vala_return_val_if_fail (index < _tmp2_, "index < this._data.size", NULL);
#line 131 "../src/Utils/ObservableList.vala"
	_tmp3_ = self->priv->_data;
#line 131 "../src/Utils/ObservableList.vala"
	_tmp4_ = gee_list_remove_at (_tmp3_, index);
#line 131 "../src/Utils/ObservableList.vala"
	item_removed = _tmp4_;
#line 132 "../src/Utils/ObservableList.vala"
	g_list_model_items_changed ((GListModel*) self, (guint) index, (guint) 1, (guint) 0);
#line 133 "../src/Utils/ObservableList.vala"
	result = item_removed;
#line 133 "../src/Utils/ObservableList.vala"
	return result;
#line 588 "ObservableList.c"
}

static void
replay_observable_list_real_set (GeeAbstractList* base,
                                 gint index,
                                 gconstpointer item)
{
	ReplayObservableList * self;
	GeeList* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	GeeList* _tmp3_;
#line 136 "../src/Utils/ObservableList.vala"
	self = (ReplayObservableList*) base;
#line 136 "../src/Utils/ObservableList.vala"
	_vala_return_if_fail (index >= 0, "index >= 0");
#line 136 "../src/Utils/ObservableList.vala"
	_tmp0_ = self->priv->_data;
#line 136 "../src/Utils/ObservableList.vala"
	_tmp1_ = gee_collection_get_size ((GeeCollection*) _tmp0_);
#line 136 "../src/Utils/ObservableList.vala"
	_tmp2_ = _tmp1_;
#line 136 "../src/Utils/ObservableList.vala"
	_vala_return_if_fail (index < _tmp2_, "index < this._data.size");
#line 140 "../src/Utils/ObservableList.vala"
	_tmp3_ = self->priv->_data;
#line 140 "../src/Utils/ObservableList.vala"
	gee_list_set (_tmp3_, index, item);
#line 141 "../src/Utils/ObservableList.vala"
	g_list_model_items_changed ((GListModel*) self, (guint) index, (guint) 1, (guint) 1);
#line 619 "ObservableList.c"
}

static GeeList*
replay_observable_list_real_slice (GeeAbstractList* base,
                                   gint start,
                                   gint stop)
{
	ReplayObservableList * self;
	GeeList* _tmp0_;
	GeeList* _tmp1_;
	GeeList* result = NULL;
#line 144 "../src/Utils/ObservableList.vala"
	self = (ReplayObservableList*) base;
#line 146 "../src/Utils/ObservableList.vala"
	_tmp0_ = self->priv->_data;
#line 146 "../src/Utils/ObservableList.vala"
	_tmp1_ = gee_list_slice (_tmp0_, start, stop);
#line 146 "../src/Utils/ObservableList.vala"
	result = _tmp1_;
#line 146 "../src/Utils/ObservableList.vala"
	return result;
#line 641 "ObservableList.c"
}

ReplayObservableList*
replay_observable_list_construct (GType object_type,
                                  GType t_type,
                                  GBoxedCopyFunc t_dup_func,
                                  GDestroyNotify t_destroy_func)
{
	ReplayObservableList * self = NULL;
#line 18 "../src/Utils/ObservableList.vala"
	self = (ReplayObservableList*) gee_abstract_list_construct (object_type, t_type, (GBoxedCopyFunc) t_dup_func, (GDestroyNotify) t_destroy_func);
#line 18 "../src/Utils/ObservableList.vala"
	self->priv->t_type = t_type;
#line 18 "../src/Utils/ObservableList.vala"
	self->priv->t_dup_func = t_dup_func;
#line 18 "../src/Utils/ObservableList.vala"
	self->priv->t_destroy_func = t_destroy_func;
#line 18 "../src/Utils/ObservableList.vala"
	return self;
#line 661 "ObservableList.c"
}

ReplayObservableList*
replay_observable_list_new (GType t_type,
                            GBoxedCopyFunc t_dup_func,
                            GDestroyNotify t_destroy_func)
{
#line 18 "../src/Utils/ObservableList.vala"
	return replay_observable_list_construct (REPLAY_TYPE_OBSERVABLE_LIST, t_type, t_dup_func, t_destroy_func);
#line 671 "ObservableList.c"
}

static gboolean
replay_observable_list_real_get_read_only (GeeAbstractCollection* base)
{
	gboolean result;
	ReplayObservableList* self;
	GeeList* _tmp0_;
	gboolean _tmp1_;
	gboolean _tmp2_;
#line 25 "../src/Utils/ObservableList.vala"
	self = (ReplayObservableList*) base;
#line 25 "../src/Utils/ObservableList.vala"
	_tmp0_ = self->priv->_data;
#line 25 "../src/Utils/ObservableList.vala"
	_tmp1_ = gee_collection_get_read_only ((GeeCollection*) _tmp0_);
#line 25 "../src/Utils/ObservableList.vala"
	_tmp2_ = _tmp1_;
#line 25 "../src/Utils/ObservableList.vala"
	result = _tmp2_;
#line 25 "../src/Utils/ObservableList.vala"
	return result;
#line 694 "ObservableList.c"
}

static gint
replay_observable_list_real_get_size (GeeAbstractCollection* base)
{
	gint result;
	ReplayObservableList* self;
	GeeList* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
#line 30 "../src/Utils/ObservableList.vala"
	self = (ReplayObservableList*) base;
#line 30 "../src/Utils/ObservableList.vala"
	_tmp0_ = self->priv->_data;
#line 30 "../src/Utils/ObservableList.vala"
	_tmp1_ = gee_collection_get_size ((GeeCollection*) _tmp0_);
#line 30 "../src/Utils/ObservableList.vala"
	_tmp2_ = _tmp1_;
#line 30 "../src/Utils/ObservableList.vala"
	result = _tmp2_;
#line 30 "../src/Utils/ObservableList.vala"
	return result;
#line 717 "ObservableList.c"
}

static GObject *
replay_observable_list_constructor (GType type,
                                    guint n_construct_properties,
                                    GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	ReplayObservableList * self;
	GeeArrayList* _tmp0_;
#line 150 "../src/Utils/ObservableList.vala"
	parent_class = G_OBJECT_CLASS (replay_observable_list_parent_class);
#line 150 "../src/Utils/ObservableList.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 150 "../src/Utils/ObservableList.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, REPLAY_TYPE_OBSERVABLE_LIST, ReplayObservableList);
#line 152 "../src/Utils/ObservableList.vala"
	_tmp0_ = gee_array_list_new (self->priv->t_type, (GBoxedCopyFunc) self->priv->t_dup_func, (GDestroyNotify) self->priv->t_destroy_func, NULL, NULL, NULL);
#line 152 "../src/Utils/ObservableList.vala"
	_g_object_unref0 (self->priv->_data);
#line 152 "../src/Utils/ObservableList.vala"
	self->priv->_data = (GeeList*) _tmp0_;
#line 150 "../src/Utils/ObservableList.vala"
	return obj;
#line 743 "ObservableList.c"
}

static void
replay_observable_list_class_init (ReplayObservableListClass * klass,
                                   gpointer klass_data)
{
#line 18 "../src/Utils/ObservableList.vala"
	replay_observable_list_parent_class = g_type_class_peek_parent (klass);
#line 18 "../src/Utils/ObservableList.vala"
	g_type_class_adjust_private_offset (klass, &ReplayObservableList_private_offset);
#line 18 "../src/Utils/ObservableList.vala"
	((GeeAbstractCollectionClass *) klass)->add = (gboolean (*) (GeeAbstractCollection*, gconstpointer)) replay_observable_list_real_add;
#line 18 "../src/Utils/ObservableList.vala"
	((GeeAbstractCollectionClass *) klass)->clear = (void (*) (GeeAbstractCollection*)) replay_observable_list_real_clear;
#line 18 "../src/Utils/ObservableList.vala"
	((GeeAbstractCollectionClass *) klass)->contains = (gboolean (*) (GeeAbstractCollection*, gconstpointer)) replay_observable_list_real_contains;
#line 18 "../src/Utils/ObservableList.vala"
	((GeeAbstractListClass *) klass)->get = (gpointer (*) (GeeAbstractList*, gint)) replay_observable_list_real_get;
#line 18 "../src/Utils/ObservableList.vala"
	((GeeAbstractListClass *) klass)->index_of = (gint (*) (GeeAbstractList*, gconstpointer)) replay_observable_list_real_index_of;
#line 18 "../src/Utils/ObservableList.vala"
	((GeeAbstractListClass *) klass)->insert = (void (*) (GeeAbstractList*, gint, gconstpointer)) replay_observable_list_real_insert;
#line 18 "../src/Utils/ObservableList.vala"
	((GeeAbstractCollectionClass *) klass)->iterator = (GeeIterator* (*) (GeeAbstractCollection*)) replay_observable_list_real_iterator;
#line 18 "../src/Utils/ObservableList.vala"
	((GeeAbstractListClass *) klass)->list_iterator = (GeeListIterator* (*) (GeeAbstractList*)) replay_observable_list_real_list_iterator;
#line 18 "../src/Utils/ObservableList.vala"
	((GeeAbstractCollectionClass *) klass)->remove = (gboolean (*) (GeeAbstractCollection*, gconstpointer)) replay_observable_list_real_remove;
#line 18 "../src/Utils/ObservableList.vala"
	((GeeAbstractListClass *) klass)->remove_at = (gpointer (*) (GeeAbstractList*, gint)) replay_observable_list_real_remove_at;
#line 18 "../src/Utils/ObservableList.vala"
	((GeeAbstractListClass *) klass)->set = (void (*) (GeeAbstractList*, gint, gconstpointer)) replay_observable_list_real_set;
#line 18 "../src/Utils/ObservableList.vala"
	((GeeAbstractListClass *) klass)->slice = (GeeList* (*) (GeeAbstractList*, gint, gint)) replay_observable_list_real_slice;
#line 18 "../src/Utils/ObservableList.vala"
	GEE_ABSTRACT_COLLECTION_CLASS (klass)->get_read_only = replay_observable_list_real_get_read_only;
#line 18 "../src/Utils/ObservableList.vala"
	GEE_ABSTRACT_COLLECTION_CLASS (klass)->get_size = replay_observable_list_real_get_size;
#line 18 "../src/Utils/ObservableList.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_replay_observable_list_get_property;
#line 18 "../src/Utils/ObservableList.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_replay_observable_list_set_property;
#line 18 "../src/Utils/ObservableList.vala"
	G_OBJECT_CLASS (klass)->constructor = replay_observable_list_constructor;
#line 18 "../src/Utils/ObservableList.vala"
	G_OBJECT_CLASS (klass)->finalize = replay_observable_list_finalize;
#line 18 "../src/Utils/ObservableList.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_OBSERVABLE_LIST_T_TYPE, g_param_spec_gtype ("t-type", "type", "type", G_TYPE_NONE, G_PARAM_STATIC_STRINGS | G_PARAM_READWRITE | G_PARAM_CONSTRUCT_ONLY));
#line 18 "../src/Utils/ObservableList.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_OBSERVABLE_LIST_T_DUP_FUNC, g_param_spec_pointer ("t-dup-func", "dup func", "dup func", G_PARAM_STATIC_STRINGS | G_PARAM_READWRITE | G_PARAM_CONSTRUCT_ONLY));
#line 18 "../src/Utils/ObservableList.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_OBSERVABLE_LIST_T_DESTROY_FUNC, g_param_spec_pointer ("t-destroy-func", "destroy func", "destroy func", G_PARAM_STATIC_STRINGS | G_PARAM_READWRITE | G_PARAM_CONSTRUCT_ONLY));
#line 18 "../src/Utils/ObservableList.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_OBSERVABLE_LIST_READ_ONLY_PROPERTY, replay_observable_list_properties[REPLAY_OBSERVABLE_LIST_READ_ONLY_PROPERTY] = g_param_spec_boolean ("read-only", "read-only", "read-only", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
#line 18 "../src/Utils/ObservableList.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_OBSERVABLE_LIST_SIZE_PROPERTY, replay_observable_list_properties[REPLAY_OBSERVABLE_LIST_SIZE_PROPERTY] = g_param_spec_int ("size", "size", "size", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
#line 800 "ObservableList.c"
}

static void
replay_observable_list_g_list_model_interface_init (GListModelInterface * iface,
                                                    gpointer iface_data)
{
#line 18 "../src/Utils/ObservableList.vala"
	replay_observable_list_g_list_model_parent_iface = g_type_interface_peek_parent (iface);
#line 18 "../src/Utils/ObservableList.vala"
	iface->get_item = (GObject* (*) (GListModel*, guint)) replay_observable_list_real_get_item;
#line 18 "../src/Utils/ObservableList.vala"
	iface->get_item_type = (GType (*) (GListModel*)) replay_observable_list_real_get_item_type;
#line 18 "../src/Utils/ObservableList.vala"
	iface->get_n_items = (guint (*) (GListModel*)) replay_observable_list_real_get_n_items;
#line 815 "ObservableList.c"
}

static void
replay_observable_list_instance_init (ReplayObservableList * self,
                                      gpointer klass)
{
#line 18 "../src/Utils/ObservableList.vala"
	self->priv = replay_observable_list_get_instance_private (self);
#line 824 "ObservableList.c"
}

static void
replay_observable_list_finalize (GObject * obj)
{
	ReplayObservableList * self;
#line 18 "../src/Utils/ObservableList.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, REPLAY_TYPE_OBSERVABLE_LIST, ReplayObservableList);
#line 20 "../src/Utils/ObservableList.vala"
	_g_object_unref0 (self->priv->_data);
#line 18 "../src/Utils/ObservableList.vala"
	G_OBJECT_CLASS (replay_observable_list_parent_class)->finalize (obj);
#line 837 "ObservableList.c"
}

static GType
replay_observable_list_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ReplayObservableListClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) replay_observable_list_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReplayObservableList), 0, (GInstanceInitFunc) replay_observable_list_instance_init, NULL };
	static const GInterfaceInfo g_list_model_info = { (GInterfaceInitFunc) replay_observable_list_g_list_model_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType replay_observable_list_type_id;
	replay_observable_list_type_id = g_type_register_static (GEE_TYPE_ABSTRACT_LIST, "ReplayObservableList", &g_define_type_info, 0);
	g_type_add_interface_static (replay_observable_list_type_id, g_list_model_get_type (), &g_list_model_info);
	ReplayObservableList_private_offset = g_type_add_instance_private (replay_observable_list_type_id, sizeof (ReplayObservableListPrivate));
	return replay_observable_list_type_id;
}

GType
replay_observable_list_get_type (void)
{
	static volatile gsize replay_observable_list_type_id__volatile = 0;
	if (g_once_init_enter (&replay_observable_list_type_id__volatile)) {
		GType replay_observable_list_type_id;
		replay_observable_list_type_id = replay_observable_list_get_type_once ();
		g_once_init_leave (&replay_observable_list_type_id__volatile, replay_observable_list_type_id);
	}
	return replay_observable_list_type_id__volatile;
}

static void
_vala_replay_observable_list_get_property (GObject * object,
                                           guint property_id,
                                           GValue * value,
                                           GParamSpec * pspec)
{
	ReplayObservableList * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, REPLAY_TYPE_OBSERVABLE_LIST, ReplayObservableList);
#line 18 "../src/Utils/ObservableList.vala"
	switch (property_id) {
#line 18 "../src/Utils/ObservableList.vala"
		case REPLAY_OBSERVABLE_LIST_READ_ONLY_PROPERTY:
#line 18 "../src/Utils/ObservableList.vala"
		g_value_set_boolean (value, gee_abstract_collection_get_read_only ((GeeAbstractCollection*) self));
#line 18 "../src/Utils/ObservableList.vala"
		break;
#line 18 "../src/Utils/ObservableList.vala"
		case REPLAY_OBSERVABLE_LIST_SIZE_PROPERTY:
#line 18 "../src/Utils/ObservableList.vala"
		g_value_set_int (value, gee_abstract_collection_get_size ((GeeAbstractCollection*) self));
#line 18 "../src/Utils/ObservableList.vala"
		break;
#line 18 "../src/Utils/ObservableList.vala"
		case REPLAY_OBSERVABLE_LIST_T_TYPE:
#line 18 "../src/Utils/ObservableList.vala"
		g_value_set_gtype (value, self->priv->t_type);
#line 18 "../src/Utils/ObservableList.vala"
		break;
#line 18 "../src/Utils/ObservableList.vala"
		case REPLAY_OBSERVABLE_LIST_T_DUP_FUNC:
#line 18 "../src/Utils/ObservableList.vala"
		g_value_set_pointer (value, self->priv->t_dup_func);
#line 18 "../src/Utils/ObservableList.vala"
		break;
#line 18 "../src/Utils/ObservableList.vala"
		case REPLAY_OBSERVABLE_LIST_T_DESTROY_FUNC:
#line 18 "../src/Utils/ObservableList.vala"
		g_value_set_pointer (value, self->priv->t_destroy_func);
#line 18 "../src/Utils/ObservableList.vala"
		break;
#line 904 "ObservableList.c"
		default:
#line 18 "../src/Utils/ObservableList.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 18 "../src/Utils/ObservableList.vala"
		break;
#line 910 "ObservableList.c"
	}
}

static void
_vala_replay_observable_list_set_property (GObject * object,
                                           guint property_id,
                                           const GValue * value,
                                           GParamSpec * pspec)
{
	ReplayObservableList * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, REPLAY_TYPE_OBSERVABLE_LIST, ReplayObservableList);
#line 18 "../src/Utils/ObservableList.vala"
	switch (property_id) {
#line 18 "../src/Utils/ObservableList.vala"
		case REPLAY_OBSERVABLE_LIST_T_TYPE:
#line 18 "../src/Utils/ObservableList.vala"
		self->priv->t_type = g_value_get_gtype (value);
#line 18 "../src/Utils/ObservableList.vala"
		break;
#line 18 "../src/Utils/ObservableList.vala"
		case REPLAY_OBSERVABLE_LIST_T_DUP_FUNC:
#line 18 "../src/Utils/ObservableList.vala"
		self->priv->t_dup_func = g_value_get_pointer (value);
#line 18 "../src/Utils/ObservableList.vala"
		break;
#line 18 "../src/Utils/ObservableList.vala"
		case REPLAY_OBSERVABLE_LIST_T_DESTROY_FUNC:
#line 18 "../src/Utils/ObservableList.vala"
		self->priv->t_destroy_func = g_value_get_pointer (value);
#line 18 "../src/Utils/ObservableList.vala"
		break;
#line 942 "ObservableList.c"
		default:
#line 18 "../src/Utils/ObservableList.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 18 "../src/Utils/ObservableList.vala"
		break;
#line 948 "ObservableList.c"
	}
}

