/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define APPLICATION_ID "io.github.nahuelwexd.Replay.Devel"

#define GETTEXT_PACKAGE "io.github.nahuelwexd.Replay"

#define LOCALEDIR "share/locale"

#define PROJECT_WEBSITE "https://github.com/nahuelwexd/Replay"

#define RESOURCE_PATH "/io/github/nahuelwexd/Replay"

#define VERSION "0.1.0-7a9a5ec"

