/* AdaptiveMode.c generated by valac 0.50.1.78-abc6b, the Vala compiler
 * generated from AdaptiveMode.vala, do not modify */

/* Replay - An open source YouTube client for GNOME
 * Copyright 2019 - 2020 Nahuel Gomez Castro <nahuel.gomezcastro@outlook.com.ar>
 *
 * Replay is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Replay is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Replay.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <glib-object.h>

typedef enum  {
	REPLAY_ADAPTIVE_MODE_NARROW,
	REPLAY_ADAPTIVE_MODE_NORMAL
} ReplayAdaptiveMode;

#define REPLAY_TYPE_ADAPTIVE_MODE (replay_adaptive_mode_get_type ())

GType replay_adaptive_mode_get_type (void) G_GNUC_CONST ;

static GType
replay_adaptive_mode_get_type_once (void)
{
	static const GEnumValue values[] = {{REPLAY_ADAPTIVE_MODE_NARROW, "REPLAY_ADAPTIVE_MODE_NARROW", "narrow"}, {REPLAY_ADAPTIVE_MODE_NORMAL, "REPLAY_ADAPTIVE_MODE_NORMAL", "normal"}, {0, NULL, NULL}};
	GType replay_adaptive_mode_type_id;
	replay_adaptive_mode_type_id = g_enum_register_static ("ReplayAdaptiveMode", values);
	return replay_adaptive_mode_type_id;
}

GType
replay_adaptive_mode_get_type (void)
{
	static volatile gsize replay_adaptive_mode_type_id__volatile = 0;
	if (g_once_init_enter (&replay_adaptive_mode_type_id__volatile)) {
		GType replay_adaptive_mode_type_id;
		replay_adaptive_mode_type_id = replay_adaptive_mode_get_type_once ();
		g_once_init_leave (&replay_adaptive_mode_type_id__volatile, replay_adaptive_mode_type_id);
	}
	return replay_adaptive_mode_type_id__volatile;
}

