/* HeaderBar.c generated by valac 0.50.1.78-abc6b, the Vala compiler
 * generated from HeaderBar.vala, do not modify */

/* Replay - An open source YouTube client for GNOME
 * Copyright 2019 - 2020 Nahuel Gomez Castro <nahuel.gomezcastro@outlook.com.ar>
 *
 * Replay is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Replay is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Replay.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <handy.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>

#define REPLAY_TYPE_HEADER_BAR (replay_header_bar_get_type ())
#define REPLAY_HEADER_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_HEADER_BAR, ReplayHeaderBar))
#define REPLAY_HEADER_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_HEADER_BAR, ReplayHeaderBarClass))
#define REPLAY_IS_HEADER_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_HEADER_BAR))
#define REPLAY_IS_HEADER_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_HEADER_BAR))
#define REPLAY_HEADER_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_HEADER_BAR, ReplayHeaderBarClass))

typedef struct _ReplayHeaderBar ReplayHeaderBar;
typedef struct _ReplayHeaderBarClass ReplayHeaderBarClass;
typedef struct _ReplayHeaderBarPrivate ReplayHeaderBarPrivate;
typedef enum  {
	REPLAY_ADAPTIVE_MODE_NARROW,
	REPLAY_ADAPTIVE_MODE_NORMAL
} ReplayAdaptiveMode;

#define REPLAY_TYPE_ADAPTIVE_MODE (replay_adaptive_mode_get_type ())
enum  {
	REPLAY_HEADER_BAR_0_PROPERTY,
	REPLAY_HEADER_BAR_ADAPTIVE_MODE_PROPERTY,
	REPLAY_HEADER_BAR_TITLE_PROPERTY,
	REPLAY_HEADER_BAR_NUM_PROPERTIES
};
static GParamSpec* replay_header_bar_properties[REPLAY_HEADER_BAR_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _ReplayHeaderBar {
	GtkWidget parent_instance;
	ReplayHeaderBarPrivate * priv;
};

struct _ReplayHeaderBarClass {
	GtkWidgetClass parent_class;
};

struct _ReplayHeaderBarPrivate {
	HdyHeaderBar* _header_bar;
	GtkSearchEntry* _search_entry;
	GtkStack* _title_stack;
	ReplayAdaptiveMode _adaptive_mode;
	gchar* _title;
};

static gint ReplayHeaderBar_private_offset;
static gpointer replay_header_bar_parent_class = NULL;

GType replay_header_bar_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayHeaderBar, g_object_unref)
GType replay_adaptive_mode_get_type (void) G_GNUC_CONST ;
static void replay_header_bar_real_dispose (GObject* base);
ReplayHeaderBar* replay_header_bar_new (void);
ReplayHeaderBar* replay_header_bar_construct (GType object_type);
ReplayAdaptiveMode replay_header_bar_get_adaptive_mode (ReplayHeaderBar* self);
void replay_header_bar_set_adaptive_mode (ReplayHeaderBar* self,
                                          ReplayAdaptiveMode value);
const gchar* replay_header_bar_get_title (ReplayHeaderBar* self);
void replay_header_bar_set_title (ReplayHeaderBar* self,
                                  const gchar* value);
static void replay_header_bar_finalize (GObject * obj);
static GType replay_header_bar_get_type_once (void);
static void _vala_replay_header_bar_get_property (GObject * object,
                                           guint property_id,
                                           GValue * value,
                                           GParamSpec * pspec);
static void _vala_replay_header_bar_set_property (GObject * object,
                                           guint property_id,
                                           const GValue * value,
                                           GParamSpec * pspec);

static inline gpointer
replay_header_bar_get_instance_private (ReplayHeaderBar* self)
{
	return G_STRUCT_MEMBER_P (self, ReplayHeaderBar_private_offset);
}

static void
replay_header_bar_real_dispose (GObject* base)
{
	ReplayHeaderBar * self;
	HdyHeaderBar* _tmp0_;
#line 51 "../src/Widgets/HeaderBar.vala"
	self = (ReplayHeaderBar*) base;
#line 53 "../src/Widgets/HeaderBar.vala"
	_tmp0_ = self->priv->_header_bar;
#line 53 "../src/Widgets/HeaderBar.vala"
	gtk_widget_unparent ((GtkWidget*) _tmp0_);
#line 54 "../src/Widgets/HeaderBar.vala"
	G_OBJECT_CLASS (replay_header_bar_parent_class)->dispose ((GObject*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_widget_get_type (), GtkWidget));
#line 117 "HeaderBar.c"
}

ReplayHeaderBar*
replay_header_bar_construct (GType object_type)
{
	ReplayHeaderBar * self = NULL;
#line 19 "../src/Widgets/HeaderBar.vala"
	self = (ReplayHeaderBar*) g_object_new (object_type, NULL);
#line 19 "../src/Widgets/HeaderBar.vala"
	return self;
#line 128 "HeaderBar.c"
}

ReplayHeaderBar*
replay_header_bar_new (void)
{
#line 19 "../src/Widgets/HeaderBar.vala"
	return replay_header_bar_construct (REPLAY_TYPE_HEADER_BAR);
#line 136 "HeaderBar.c"
}

ReplayAdaptiveMode
replay_header_bar_get_adaptive_mode (ReplayHeaderBar* self)
{
	ReplayAdaptiveMode result;
	ReplayAdaptiveMode _tmp0_;
#line 30 "../src/Widgets/HeaderBar.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 30 "../src/Widgets/HeaderBar.vala"
	_tmp0_ = self->priv->_adaptive_mode;
#line 30 "../src/Widgets/HeaderBar.vala"
	result = _tmp0_;
#line 30 "../src/Widgets/HeaderBar.vala"
	return result;
#line 152 "HeaderBar.c"
}

void
replay_header_bar_set_adaptive_mode (ReplayHeaderBar* self,
                                     ReplayAdaptiveMode value)
{
	ReplayAdaptiveMode _tmp0_;
	ReplayAdaptiveMode _tmp1_;
#line 31 "../src/Widgets/HeaderBar.vala"
	g_return_if_fail (self != NULL);
#line 33 "../src/Widgets/HeaderBar.vala"
	_tmp0_ = self->priv->_adaptive_mode;
#line 33 "../src/Widgets/HeaderBar.vala"
	if (_tmp0_ == value) {
#line 33 "../src/Widgets/HeaderBar.vala"
		return;
#line 169 "HeaderBar.c"
	}
#line 34 "../src/Widgets/HeaderBar.vala"
	self->priv->_adaptive_mode = value;
#line 36 "../src/Widgets/HeaderBar.vala"
	_tmp1_ = self->priv->_adaptive_mode;
#line 36 "../src/Widgets/HeaderBar.vala"
	switch (_tmp1_) {
#line 36 "../src/Widgets/HeaderBar.vala"
		case REPLAY_ADAPTIVE_MODE_NARROW:
#line 179 "HeaderBar.c"
		{
			GtkStack* _tmp2_;
#line 39 "../src/Widgets/HeaderBar.vala"
			_tmp2_ = self->priv->_title_stack;
#line 39 "../src/Widgets/HeaderBar.vala"
			gtk_stack_set_visible_child_name (_tmp2_, "title-label");
#line 40 "../src/Widgets/HeaderBar.vala"
			break;
#line 188 "HeaderBar.c"
		}
#line 36 "../src/Widgets/HeaderBar.vala"
		case REPLAY_ADAPTIVE_MODE_NORMAL:
#line 192 "HeaderBar.c"
		{
			GtkStack* _tmp3_;
#line 42 "../src/Widgets/HeaderBar.vala"
			_tmp3_ = self->priv->_title_stack;
#line 42 "../src/Widgets/HeaderBar.vala"
			gtk_stack_set_visible_child_name (_tmp3_, "search-entry");
#line 43 "../src/Widgets/HeaderBar.vala"
			break;
#line 201 "HeaderBar.c"
		}
		default:
#line 36 "../src/Widgets/HeaderBar.vala"
		break;
#line 206 "HeaderBar.c"
	}
#line 31 "../src/Widgets/HeaderBar.vala"
	g_object_notify_by_pspec ((GObject *) self, replay_header_bar_properties[REPLAY_HEADER_BAR_ADAPTIVE_MODE_PROPERTY]);
#line 210 "HeaderBar.c"
}

const gchar*
replay_header_bar_get_title (ReplayHeaderBar* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 48 "../src/Widgets/HeaderBar.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 48 "../src/Widgets/HeaderBar.vala"
	_tmp0_ = self->priv->_title;
#line 48 "../src/Widgets/HeaderBar.vala"
	result = _tmp0_;
#line 48 "../src/Widgets/HeaderBar.vala"
	return result;
#line 226 "HeaderBar.c"
}

void
replay_header_bar_set_title (ReplayHeaderBar* self,
                             const gchar* value)
{
#line 48 "../src/Widgets/HeaderBar.vala"
	g_return_if_fail (self != NULL);
#line 48 "../src/Widgets/HeaderBar.vala"
	if (g_strcmp0 (value, replay_header_bar_get_title (self)) != 0) {
#line 237 "HeaderBar.c"
		gchar* _tmp0_;
#line 48 "../src/Widgets/HeaderBar.vala"
		_tmp0_ = g_strdup (value);
#line 48 "../src/Widgets/HeaderBar.vala"
		_g_free0 (self->priv->_title);
#line 48 "../src/Widgets/HeaderBar.vala"
		self->priv->_title = _tmp0_;
#line 48 "../src/Widgets/HeaderBar.vala"
		g_object_notify_by_pspec ((GObject *) self, replay_header_bar_properties[REPLAY_HEADER_BAR_TITLE_PROPERTY]);
#line 247 "HeaderBar.c"
	}
}

static void
replay_header_bar_class_init (ReplayHeaderBarClass * klass,
                              gpointer klass_data)
{
#line 19 "../src/Widgets/HeaderBar.vala"
	replay_header_bar_parent_class = g_type_class_peek_parent (klass);
#line 19 "../src/Widgets/HeaderBar.vala"
	g_type_class_adjust_private_offset (klass, &ReplayHeaderBar_private_offset);
#line 19 "../src/Widgets/HeaderBar.vala"
	((GObjectClass *) klass)->dispose = (void (*) (GObject*)) replay_header_bar_real_dispose;
#line 19 "../src/Widgets/HeaderBar.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_replay_header_bar_get_property;
#line 19 "../src/Widgets/HeaderBar.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_replay_header_bar_set_property;
#line 19 "../src/Widgets/HeaderBar.vala"
	G_OBJECT_CLASS (klass)->finalize = replay_header_bar_finalize;
#line 19 "../src/Widgets/HeaderBar.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_HEADER_BAR_ADAPTIVE_MODE_PROPERTY, replay_header_bar_properties[REPLAY_HEADER_BAR_ADAPTIVE_MODE_PROPERTY] = g_param_spec_enum ("adaptive-mode", "adaptive-mode", "adaptive-mode", REPLAY_TYPE_ADAPTIVE_MODE, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 19 "../src/Widgets/HeaderBar.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_HEADER_BAR_TITLE_PROPERTY, replay_header_bar_properties[REPLAY_HEADER_BAR_TITLE_PROPERTY] = g_param_spec_string ("title", "title", "title", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 19 "../src/Widgets/HeaderBar.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/io/github/nahuelwexd/Replay/HeaderBar.ui");
#line 19 "../src/Widgets/HeaderBar.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "_header_bar", FALSE, ReplayHeaderBar_private_offset + G_STRUCT_OFFSET (ReplayHeaderBarPrivate, _header_bar));
#line 19 "../src/Widgets/HeaderBar.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "_search_entry", FALSE, ReplayHeaderBar_private_offset + G_STRUCT_OFFSET (ReplayHeaderBarPrivate, _search_entry));
#line 19 "../src/Widgets/HeaderBar.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "_title_stack", FALSE, ReplayHeaderBar_private_offset + G_STRUCT_OFFSET (ReplayHeaderBarPrivate, _title_stack));
#line 279 "HeaderBar.c"
}

static void
replay_header_bar_instance_init (ReplayHeaderBar * self,
                                 gpointer klass)
{
#line 19 "../src/Widgets/HeaderBar.vala"
	self->priv = replay_header_bar_get_instance_private (self);
#line 19 "../src/Widgets/HeaderBar.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 290 "HeaderBar.c"
}

static void
replay_header_bar_finalize (GObject * obj)
{
	ReplayHeaderBar * self;
#line 19 "../src/Widgets/HeaderBar.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, REPLAY_TYPE_HEADER_BAR, ReplayHeaderBar);
#line 21 "../src/Widgets/HeaderBar.vala"
	_g_object_unref0 (self->priv->_header_bar);
#line 22 "../src/Widgets/HeaderBar.vala"
	_g_object_unref0 (self->priv->_search_entry);
#line 23 "../src/Widgets/HeaderBar.vala"
	_g_object_unref0 (self->priv->_title_stack);
#line 48 "../src/Widgets/HeaderBar.vala"
	_g_free0 (self->priv->_title);
#line 19 "../src/Widgets/HeaderBar.vala"
	G_OBJECT_CLASS (replay_header_bar_parent_class)->finalize (obj);
#line 309 "HeaderBar.c"
}

static GType
replay_header_bar_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ReplayHeaderBarClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) replay_header_bar_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReplayHeaderBar), 0, (GInstanceInitFunc) replay_header_bar_instance_init, NULL };
	GType replay_header_bar_type_id;
	replay_header_bar_type_id = g_type_register_static (gtk_widget_get_type (), "ReplayHeaderBar", &g_define_type_info, 0);
	ReplayHeaderBar_private_offset = g_type_add_instance_private (replay_header_bar_type_id, sizeof (ReplayHeaderBarPrivate));
	return replay_header_bar_type_id;
}

GType
replay_header_bar_get_type (void)
{
	static volatile gsize replay_header_bar_type_id__volatile = 0;
	if (g_once_init_enter (&replay_header_bar_type_id__volatile)) {
		GType replay_header_bar_type_id;
		replay_header_bar_type_id = replay_header_bar_get_type_once ();
		g_once_init_leave (&replay_header_bar_type_id__volatile, replay_header_bar_type_id);
	}
	return replay_header_bar_type_id__volatile;
}

static void
_vala_replay_header_bar_get_property (GObject * object,
                                      guint property_id,
                                      GValue * value,
                                      GParamSpec * pspec)
{
	ReplayHeaderBar * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, REPLAY_TYPE_HEADER_BAR, ReplayHeaderBar);
#line 19 "../src/Widgets/HeaderBar.vala"
	switch (property_id) {
#line 19 "../src/Widgets/HeaderBar.vala"
		case REPLAY_HEADER_BAR_ADAPTIVE_MODE_PROPERTY:
#line 19 "../src/Widgets/HeaderBar.vala"
		g_value_set_enum (value, replay_header_bar_get_adaptive_mode (self));
#line 19 "../src/Widgets/HeaderBar.vala"
		break;
#line 19 "../src/Widgets/HeaderBar.vala"
		case REPLAY_HEADER_BAR_TITLE_PROPERTY:
#line 19 "../src/Widgets/HeaderBar.vala"
		g_value_set_string (value, replay_header_bar_get_title (self));
#line 19 "../src/Widgets/HeaderBar.vala"
		break;
#line 356 "HeaderBar.c"
		default:
#line 19 "../src/Widgets/HeaderBar.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 19 "../src/Widgets/HeaderBar.vala"
		break;
#line 362 "HeaderBar.c"
	}
}

static void
_vala_replay_header_bar_set_property (GObject * object,
                                      guint property_id,
                                      const GValue * value,
                                      GParamSpec * pspec)
{
	ReplayHeaderBar * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, REPLAY_TYPE_HEADER_BAR, ReplayHeaderBar);
#line 19 "../src/Widgets/HeaderBar.vala"
	switch (property_id) {
#line 19 "../src/Widgets/HeaderBar.vala"
		case REPLAY_HEADER_BAR_ADAPTIVE_MODE_PROPERTY:
#line 19 "../src/Widgets/HeaderBar.vala"
		replay_header_bar_set_adaptive_mode (self, g_value_get_enum (value));
#line 19 "../src/Widgets/HeaderBar.vala"
		break;
#line 19 "../src/Widgets/HeaderBar.vala"
		case REPLAY_HEADER_BAR_TITLE_PROPERTY:
#line 19 "../src/Widgets/HeaderBar.vala"
		replay_header_bar_set_title (self, g_value_get_string (value));
#line 19 "../src/Widgets/HeaderBar.vala"
		break;
#line 388 "HeaderBar.c"
		default:
#line 19 "../src/Widgets/HeaderBar.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 19 "../src/Widgets/HeaderBar.vala"
		break;
#line 394 "HeaderBar.c"
	}
}

