/* Page.c generated by valac 0.50.1.78-abc6b, the Vala compiler
 * generated from Page.vala, do not modify */

/* Replay - An open source YouTube client for GNOME
 * Copyright 2019 - 2020 Nahuel Gomez Castro <nahuel.gomezcastro@outlook.com.ar>
 *
 * Replay is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Replay is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Replay.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>

#define REPLAY_TYPE_PAGE (replay_page_get_type ())
#define REPLAY_PAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPLAY_TYPE_PAGE, ReplayPage))
#define REPLAY_PAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPLAY_TYPE_PAGE, ReplayPageClass))
#define REPLAY_IS_PAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPLAY_TYPE_PAGE))
#define REPLAY_IS_PAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPLAY_TYPE_PAGE))
#define REPLAY_PAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPLAY_TYPE_PAGE, ReplayPageClass))

typedef struct _ReplayPage ReplayPage;
typedef struct _ReplayPageClass ReplayPageClass;
typedef struct _ReplayPagePrivate ReplayPagePrivate;
enum  {
	REPLAY_PAGE_0_PROPERTY,
	REPLAY_PAGE_CHILD_PROPERTY,
	REPLAY_PAGE_NUM_PROPERTIES
};
static GParamSpec* replay_page_properties[REPLAY_PAGE_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _ReplayPage {
	GtkWidget parent_instance;
	ReplayPagePrivate * priv;
};

struct _ReplayPageClass {
	GtkWidgetClass parent_class;
};

struct _ReplayPagePrivate {
	GtkWidget* _child;
};

static gint ReplayPage_private_offset;
static gpointer replay_page_parent_class = NULL;
static GtkBuildableIface * replay_page_gtk_buildable_parent_iface = NULL;

GType replay_page_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReplayPage, g_object_unref)
static void replay_page_real_add_child (GtkBuildable* base,
                                 GtkBuilder* builder,
                                 GObject* child,
                                 const gchar* type);
void replay_page_set_child (ReplayPage* self,
                            GtkWidget* value);
static void replay_page_real_dispose (GObject* base);
ReplayPage* replay_page_new (void);
ReplayPage* replay_page_construct (GType object_type);
GtkWidget* replay_page_get_child (ReplayPage* self);
static void replay_page_finalize (GObject * obj);
static GType replay_page_get_type_once (void);
static void _vala_replay_page_get_property (GObject * object,
                                     guint property_id,
                                     GValue * value,
                                     GParamSpec * pspec);
static void _vala_replay_page_set_property (GObject * object,
                                     guint property_id,
                                     const GValue * value,
                                     GParamSpec * pspec);

static inline gpointer
replay_page_get_instance_private (ReplayPage* self)
{
	return G_STRUCT_MEMBER_P (self, ReplayPage_private_offset);
}

static void
replay_page_real_add_child (GtkBuildable* base,
                            GtkBuilder* builder,
                            GObject* child,
                            const gchar* type)
{
	ReplayPage * self;
#line 41 "../src/Widgets/Page.vala"
	self = (ReplayPage*) base;
#line 41 "../src/Widgets/Page.vala"
	g_return_if_fail (builder != NULL);
#line 41 "../src/Widgets/Page.vala"
	g_return_if_fail (child != NULL);
#line 41 "../src/Widgets/Page.vala"
	_vala_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (child, gtk_widget_get_type ()), "child is Gtk.Widget");
#line 44 "../src/Widgets/Page.vala"
	replay_page_set_child (self, G_TYPE_CHECK_INSTANCE_CAST (child, gtk_widget_get_type (), GtkWidget));
#line 113 "Page.c"
}

static void
replay_page_real_dispose (GObject* base)
{
	ReplayPage * self;
#line 47 "../src/Widgets/Page.vala"
	self = (ReplayPage*) base;
#line 49 "../src/Widgets/Page.vala"
	replay_page_set_child (self, NULL);
#line 50 "../src/Widgets/Page.vala"
	G_OBJECT_CLASS (replay_page_parent_class)->dispose ((GObject*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_widget_get_type (), GtkWidget));
#line 126 "Page.c"
}

ReplayPage*
replay_page_construct (GType object_type)
{
	ReplayPage * self = NULL;
#line 18 "../src/Widgets/Page.vala"
	self = (ReplayPage*) g_object_new (object_type, NULL);
#line 18 "../src/Widgets/Page.vala"
	return self;
#line 137 "Page.c"
}

ReplayPage*
replay_page_new (void)
{
#line 18 "../src/Widgets/Page.vala"
	return replay_page_construct (REPLAY_TYPE_PAGE);
#line 145 "Page.c"
}

GtkWidget*
replay_page_get_child (ReplayPage* self)
{
	GtkWidget* result;
	GtkWidget* _tmp0_;
#line 25 "../src/Widgets/Page.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 25 "../src/Widgets/Page.vala"
	_tmp0_ = self->priv->_child;
#line 25 "../src/Widgets/Page.vala"
	result = _tmp0_;
#line 25 "../src/Widgets/Page.vala"
	return result;
#line 161 "Page.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 33 "../src/Widgets/Page.vala"
	return self ? g_object_ref (self) : NULL;
#line 169 "Page.c"
}

void
replay_page_set_child (ReplayPage* self,
                       GtkWidget* value)
{
	GtkWidget* _tmp0_;
	GtkWidget* _tmp1_;
	GtkWidget* _tmp3_;
	GtkWidget* _tmp4_;
#line 26 "../src/Widgets/Page.vala"
	g_return_if_fail (self != NULL);
#line 28 "../src/Widgets/Page.vala"
	_tmp0_ = self->priv->_child;
#line 28 "../src/Widgets/Page.vala"
	if (_tmp0_ == value) {
#line 28 "../src/Widgets/Page.vala"
		return;
#line 188 "Page.c"
	}
#line 30 "../src/Widgets/Page.vala"
	_tmp1_ = self->priv->_child;
#line 30 "../src/Widgets/Page.vala"
	if (_tmp1_ != NULL) {
#line 194 "Page.c"
		GtkWidget* _tmp2_;
#line 31 "../src/Widgets/Page.vala"
		_tmp2_ = self->priv->_child;
#line 31 "../src/Widgets/Page.vala"
		gtk_widget_unparent (G_TYPE_CHECK_INSTANCE_CAST (_tmp2_, gtk_widget_get_type (), GtkWidget));
#line 200 "Page.c"
	}
#line 33 "../src/Widgets/Page.vala"
	_tmp3_ = _g_object_ref0 (value);
#line 33 "../src/Widgets/Page.vala"
	_g_object_unref0 (self->priv->_child);
#line 33 "../src/Widgets/Page.vala"
	self->priv->_child = _tmp3_;
#line 35 "../src/Widgets/Page.vala"
	_tmp4_ = self->priv->_child;
#line 35 "../src/Widgets/Page.vala"
	if (_tmp4_ != NULL) {
#line 212 "Page.c"
		GtkWidget* _tmp5_;
#line 36 "../src/Widgets/Page.vala"
		_tmp5_ = self->priv->_child;
#line 36 "../src/Widgets/Page.vala"
		gtk_widget_set_parent (G_TYPE_CHECK_INSTANCE_CAST (_tmp5_, gtk_widget_get_type (), GtkWidget), (GtkWidget*) self);
#line 218 "Page.c"
	}
#line 26 "../src/Widgets/Page.vala"
	g_object_notify_by_pspec ((GObject *) self, replay_page_properties[REPLAY_PAGE_CHILD_PROPERTY]);
#line 222 "Page.c"
}

static void
replay_page_class_init (ReplayPageClass * klass,
                        gpointer klass_data)
{
#line 18 "../src/Widgets/Page.vala"
	replay_page_parent_class = g_type_class_peek_parent (klass);
#line 18 "../src/Widgets/Page.vala"
	g_type_class_adjust_private_offset (klass, &ReplayPage_private_offset);
#line 18 "../src/Widgets/Page.vala"
	((GObjectClass *) klass)->dispose = (void (*) (GObject*)) replay_page_real_dispose;
#line 18 "../src/Widgets/Page.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_replay_page_get_property;
#line 18 "../src/Widgets/Page.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_replay_page_set_property;
#line 18 "../src/Widgets/Page.vala"
	G_OBJECT_CLASS (klass)->finalize = replay_page_finalize;
#line 18 "../src/Widgets/Page.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPLAY_PAGE_CHILD_PROPERTY, replay_page_properties[REPLAY_PAGE_CHILD_PROPERTY] = g_param_spec_object ("child", "child", "child", gtk_widget_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 56 "../src/Widgets/Page.vala"
	gtk_widget_class_set_layout_manager_type (GTK_WIDGET_CLASS (klass), gtk_bin_layout_get_type ());
#line 245 "Page.c"
}

static void
replay_page_gtk_buildable_interface_init (GtkBuildableIface * iface,
                                          gpointer iface_data)
{
#line 18 "../src/Widgets/Page.vala"
	replay_page_gtk_buildable_parent_iface = g_type_interface_peek_parent (iface);
#line 18 "../src/Widgets/Page.vala"
	iface->add_child = (void (*) (GtkBuildable*, GtkBuilder*, GObject*, const gchar*)) replay_page_real_add_child;
#line 256 "Page.c"
}

static void
replay_page_instance_init (ReplayPage * self,
                           gpointer klass)
{
#line 18 "../src/Widgets/Page.vala"
	self->priv = replay_page_get_instance_private (self);
#line 265 "Page.c"
}

static void
replay_page_finalize (GObject * obj)
{
	ReplayPage * self;
#line 18 "../src/Widgets/Page.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, REPLAY_TYPE_PAGE, ReplayPage);
#line 20 "../src/Widgets/Page.vala"
	_g_object_unref0 (self->priv->_child);
#line 18 "../src/Widgets/Page.vala"
	G_OBJECT_CLASS (replay_page_parent_class)->finalize (obj);
#line 278 "Page.c"
}

static GType
replay_page_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ReplayPageClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) replay_page_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReplayPage), 0, (GInstanceInitFunc) replay_page_instance_init, NULL };
	static const GInterfaceInfo gtk_buildable_info = { (GInterfaceInitFunc) replay_page_gtk_buildable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType replay_page_type_id;
	replay_page_type_id = g_type_register_static (gtk_widget_get_type (), "ReplayPage", &g_define_type_info, 0);
	g_type_add_interface_static (replay_page_type_id, gtk_buildable_get_type (), &gtk_buildable_info);
	ReplayPage_private_offset = g_type_add_instance_private (replay_page_type_id, sizeof (ReplayPagePrivate));
	return replay_page_type_id;
}

GType
replay_page_get_type (void)
{
	static volatile gsize replay_page_type_id__volatile = 0;
	if (g_once_init_enter (&replay_page_type_id__volatile)) {
		GType replay_page_type_id;
		replay_page_type_id = replay_page_get_type_once ();
		g_once_init_leave (&replay_page_type_id__volatile, replay_page_type_id);
	}
	return replay_page_type_id__volatile;
}

static void
_vala_replay_page_get_property (GObject * object,
                                guint property_id,
                                GValue * value,
                                GParamSpec * pspec)
{
	ReplayPage * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, REPLAY_TYPE_PAGE, ReplayPage);
#line 18 "../src/Widgets/Page.vala"
	switch (property_id) {
#line 18 "../src/Widgets/Page.vala"
		case REPLAY_PAGE_CHILD_PROPERTY:
#line 18 "../src/Widgets/Page.vala"
		g_value_set_object (value, replay_page_get_child (self));
#line 18 "../src/Widgets/Page.vala"
		break;
#line 321 "Page.c"
		default:
#line 18 "../src/Widgets/Page.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 18 "../src/Widgets/Page.vala"
		break;
#line 327 "Page.c"
	}
}

static void
_vala_replay_page_set_property (GObject * object,
                                guint property_id,
                                const GValue * value,
                                GParamSpec * pspec)
{
	ReplayPage * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, REPLAY_TYPE_PAGE, ReplayPage);
#line 18 "../src/Widgets/Page.vala"
	switch (property_id) {
#line 18 "../src/Widgets/Page.vala"
		case REPLAY_PAGE_CHILD_PROPERTY:
#line 18 "../src/Widgets/Page.vala"
		replay_page_set_child (self, g_value_get_object (value));
#line 18 "../src/Widgets/Page.vala"
		break;
#line 347 "Page.c"
		default:
#line 18 "../src/Widgets/Page.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 18 "../src/Widgets/Page.vala"
		break;
#line 353 "Page.c"
	}
}

